### ISSUE TITLE
directory not found issue with CFM based connector

### ISSUE THREAD

**Issue by douglasknudsen** [simogeo/Filemanager#159]
This is occurring in the latest CF10 due to a change in the variable cgi.PATH_INFO.  A discussion can be seen here

http://forums.adobe.com/message/5201741

Changing the last line in the method $getRoot im accessors.cfm to this will do the trick

<cfargument name="cgiTemplatePath" type="string" required="false" default="#getDirectoryFromPath(CGI.SCRIPT_NAME)#" />

DK

**Comment by simogeo** [comment]
Will be reopened in case a CFM maintainer let him know

**Comment by cfmaniac** [comment]
The Fix that @douglasknudsen is referring to is:
<cfargument name="cgiTemplatePath" type="string" required="false" default="#GetDirectoryFromPath(cgi.path_info)#" />
To:
<cfargument name="cgiTemplatePath" type="string" required="false" default="#getDirectoryFromPath(CGI.SCRIPT_NAME)#" />
I confirm that this works on CF10.
