### ISSUE TITLE
Not able to download the uploaded files.

### ISSUE THREAD

**Issue by pankajparashar-zz** [simogeo/Filemanager#162]
I am not able to download the files that I just uploaded. Co-incidentally the demo link - http://fm.linea21.com/ also has the same problem.

Is this a known issue?

**Comment by servocoder** [comment]
Try chunked upload at [RichFilemanager](https://github.com/servocoder/RichFilemanager)

**Comment by kyme32** [comment]
I've already fixed it in old way with direct linking to file, it's still and negative size file for 4gb file but ehh i can live with it, it would be grate to have this option to activate an direct linking on download to avoid this situation tho...
One more thing, i've got 0 info about multiusers, as i try to use same script for 2 pages with different root in 0.8 was easy to do so adding 2nd config, but on info from wiki i've understood almost nothing...add users file php where?it's a lil confusing and i've tried multimple combos and nothing so i've end up having filemanager.min 2 times with different config files linked to it.
It would be grate to add mire details to that section, the big story i've got it, but where to create that file...no idea
Just sayin'
Thank you
