### ISSUE TITLE
having differents configurations 

### ISSUE THREAD

**Issue by rafmix** [simogeo/Filemanager#255]
Hi, 
first, thanks for your work.

I use the filemenager with Ckeditor, loade by jquery,  and I need to make different configuration, not only for the folder. For exemple, in one case, user can upload image, in another case, only .xls.

I tried different solution, the only one that I founded is to duplicate your application in order to change the filemanager.config.js for each case. Is it a better solution?
Thanks in advance for your answer.
Raf

**Comment by kaptk2** [comment]
What about being able to pass in the config file similar to how exclusive folders are handled? Something like index.html?config=configFileName.js would be nice.

**Comment by simogeo** [comment]
Should be now possible. See last commit and following doc : https://github.com/simogeo/Filemanager/wiki/Passing-parameters-to-the-FM#passing-a-config-file
