### ISSUE TITLE
Modification in setFileRoot

### ISSUE THREAD

**Issue by sandeepbisht** [simogeo/Filemanager#258]
## Problem

Note:May be this is an issue or i am integrating it wrong.

Images folder location in server is /var/www/html/public/images

I am using it as
$fm->setFileRoot("/public/images");

I created a folder using filemanager it successfully created.In attempt of deleting the folder I am getting "Invalid directory of file' error

When i enable the log of getFullPath.Then logs prints as

returned path : /var/www/html/public/images/public/images/My_folder/

It should be /var/www/html/public/images/My_folder/
## Solution

I done following change in code and it worked

Changes are in setFileRoot function(filemanager.class.php) when setting dynamic_fileRoot

$this->dynamic_fileroot = str_replace("//","/",str_replace($_SERVER['DOCUMENT_ROOT'], '', $this->doc_root));

**Comment by rocketmanPHP** [comment]
I had issue with this plugin after adding dynamic root in user.config.php for matching userID with directory. I was getting No Way when I try to delete file, everything else was working properly.

@sandeepbisht with your solution now I am able to delete files.

Thank you.

**Comment by simogeo** [comment]
I don't have much time so I integrated the proposed fix without taking much time to analyse. If someone could explain it would be nice. Thanks

**Comment by rocketmanPHP** [comment]
@simogeo Thank you, and thank you for this great plugin.
