### ISSUE TITLE
filemanager with classic asp connector

### ISSUE THREAD

**Issue by rccinar** [simogeo/Filemanager#273]
hello. first of all thank you for you dont forget classic asp coders. i have a problem with configuration the script. i could not define upload folder for the script. i tried all versions of the cong file the variables serverRoot, fileRoot and relPath also userPath in filemanager.config.asp. what must i do for i can see the files in your browser. because of this problem only loading animation seem on browser. Pls help me. 
Pls give an example for windows iis server path samples.

**Comment by abrhim2222** [comment]
sorry do u have documents for install ?
