### ISSUE TITLE
Left filetree view sometimes appears strange 

### ISSUE THREAD

**Issue by frzsombor** [simogeo/Filemanager#302]
Sometimes (but relatively often: 1/10) the left filetree fails to load successfully.
Problem occurs in Chrome and Firefox too.

See the (low quality - sorry again) screen recording:
http://tinypic.com/r/2088h90/8

**Comment by simogeo** [comment]
This should really be ok now : 8e39541d9bb4885f44992a6b6239139c2112548f

**Comment by frzsombor** [comment]
Sorry, I didn't have time for this issue during the holidays.
But now it works for me too! Thanks!
