### ISSUE TITLE
Bootstrap + Angular

### ISSUE THREAD

**Issue by joni2back** [simogeo/Filemanager#305]
@simogeo I guess would be very important for this project to refactor the frontend using a javascript framework such as AngularJS (or Knockout) and CSS library like Bootstrap3.
What do you think?

**Comment by simogeo** [comment]
Hi joni2back, 
I'm not very familiar with angularJS and I'm not sure implementing Bootstrap3 is worth value.

1. Regarding the first point, I'm not opposed to refactor the project using AngularJS but I'd be happy to see advantages of that. Could you tell me more ? Another point is that I would have few time for doing that. But some users may be ready to help or do it ??

2. Regarding Bootstrap3. It is, indeed, a nice framework but a bit heavy. I want to keep the Filemanager as light as possible. And I guess Bootstrap3 could be implemented with the available theme template mechanism right now - If needed, I'm ready to adjust the current mechanism to make it fully compatible. Also, in that case, I would appreciate you provide Bootstrap3 theme.

Waiting your thoughts / arguments regarding these points.
Thanks for sharing.

**Comment by joni2back** [comment]
I was working on [@angular-filemanager](https://github.com/joni2back/angular-filemanager) [[limited demo]](http://zendelsolutions.com/zendel/projects/angular-filemanager)
The idea is to use also many connectors in different languages.
Would be nice to start a new project, based on these projects together, using your backend and my frontend.

**Comment by th-schwarz** [comment]
@joni2back Is there any API-docu for connectors available?

**Comment by joni2back** [comment]
Not yet, I'll make this asap!!

**Comment by joni2back** [comment]
@th-schwarz API doc ready! [angular-filemanager-docs](https://github.com/joni2back/angular-filemanager/blob/master/README.md)

**Comment by simogeo** [comment]
Great work @joni2back 

Just few remarks / questions : 

>  The idea is to use also many connectors in different languages.

From my FM experience, I've seen this not not realistic to have many connectors and have ongoing development. Hope you will have more success.

> Would be nice to start a new project, based on these projects together, using your backend and my frontend.

Why not, but why to change the API ? Is this related to angular ?

Another question : how will you handle the config file ?

**Comment by joni2back** [comment]
@simogeo 
I prefer to make new json api, principally to avoid to use GET requests.
For example, I guess the file list in this api is more predictable to handle the items..

Regarding the config file, there are a momentarily config.js file, that defines the api urls, and other misc parameters.. But is great idea to have a default config to extend, I'll working on that..

--------------
@th-schwarz
Did you check the doc?

**Comment by th-schwarz** [comment]
@joni2back  Yes, thanks. But at the moment, I'm busy and the next weeks I'll be in holiday ...
The API seems to be nice and clear.

Like simogeo I'm missing the handling of the configuration. A kind of shared configuration is needed, I guess! Or do you want a splitted configuration, one for the backend and one for the frontend?

**Comment by simogeo** [comment]
If interested by project please follow : https://github.com/joni2back/angular-filemanager
