### ISSUE TITLE
is_valid_path() doesn't work on WAMP

### ISSUE THREAD

**Issue by pers0n** [simogeo/Filemanager#306]
For example it is trying to compare:
C:/www/mysite/Filemanager-2.0.0/userfiles/
with
C:\www\mysite\Filemanager-2.0.0\userfiles/

and of course it fails.

I fixed it by using realpath() a PHP function

line#87 $this->path_to_files = realpath($this->path_to_files);//MODIFIED
line#990 $full_path = realpath($full_path);//MODIFIED

**Comment by simogeo** [comment]
It is now supposed to be fixed : 23d60d2a69576e4ae755e3a6e513096d22775962
Thanks for reporting
