### ISSUE TITLE
Pre-uploaded images without generated thumbnails

### ISSUE THREAD

**Issue by frzsombor** [simogeo/Filemanager#307]
I just found that if I copy a few images to Filemanager's root folder, `connectors/php/filemanager.php?mode=preview&path=/filename.jpg&1420506138&thumbnail=true` will "_500 (Internal Server Error)_" on these images in the "grid" view, because Filemanager will look for the thumbs, but - of course - will never find them. Maybe a check for an existing thumbnail would be a good idea, and if no thumbnail found, the proper images/fileicons/_fileext_.png should be displayed.

**Comment by simogeo** [comment]
The [preview()](https://github.com/simogeo/Filemanager/blob/master/connectors/php/filemanager.class.php#L844) method will generate automatically the thumbnail if needed.

I guess it is a permissions issue. Is your file readable by Apache user when uploading it through FTP ? 
Is your file displaying when clicking on it ?

**Comment by frzsombor** [comment]
Hmm, thats strange, it works on my OSX, but not on my Windows. Also forget the FTP thing, I've edited it out, I've only experienced this issue on my Windows. But on Windows, there shouldn't be any permission issue I think. I will post an update soon, later today.

**Comment by simogeo** [comment]
You can check if the thumbnail is created in `_thumbs` folder. Be sure the extension is in lowercase

**Comment by frzsombor** [comment]
Well, it's a strange situation, because I feel like the issue here is not related to permissions (since I only noticed this on windows), however since I've updated Filemanager to the latest version (e157f436ccf2ed86f981622a451b85e32c49e37d) I'm not able to reproduce the bug.
