### ISSUE TITLE
Safer handling of files and folders (permission)

### ISSUE THREAD

**Issue by frzsombor** [simogeo/Filemanager#308]
I know this "issue" is based on a very rare situation, but I think you can never be too careful.

So, it looks like if Filemanager has no read access on a file or folder, it will just hang and the php connector will return an error.

With folders, there are already a check [here](https://github.com/simogeo/Filemanager/blob/3b53705e22f7a4128aa47bc0a61c3eb8dadbc41e/connectors/php/filemanager.class.php#L225), but according to [the php manual](http://php.net/manual/en/function.opendir.php#refsect1-function.opendir-returnvalues) opendir can throw an error if it encounters a permission restriction or filesystem error, so it's better to add a '@' here:
`if(!$handle = @opendir($current_path)) {`

With files, there are no such check, but adding 
`if(!is_readable($this->getFullPath($current_path))) return;`
to [here](https://github.com/simogeo/Filemanager/blob/3b53705e22f7a4128aa47bc0a61c3eb8dadbc41e/connectors/php/filemanager.class.php#L929) solved the connector's error for me and displayed the file with the default icon, but I don't know if this _return_ can cause any issues there.

**Comment by simogeo** [comment]
> With folders, there are already a check here, but according to the php manual opendir can throw an error if it encounters a permission restriction or filesystem error, so it's better to add a '@' here:
if(!$handle = @opendir($current_path)) {

I don't see any utility here to remove warning since it is handled as an error. According to me, it is more explicit to display an error message here.

> With files, there are no such check, but adding
if(!is_readable($this->getFullPath($current_path))) return;
to here solved the connector's error for me and displayed the file with the default icon, but I don't know if this return can cause any issues there.

It would probably not cause other issue but the file would still not be readable when clicking it, no ?

**Comment by frzsombor** [comment]
If I don't add '@' before opendir, and I try to open a directory that I don't have read access to, filemanager.php will return with _Status Code: 500 Internal Server Error_ and a response like this:
```
{"error":{"type":"ErrorException","message":"opendir(\/path\/to\/uploads\/protected\/): failed to open dir: Permission denied","file":"\/path\/to\/fileman\/connectors\/php\/filemanager.class.php","line":225}}
```
And this error is not handled on the frontend, the img.activity loader will stay there and spin forever.

---
If I add the is_readable check as I mentioned, and click on the "protected file" I see something like [this](https://cloud.githubusercontent.com/assets/7306657/5629329/74e0d9a2-95b2-11e4-9fb7-0d74dea8e306.png). Executing any action on it will fail silently (of course filemanager.php will return with a similar response as above, but user will only see that nothing happens) - which is not a problem in my opinion, but maybe a "Permission denied" alert would be good.

**Comment by simogeo** [comment]
Well spotted ... 
Actually, it would also be great to add a mention on protected folders (with a lock on icons for example). It could be a coming improvement.

To complete your proposed fixs I also added some tests on move(), edit(), delete(), ... methods. See commit  3d41ba79c16931aadaf397a809283398d6370025

**Comment by frzsombor** [comment]
Nice, thanks!

**Comment by simogeo** [comment]
I also completed all this with protected icons set and explicit messages : d68659177d19ff59de1ed161bb389bbb14d5f38f
