### ISSUE TITLE
Reste bloqué a l'icône de chargement

### ISSUE THREAD

**Issue by Yvon15** [simogeo/Filemanager#310]
Bonjour Simon,

J'ai installer filemanager et ca affiche corectement. Le seul problème est que filemanager apparait et l'icône de chargement tourne sans fin. Je peux télécharger des images et créer un nouveau dossier mais rien n'apparait dans l'écran principale (Juste l'icône de chargement) et il n'y a rien dans la section a gauche sous l'icône de maison.

J'ai peut-être ratté une indication d'installation. 

Merci de ton aide.

Yvon

**Comment by simogeo** [comment]
> J'ai peut-être ratté une indication d'installation. 

Il semble que oui. Reprends les étapes !

**Comment by Yvon15** [comment]
Merci pour la réponse rapide.

Ca fait 3 fois que je l'installe et ca fait toujours la même chose.

Est-ce que je doit définir le "fileroot" et le "relpath" dans le "filemanager.config.js" ?

Voici les étapes que je fait:
J'ai téléchargé la version 2.0.0.
Je l'ai placer dans le dossier de ma solution et j'ai supprimer le connector MVC car ma solution n'est pas en MVC et cela me donnais des erreurs de compilation.

(1) Check out a copy of the FileManager from the repository using Git :
git clone http://github.com/simogeo/Filemanager.git
or download the archive from Github : https://github.com/simogeo/Filemanager/archive/master.zip

You can place the FileManager anywhere within your web serving root directory.

(2) Make a copy of the default configuration file ("filemanager.config.js.default" located in the scripts directory), removing the '.default' from the end of the filename, and edit the options according to the following wiki page : https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file Having a look on configuration cases study may also be helpful to you : https://github.com/simogeo/Filemanager/wiki/Specify-user-folder%2C-configuration-cases.

Pour ce qui est des étapes ( 3a, 3b, 3c) Je n'integre pas filemanager avec FCKEditor, CKEditor et TinyMCE. Je veux utiliser seulement filemanager.

Je te donne une adresse web du site dans lequel je veux utiliser filemanager, Comme ca tu pourra voir comment il réagit.  dev1.3wdesign.ca. et click sur FILEMANAGER-2.0.0 en haut a droite.

Merci

Yvon

**Comment by Yvon15** [comment]
Je suis retourné a la version Filemanager-Master.

Autre problème, quand je veux télécharger un image, il y a une barre de progression verte et ensuite ca passe au rouge et un X rouge apparait dans le coin droit de l'image. Ensuite , j'ai le message de confirmation qui me dit que l'image a bien été ajouté avec succès mais rien n'apparait a l'écran juste l'icône de chargement qui tourne sans fin.

Merci de ton aide

Yvon

**Comment by simogeo** [comment]
> Est-ce que je doit définir le "fileroot" et le "relpath" dans le "filemanager.config.js" ?

relpath est optionnel.il est recommandé de définir fileroot.

dev1.3wdesign.ca n'est pas accessible.

**Comment by Yvon15** [comment]
Voici la bonne adresse du site dev1.wwwdesign.ca si tu veux y jeter un coup d'oeil. Merci

**Comment by simogeo** [comment]
Visiblement le connecteur PHP n'est aps présent !

http://dev1.wwwdesign.ca/Filemanager-master/connectors/php/filemanager.php?path=%2FFilemanager-master%2Fuserfiles%2F&mode=getfolder&showThumbs=true&time=511 renvoie une erreur 404

**Comment by Yvon15** [comment]
Salut Simon,

J'espère que tu va bien!

J'ai réglé le problème du PHP.

Maintenant si tu va voir le site dev1.wwwdesign.ca regarde ce qu'il me mets comme message.

J'ai créé un fichier fileRoot sur le serveur ftp. 

Je te fait voir ce que j'ai fait dans le filemanager.config.js et il me retourne " No way " et impossible de faire quoi que ce soit.

        "serverRoot": true,
        "fileRoot": "fileRoot/",
        "relPath": false,
        "logger": false,

J'ai aussi changé un truc dans le fichier filemanager.class.php
A l'endroit ou il y a " No way ", j'ai mit la variable " $currentpath " 
Comme ceci:
                public function getfolder() {
		             $array = array();
		             $filesDir = array();

		             $current_path = $this->getFullPath();

		if(!$this->is_valid_path($current_path)) {
			$this->error($current_path);
		}

et il me retourne " /fileRoot/ "

Je ne sais plus trop quoi faire.

Merci de ton aide.

Yvon

**Comment by simogeo** [comment]
Ou se trouve ton dossier fileRoot physiquement sur ta machine ? 

Tu peux essayer : 

```"serverRoot": false,
    "fileRoot": "/path/to/your/fileRoot/",
\\\

**Comment by Yvon15** [comment]
Il n'est pas sur ma machine, il est sur le serveur.

**Comment by Yvon15** [comment]
Est-ce que je doit mettre fullpath: C:/Users/Yvon/Desktop/fileRoot/

**Comment by simogeo** [comment]
... Il y a toutes les instructions dans le [readme](https://github.com/simogeo/Filemanager/blob/master/ReadMe.md) et sur le [wiki](https://github.com/simogeo/Filemanager/wiki), voir notamment [cette page](https://github.com/simogeo/Filemanager/wiki/Specify-user-folder%2C-configuration-cases).
