### ISSUE TITLE
Using vendor as a folder name causes trouble

### ISSUE THREAD

**Issue by frzsombor** [simogeo/Filemanager#311]
I found the source of issue #307 and I think it's a good lesson for me too. It's not related to Windows, not related to permissions, but related to git, composer and surely can hit others. 

I'm using Git for version controlling and Filemanager in a Laravel project. As any other composer project, Laravel lists `vendor` folder in it's [.gitignore](https://github.com/laravel/framework/blob/4.2/.gitignore).

This means that if anyone uses Filemanager in a composer installed project, he will not commit the files in `connectors\php\inc\vendor\` folder, so if anyone else will clone/pull the repo, he will miss the files of wideimage and get_thumbnail() will break [here](https://github.com/simogeo/Filemanager/blob/e157f436ccf2ed86f981622a451b85e32c49e37d/connectors/php/filemanager.class.php#L1312). The response will be a simple empty page with Internal Server Error response code.

**Comment by simogeo** [comment]
I decided to remove the vendor folder and locate wideimage in `inc/` folder : 
cb1fc3d8fcd52c10969c2d5f48587ab809d6407a
Still, the situation is a bit annoying ... because this is not specific to the Filemanager, actually.


Would you have time to create a wiki page to detail Filemanager integration with Laravel ? It would be worth value for the project itself.

**Comment by frzsombor** [comment]
Was all the 100644 → 100755 permission changes on propose or accidental? I don't know if they have any effect, just asking.

I see it's annoying, but maybe that's one more reason to use a package manager for most of the 3rd party scripts (as discussed in 293).

Of course, it's a good idea, and as soon as I will have some time to this, I will do it.
I'm using Filemanager not just with Laravel, but also with [Laravel Administrator](https://github.com/FrozenNode/Laravel-Administrator).
Unfortunately I didn't have time to work on, or even write a useful reply to 293 yet, but I will keep it in mind too.

**Comment by simogeo** [comment]
> Was all the 100644 → 100755 permission changes on propose or accidental? I don't know if they have any effect, just asking.

Accidental ... I don't think it would affect anything ...

I may also work on the desired  #293 feature. At least, to let you know which package can be automatically updated.
