### ISSUE TITLE
how to use korean-alphabet filename.

### ISSUE THREAD

**Issue by syncole** [simogeo/Filemanager#313]
English written on the button(UI) does not matter,

But If korean-alphabet filename exites in the folder, the file manager does not work.

how to edit this filemanager code for use korean-alphabet????

**Comment by simogeo** [comment]
You can try to allow non-latin characters by setting `chars_only_latin` to `false` in [config file](https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file).

But the problem may be more complex. See the following issue : https://github.com/simogeo/Filemanager/issues/244
