### ISSUE TITLE
Directories in left tree are not always displayed

### ISSUE THREAD

**Issue by swiki** [simogeo/Filemanager#314]
When page with filemanager is refreshed few times,  sometimes directories are not displayed.

Does anybody have similiar issue?

**Comment by simogeo** [comment]
Which browser ? which version ?

**Comment by swiki** [comment]
I tried in Chrome (Version 40.0.2214.111 (64-bit). Try to open filemanager and then refresh web page few times. I've just noticed that when I switch to list view, icons for folders are not displayed (attached screen). But before they was displayed. It is very strange, because when I open page with file manager for first time after some time, then everything is fine, but after loading tree is not displayed and icons in list view are not displayed too (Grid View is fine)

![screen shot 2015-02-10 at 12 16 31](https://cloud.githubusercontent.com/assets/3702721/6126235/bcad6b56-b11e-11e4-9a89-1601caccd068.png)

I would like to ask you one not related question. Can be somehow implemented feature to go "up" in directories? Like is ".." in standard folder browsers. Should I create new ticket for it?

Thanks for your reply, I appreciate your Filemanager, its very simple and exactly what I need, great work!

**Comment by simogeo** [comment]
HI, 
I guess you use the latest stable release. The trunk version should correct this : https://github.com/simogeo/Filemanager/archive/master.zip. Please, let me know.

> I would like to ask you one not related question. Can be somehow implemented feature to go "up" in directories? Like is ".." in standard folder browsers. Should I create new ticket for it?

Could be ... Please create a ticket, yes !

**Comment by swiki** [comment]
I tested last version and it wont fix my bug :( Strange is that it appears only in Chrome, Safari looks good.

**Comment by simogeo** [comment]
@swiki :  could you inspect element to see if you have that kind of code for one row : 

```html
<tr class=" cap_select cap_download cap_rename cap_move cap_delete cap_replace">
<td data-path="/Filemanager/userfiles/274_page.pdf" title="/Filemanager/userfiles/274_page.pdf" "="" style="background-image: url(http://localhost/Filemanager/scripts/jquery.filetree/images/pdf.png); ">274_page.pdf</td>
<td></td>
<td><abbr title="1433976">1.37mb</abbr></td>
<td>06 Feb 2014 15:12</td>
</tr>
```

Notice the element style applied and check the url : 

```html
 style="background-image: url(http://localhost/Filemanager/scripts/jquery.filetree/images/pdf.png);"
```

**Comment by simogeo** [comment]
By the way, can you precise if `list` view is set in config file or you're switching it by click only.
