### ISSUE TITLE
Navigation to Parent Directory ".."

### ISSUE THREAD

**Issue by swiki** [simogeo/Filemanager#315]
Hi @simogeo, 

I would very appreciated if there will be feature like  "go up" in directories. Like is ".." in standard folder browsers.

Something like... 
![screen shot 2015-02-10 at 13 02 41](https://cloud.githubusercontent.com/assets/3702721/6126878/27697056-b125-11e4-85d8-771296f8482a.png)

Thanks!

**Comment by simogeo** [comment]
Will try to....  I guess it could be done on client side only.

By the way, any contribution is welcome. So, if you feel to, just go on !

**Comment by simogeo** [comment]
done ! 3bfc5b71d993eaf49e0c57bc22f8b3d09e31fe66
