### ISSUE TITLE
Is there some form of callback?

### ISSUE THREAD

**Issue by sineverba** [simogeo/Filemanager#318]
I need (argh!) to realize a small gallery and my choice is your plugin.

So, you could imagine a basic form with a lightbox-driven button and a text-field to give title to photo.

Is there something callback on CLOSING the main window so I could refresh my page via Ajax and show immediately a thumb of the selected image in the form?

Thank you ;-)

**Comment by simogeo** [comment]
No callback in the FM itself but I guess it can be triggered from your own script, no ?
