### ISSUE TITLE
display problem?

### ISSUE THREAD

**Issue by lganchimeg** [simogeo/Filemanager#321]
![untitled](https://cloud.githubusercontent.com/assets/11252946/6569725/56ca5b6a-c72a-11e4-9aa9-a8ff4476033f.png)

**Comment by simogeo** [comment]
Do you have the same problem when using the filemanager from the online demo version : http://fm.linea21.com/ ?

**Comment by lganchimeg** [comment]
no.

**Comment by simogeo** [comment]
The online demo use the latest repository version. You should [do the same](https://github.com/simogeo/Filemanager/archive/master.zip) (and you probably are). 

From your screenshot, I can see you embed the FM into an HTML page. Some of your CSS probably overwrite FM sylesheet. You can explore that with firebug or Chrome Web development tool. Once spotted, change the name / id of the source's trouble or just select the element with precision.
