### ISSUE TITLE
support wildcards in editExt/filemanager.config.js

### ISSUE THREAD

**Issue by rhodebump** [simogeo/Filemanager#324]
I wish to just put in a wildcard so I can just edit any file.
"editExt": [ "*"]

I have had to add 10 extensions so far (css, jsp, html, java, js, groovy, properties, xml, md, etc)

**Comment by simogeo** [comment]
This is not possible. The filemenager itself need to know which files are editable (images and others binary files are not).

And I don't want to pre define an assumptive editable extensions list ... it would of course vary from a user to another and it may cause security issue.

The user will have to define it once when implementing the Filemanager. It doesn't appear to me like an insurmountable task.
