### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by hmalaud** [simogeo/Filemanager#325]
Hi there,

I installed the filemanager on my CMS and it gets stuck on the boot screen with the loader gif. I work on a  local environment set with a virtual host, and changed the fileRoot and relPath according to my root structure. However, looking into the XHR calls at start of the manager, I get the following error:

```
{"\/assets\/azeazea\/":
{"Path":"\/assets\/azeazea\/","Filename":"azeazea","File Type":"dir","Preview":"images\/fileicons\/_Open.png","Properties":
{"Date Created":"20 Mar 2015 12:21","Date Modified":"20 Mar 2015 12:21","filemtime":1426854112,"Height":null,"Width":null,"Size":null
},"Error":"","Code":0
},"\/assets\/img\/":
{"Path":"\/assets\/img\/","Filename":"img","File Type":"dir","Preview":"images\/fileicons\/_Open.png","Properties":
{"Date Created":"19 Mar 2015 17:58","Date Modified":"19 Mar 2015 17:58","filemtime":1426787914,"Height":null,"Width":null,"Size":null
},"Error":"","Code":0
}}
```

The script is reading my dummy folder 'azeazea' I created in my root folder 'assets' but nothing gets displayed.
Any idea?

Thanks for the help!

**Comment by simogeo** [comment]
No idea ... Have you tried any other options ? https://github.com/simogeo/Filemanager/wiki/Specify-user-folder%2C-configuration-cases

You may also try to debug it using [debug option](https://github.com/simogeo/Filemanager/wiki/Enable-log-debug-in-PHP-connector#the-json-config-file-way).

Please let me know

**Comment by hmalaud** [comment]
Thanks for your help.

Well, pointing on another folder does just the same: the call gets it well, but the window is stuck with the loader. The weird thing is that I can create a folder with the button.

The logfile says the following (I don't think it will help much):
```
[20/03/2015 02:05:49] Filemanager::enableLog - Log enabled (in /Users/hmalaud/Documents/Work/workspace/_akdv/statamic/assets/log.txt file)
[20/03/2015 02:05:49] Filemanager::__construct $this->doc_root value /Users/hmalaud/Documents/Work/workspace/_akdv/statamic
```

Is there by any chance an URL where I could test a working copy of the manager?

**Comment by simogeo** [comment]
I presume you have followed [these instructions](https://github.com/simogeo/Filemanager/wiki/Specify-user-folder%2C-configuration-cases#specify-a-folder-not-located-under-server-root-folder) and added the end slash to `fileRoot` value. Can you copy/paste it your config file ? 

> Is there by any chance an URL where I could test a working copy of the manager?

http://fm.linea21.com/

**Comment by hmalaud** [comment]
Sure, here it goes (and yes, I added a / to fileRoot):

```
{
        "_comment": "IMPORTANT : go to the wiki page to know about options configuration https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file",
    "options": {
        "culture": "en",
        "lang": "php",
        "defaultViewMode": "grid",
        "autoload": true,
        "showFullPath": true,
        "browseOnly": false,
        "showConfirmation": true,
        "showThumbs": true,
        "searchBox": true,
        "listFiles": true,
        "fileSorting": "default",
        "chars_only_latin": true,
        "dateFormat": "d M Y H:i",
        "serverRoot": true,
        "fileRoot": "assets/",
        "relPath": "/assets/",
        "logger": true,
        "logfile": "/Users/hmalaud/Documents/Work/workspace/_akdv/statamic/assets/log.txt",
        "plugins": []
    },
    "security": {
        "uploadPolicy": "DISALLOW_ALL",
        "uploadRestrictions": [
            "jpg",
            "jpeg",
            "gif",
            "png",
            "svg",
            "txt",
            "pdf",
            "odp",
            "ods",
            "odt",
            "rtf",
            "doc",
            "docx",
            "xls",
            "xlsx",
            "ppt",
            "pptx",
            "ogv",
            "mp4",
            "webm",
            "ogg",
            "mp3",
            "wav",
            "zip"
        ]
    },
    "upload": {
        "overwrite": false,
        "imagesOnly": false,
        "fileSizeLimit": 16
    },
    "exclude": {
        "unallowed_files": [
            ".htaccess",
            "index.html"
        ],
        "unallowed_dirs": [
            "_thumbs",
            ".CDN_ACCESS_LOGS",
            "cloudservers"
        ],
        "unallowed_files_REGEXP": "/^\\./uis",
        "unallowed_dirs_REGEXP": "/^\\./uis"
    },
    "images": {
        "imagesExt": [
            "jpg",
            "jpeg",
            "gif",
            "png",
            "svg"
        ]
    },
    "videos": {
        "showVideoPlayer": true,
        "videosExt": [
            "ogv",
            "mp4",
            "webm"
        ],
        "videosPlayerWidth": 400,
        "videosPlayerHeight": 222
    },
    "audios": {
        "showAudioPlayer": true,
        "audiosExt": [
            "ogg",
            "mp3",
            "wav"
        ]
    },
    "extras": {
        "extra_js": [],
        "extra_js_async": true
    },
    "icons": {
        "path": "images/fileicons/",
        "directory": "_Open.png",
        "default": "default.png"
    }
}

```

**Comment by simogeo** [comment]
And what's happening if you set it as follow ?

```
"serverRoot": false,
"fileRoot": "/Users/hmalaud/Documents/Work/workspace/_akdv/statamic/assets/",
```

**Comment by hmalaud** [comment]
No changes :(
I will try on a real server just to check OSX is not messing something up.

**Comment by simogeo** [comment]
Try it also by setting relPath to `false`.

**Comment by hmalaud** [comment]
We got progress! That worked on my distant server, but isn't working on my localhost. It's a bit annoying but I can't ask you to debug each one's configuration ^^
If you think of some configuration that might be missing, please let me know (Yosemite, php 5.6.6).

Anyways, thanks for your help!

**Comment by simogeo** [comment]
Please let us know if you find a fix concerning your localhost config. It could also be useful for others.
