### ISSUE TITLE
Having a connector outside the file tree

### ISSUE THREAD

**Issue by rcs1000** [simogeo/Filemanager#326]
Hi,

I would like to have the connector sit on a custom (on-site) URL - specifically "/connector" (I'm parsing it with flask on Python). With version 0.8 I was able to change one line in filemanager.js to:

"var fileConnector = '/connector';"

If I try changing the line in the latest version it seems to have no effect - filemanager still attempts to access /connectors/php/filemanager.php

Do you know what I need to do to change the URL for the connector?

Many thanks,

Robert

**Comment by simogeo** [comment]
By default, the FM use the minified JS version, change it into your HTML file
and try to make your change into `filemanager.js`.
Not sure it will work, because the connector itself is used as reference to know files paths.
