### ISSUE TITLE
Files and directories are not displayed

### ISSUE THREAD

**Issue by bupiotr** [simogeo/Filemanager#327]
Hello.
I have a problem with FileManager. If I run it on Xampp (Apache 2,4 PHP5,4 Win8,1) everything is OK.
But if I run it under ZendServer (Apache 2,2,25, PHP 5.5.13 Win8,1) left panel with filetree and rightpanel is empty - loading icon is only visible. Uploading files and folder creating works fine. 
When I debugged application under Zend errors appeared in jquery1.8.3.js and filemanager.min.js.
Can anybody help?

**Comment by simogeo** [comment]
Any online URL to provide ?
Could you  copy / paste the errors messages ?

**Comment by bupiotr** [comment]
Debugging application in Mozilla I found warnings in response from GET request 

GET http://localhost/Filemanager/connectors/php/filem...files%2F&mode=getfolder&showThumbs=true&time=202

<br />
<b>Warning</b>:  fopen(/tmp/filemanager.log): failed to open stream: No such file or directory in <b>
C:\Program Files (x86)\Zend\Apache2\htdocs\Filemanager\connectors\php\filemanager.class.php</b> on line <b>1459</b><br />
<br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, boolean given in <b>
C:\Program Files (x86)\Zend\Apache2\htdocs\Filemanager\connectors\php\filemanager.class.php</b> on line <b>1461</b><br />
<br />
<b>Warning</b>:  fclose() expects parameter 1 to be resource, boolean given in <b>
C:\Program Files (x86)\Zend\Apache2\htdocs\Filemanager\connectors\php\filemanager.class.php</b> on line <b>1462</b><br />
<br />
......
These warnings appeared several times.
After warnings further part of request is shown (files and directories uploaded early because uploading works OK)
I noticed that every time the filemanager.php is invoked the same warnings appear.
-----------------------------------------
But when I am debugging application in Zend Studio the situation is quite different.
Only loading icon is shown, in the Studio Console 4 errors is displayed:
console is not defined in http"//localhost/Filemanager/scripts/filemanager.js  1933
_defineProperty is not a function in http"//localhost/Filemanager/scripts/jquery-1.8.3.min.js  1631
console is not defined in http"//localhost/Filemanager/scripts/filemanager.min.js  71
_defineProperty is not a function in http"//localhost/Filemanager/scripts/jquery-1.8.3.min.js  1631

**Comment by simogeo** [comment]
Just set `logger` to false in your config file or specify a valid path. see wiki page : https://github.com/simogeo/Filemanager/wiki/Enable-log-debug-in-PHP-connector#the-json-config-file-way

**Comment by bupiotr** [comment]
Thanks a lot. It works. But I wonder why it worked under XAMPP with logger=true. Maybe permission to log file on C: or E: caused the problem? I have to check it out.
As so far I want to integrate this gorgeous application with zend but up to now have no idea how to do in the best way. I have to think it over. But if You give me some advise  I would be pleased.

**Comment by simogeo** [comment]
Just because PHP error settings are, by default, different from XAMPP and Zend Server, I guess.

See : 
* http://php.net/manual/fr/function.error-reporting.php
* http://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting

> As so far I want to integrate this gorgeous application with zend but up to now have no idea how to do in the best way. I have to think it over. But if You give me some advise I would be pleased.

No idea, but should not be a big deal.
