### ISSUE TITLE
Permissions on original image.

### ISSUE THREAD

**Issue by roddyguy22** [simogeo/Filemanager#330]
I've been forced to work on a Windows server that has PHP installed. Everything is working fine, and after I upload an image, I can access all resized images, but not the original image. I can see it is on the server, but for some reason the permissions for original image are different and give me a broken image link until I manually change the pernmissions on that image. I assume that permissions are somehow being set when resizing and creating new images, but not on original image. Any ideas?

Tried using chmode script after upload, but no luck.

**Comment by roddyguy22** [comment]
I narrowed it down that somehow either the "convert_image" or the "make_thumb" function was somehow making the files accessible on the server. 

My workaround was to comment out line 644 in FileManager.php:
//move_uploaded_file($tempFile, $urlandname);

and put this there instead:
$image = $this->convert_image($tempFile, $mime);
$this->make_thumb($image, $urlandname, $attr[0], $attr[1], $mime);

This made the original image accessible with correct permissions. (or maybe non-corrupted)

FYI - I've never had this problem on a Linux server, and don't know enough about windows servers to know what the real problem is.

**Comment by simogeo** [comment]
@roddyguy22 : could you try that ? http://php.net/manual/fr/function.move-uploaded-file.php#86332

**Comment by roddyguy22** [comment]
@simogeo : might work, but I use same move_upload script elsewhere on the site (not using FileManager) and I have no problems. Not sure what the difference would be. Don't have time to troubleshoot anymore, or wrestle with tech support to change php.ini settings (which I have no control of). But I appreciate the advice and really love your scripts. Best for me to always avoid windows servers. : )

**Comment by simogeo** [comment]
> Best for me to always avoid windows servers. 

That's it ! ;-)
