### ISSUE TITLE
PHP: Code that never gets executed

### ISSUE THREAD

**Issue by robsch** [simogeo/Filemanager#331]
Method is_allowed_file_type() In class Filemanager contains code that won't be reached. I cannot assess if it is required or not. But that code coud be removed (and the if statement could be simplified, i.e. replaced by a return statement).

**Comment by simogeo** [comment]
Could you provide more explanation ?

**Comment by robsch** [comment]
If and else branch (line 1198) return a boolean value. So the method ends here. And you could replace if/else with 

    return (isset($path_parts['extension']) && !empty($path_parts['extension'])) 
       || $this->config['security']['allowNoExtension'] == true;

**Comment by simogeo** [comment]
Well spotted, indeed ... I want to execute the code beyond actually ...

So, the test should be : 

```php
	// if there is no extension 
	if(!isset($path_parts['extension'])) {
		// we check if no extension file are allowed
		if($this->config['security']['allowNoExtension'] == true) return true;
		return false;
	}
```

**Comment by simogeo** [comment]
It is supposed to be fixed : fc59ebe6404ae67ab06b2989baaaf19c5ea70eea

**Comment by robsch** [comment]
Okay. And I guess my suggested empty() check is not needed...

**Comment by simogeo** [comment]
`if(!isset($path_parts['extension']))` should be enough.
