### ISSUE TITLE
Problem with paths that contain symlinks on Linux

### ISSUE THREAD

**Issue by robsch** [simogeo/Filemanager#332]
#306 has corrupted the behaviour on linux systems, I think. At least with 2.1 I've got a problem now that I didn't have with 2.0.

 realpath() resolves symbolic links and then the comparison 'startWith' doesn't work anymore. I think realpath is not the best way to solve #306. Have a look on http://stackoverflow.com/questions/5642785/php-a-good-way-to-universalize-paths-across-oss-slash-directions .

My situation: 'fileRoot' links to a (normal) relative path. In this directory I have some symbolic links to files and folders that the user should access. I cannot put those folders into the 'fileRoot' directory.

Sorry to bother you again ;-)

**Comment by simogeo** [comment]
> Sorry to bother you again ;-)

Don't worry, I like the efficient way you spot bugs ! I just committed a new version implementing the pointed method. Could you please try and give me feedback ?

**Comment by robsch** [comment]
Okay. Seems to work. Though I have tested only on Mac. I'm not sure what happens on Windows, especially with symlinks.

**Comment by simogeo** [comment]
@pers0n : would you mind to check if the latest trunk version works also for you under Windows ? - I refer to issue #306

**Comment by simogeo** [comment]
@robsch : great. Thanks
