### ISSUE TITLE
Cannot move files and folders via drag&drop

### ISSUE THREAD

**Issue by robsch** [simogeo/Filemanager#335]
Where and how can I (user) move files. Is it possible in the tree AND in the right pane? Can I move them from left to right and vice versa? Or just within the panes?

In Firefox 31 and Chrome 41 I cannot move anything. It seems to me I can start dragging from the tree, but dropping anywhere does not have any effect.

**Comment by simogeo** [comment]
Hi @robsch : the FM does not pretend to do so ! ;-) 

And the feature has already been asked here #84. Would you like to work on that ?

**Comment by robsch** [comment]
Hm... I'd like so but I think that takes too long. Drag&drop would be really nice, though. For a modern file manager I would even say it is a must-have...

**Comment by ChristianSchmidt1981** [comment]
I agree
