### ISSUE TITLE
reduntant usage of the modificatoion date in 'getinfo' and 'getfolder'

### ISSUE THREAD

**Issue by th-schwarz** [simogeo/Filemanager#337]
I found an extra, undocumented property 'filemtime'. It's seems to be a timestamp that is equals to 'Date Modified', right?

I think you should decide for timestamp or the string representation of a date.
I'm Java-Script and I don't know if you could manage the string representation of a date with a kind of date-formator. So you could define a date format string for each supported country.

It's just a suggestion! But it would be easier and more clearly to handle from the connector-developers. ;-)

**Comment by simogeo** [comment]
'Date Modified' is a readable date format whereas 'filemtime' is used to sort files with the `fileSorting` *MODIFIED_DESC / MODIFIED_ASC* options.

Please see : https://github.com/simogeo/Filemanager/wiki/How-to-change-files-and-folders-order-in-list%3F

Indeed `filemtime` is not used by the javascript part but is needed by connector.

**Comment by th-schwarz** [comment]
@simogeo If `filemtime` isn't used by the javascript part, I haven't set it in the java-connector, right?

Just for my interest: why do you need `filemtime` in the php-connector?

**Comment by simogeo** [comment]
> 'filemtime' is used to sort files with the fileSorting MODIFIED_DESC / MODIFIED_ASC options.

Here : https://github.com/simogeo/Filemanager/blob/master/connectors/php/filemanager.class.php#L1120

**Comment by th-schwarz** [comment]
thank you!
