### ISSUE TITLE
Issue on CKEditor integration when allow users to have their own folder

### ISSUE THREAD

**Issue by bestmomo** [simogeo/Filemanager#339]
Hello,

CKEditor integration works fine in classical way. But if I follow [this page](https://github.com/simogeo/Filemanager/wiki/How-to-allow-users-to-have-their-own-folder-%3F) instructions to allow users to have their own folder I get images with wrong path.

To get it working I set this in config : 
```
"serverRoot": false,
"fileRoot": "/",
```
And I use setFileRoot to set the good path. And filemanager is working fine in this path.

But when I use it in CKEditor I get :
```
src="http://localhostE:\wamp\www\basepublic/filemanager/userfiles/greatredactor/image1.png"
```
Instead of : 

```
src="http://localhost/base/public/filemanager/userfiles/greatredactor/image1.png"
```
What am I doing wrong ?

Thanks

**Comment by simogeo** [comment]
You can use `relPath` to navigate to the right folder 

```javascript
"relPath": "../../",
```

**Comment by simogeo** [comment]
But I have to admit I did not work much on this. Hope it will works. If not, let me know. I'll try to fix this soon.

**Comment by bestmomo** [comment]
Thanks but I cant get it working with that, it is not a relative url issue but looks like a concat somewhere...

**Comment by simogeo** [comment]
Should be ok now !  Please [download latest version](https://github.com/simogeo/Filemanager/archive/master.zip).

And set `relPath` as follow : 

```javascript
"relPath": "http://localhost/base/public/filemanager/userfiles/"

"relPath": "http://localhost/base/public/filemanager/"

"relPath": "http://localhost/base/public/"
```

They should all work correctly !

**Comment by bestmomo** [comment]
Thanks but you dont have changed **filemanager.min.js**  ;)

**Comment by simogeo** [comment]
I did. Clear your cache and let me know !

**Comment by bestmomo** [comment]
Perfect I use relative url : 
```
"baseUrl": "/filemanager/",
```
And all works fine !

**Comment by simogeo** [comment]
Wonderful !

By the way and for your information (but you may already know)I reference your tutorial on the wiki : https://github.com/simogeo/Filemanager/wiki/Integrate-the-Filemanager-with-Laravel

**Comment by bestmomo** [comment]
Yes I saw this reference, I'll update it with new features.

**Comment by sd-design** [comment]
I have a problem with "copy URL in clipboard". When I copy missing some letter in the beginning of filename. Fore example I copy http://filemanager/uploads/file1.jpg - and I have result http://filemanager/uploads/1.jpg
Or I copy http://filemanager/uploads/folder/file2.jpg - I have result http://filemanager/uploads/r/file2.jpg
In filemanager.config.js value "baseUrl": "http://filemanager/uploads/"

**Comment by simogeo** [comment]
what is the path set with  `$fm->setFileRoot();` ?

**Comment by sd-design** [comment]
I found the solution: in filemanager.config.js I change value "baseUrl": false - it's work!!!!

**Comment by ptitbibice** [comment]
hi, 
i would like back to my tree folder with : 
"serverRoot": false,
"fileRoot": "/",
"baseUrl": "../../",

But it doesn't work ?
Can you help me?

**Comment by simogeo** [comment]
Pleas be more accurate if you want any help.

What do you want to do ? What is your folders structure ? What is your webserver root ? Where is FM installed ?

**Comment by ptitbibice** [comment]
i would like start my file tree 3 folder before my folder filemanager.
exemple :
- /
  -folder1
    -folder11
      -filemanger
  -folder2
like this exemple, i would like start file root at /

Thanks for your help

**Comment by ptitbibice** [comment]
ok, i have found, sorry for the disruption

**Comment by simogeo** [comment]
Assuming you have this kind of folders structure : 

```html
- /home/user/
    |
    |_____ desiredRootFolder/
                       |
                       |________ folder1/
                       |                      |
                       |                      |_____ Filmanager/
                       |
                       |________ folder2/
```


Something similar to this should work

```json
"serverRoot": false,
"fileRoot": "/home/user/desiredRootFolder/",
```


`baseUrl` is only used for selecting from an editor : 

```json
"baseUrl": "http://www.mydomain.tld/my/path/",
```

**Comment by ptitbibice** [comment]
Thanks for your replay !

**Comment by alanhartless** [comment]
I need to be able to set baseUrl dynamically via PHP.  Is that possible?

**Comment by simogeo** [comment]
Absolutely not ...
