### ISSUE TITLE
Got lost

### ISSUE THREAD

**Issue by harrypotter30022003** [simogeo/Filemanager#342]
Hello,

Thanks for the fantastic filemanager module. I have a few questions:
1. Where did you save the file structure? i dont see any DB or Json contain this info

2. How can I add new column to the list view? I want to add file owner column which available in my DB

3. In the file manager, I need to filter certain file according to special requirement. Example: only show files that have show flag which include in my DB. Where can I add custom filter/DB query code?

Thanks

**Comment by simogeo** [comment]
> 1. Where did you save the file structure? i dont see any DB or Json contain this info

The FM directly read the files structures. All files are stored into `/userfiles/` folder by default

> How can I add new column to the list view? I want to add file owner column which available in my DB

> In the file manager, I need to filter certain file according to special requirement. Example: only show files that have show flag which include in my DB. Where can I add custom filter/DB query code?

Ther is no DB connector... You will have to tweak the app to get this work - it will break update compatibility
