### ISSUE TITLE
issues while using on WD My cloud

### ISSUE THREAD

**Issue by joutain** [simogeo/Filemanager#343]
Hi this web based file manager is great, when I try to use it on my WD My cloud, it gives me the error message like the following. Can you figure it out what could be the possible reason and how to solve it? thanks!
![image](https://cloud.githubusercontent.com/assets/9023645/7335586/7541078c-eb98-11e4-8417-f1aa7724f107.png)

**Comment by th-schwarz** [comment]
I guess there  is a syntax error in your filemanager.config.js.
