### ISSUE TITLE
Error uploading and loading file list when filename contains chinese char

### ISSUE THREAD

**Issue by kyle250** [simogeo/Filemanager#349]
when uploading chinese file name the folder show the error filename
![image](https://cloud.githubusercontent.com/assets/3203693/7608719/a09cac60-f99e-11e4-9274-c8b364e5007a.png)

and if the folder contains chinese file name the page could not be able to load file list like this:
![image](https://cloud.githubusercontent.com/assets/3203693/7608737/cfec1c3a-f99e-11e4-9323-df47648ea774.png)

hope some one can fix this.

**Comment by simogeo** [comment]
This is not so easy to fix since it relies on filesystem encoding. Please read #244.
