### ISSUE TITLE
Online it doesn't work

### ISSUE THREAD

**Issue by Woutje99** [simogeo/Filemanager#350]
Hi,

Local works the filemanager fine, I upload it to my server and now i get everytime the error: Error parsing the settings file! Please check your JSON syntax.

But i have copied the default settings file, so this is strange?

Can you help me?

**Comment by simogeo** [comment]
give me the url if you want any help

**Comment by Woutje99** [comment]
Hi,

This is the url: http://dev.vikingrace.nl/admin
You can login with: whaakmeester@gmail.com, 123456

Then you must go this URL: http://dev.vikingrace.nl/admin/news/edit
When you cick on 'Bladeren' you see the screen with the error

**Comment by simogeo** [comment]
Well, firebug is very verbose, `filemanager.config.js` does not exists ... http://dev.vikingrace.nl/filemanager/scripts/filemanager.config.js

check whether the file exists or not ... if it does, it could be a rewrite / or laravel routing issue

**Comment by Woutje99** [comment]
It was my fault, i find the solution.

Thnxx!

**Comment by sd-design** [comment]
Link http://dev.vikingrace.nl/filemanager/scripts/filemanager.config.js is not working
