### ISSUE TITLE
How to change location of index.html?

### ISSUE THREAD

**Issue by sd-design** [simogeo/Filemanager#351]
I want replace root's index.html to myFoder. Ho Can I do it?
I work in Codeigniter and I want to use your Filemanager in this framework.

**Comment by simogeo** [comment]
You can locate the Filemanager anywhere.
(If you want any help, please be accurate)

**Comment by sd-design** [comment]
For example: Filemanager in folder http://localhost/filemanager/
I need to call Filemanager from http://localhost/user/manager/
I switch on all .js files - in console of browser I have error in filemenager.js "logger is undefinded"

**Comment by simogeo** [comment]
Define logger in your config file. See https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.config.js.default#L23

**Comment by sd-design** [comment]
I use "logger : false"

**Comment by sd-design** [comment]
When I use value o "logger" in native folder - all work. When I use in other folder filemanager is not work

**Comment by simogeo** [comment]
!!!! ??? Could you paste your config file ?

**Comment by simogeo** [comment]
you can also try last version (see commit 933614768ed57ca0ae5ac874d3f033bd092a11f4)

**Comment by simogeo** [comment]
by the way, correct syntax is : 

>  "logger" : false,

**Comment by sd-design** [comment]
I update file "connectors/php/filemanager.class.php"
Error: Uncaught TypeError: Cannot read property 'logger' of undefined in filemanager.min.js line:9

**Comment by sd-design** [comment]
My Config file:
{
		"_comment": "IMPORTANT : go to the wiki page to know about options configuration https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file",
    "options": {
        "culture": "en",
        "lang": "php",
        "theme": "flat-dark",
        "defaultViewMode": "grid",
        "autoload": true,
        "showFullPath": false,
        "showTitleAttr": false,
        "browseOnly": false,
        "showConfirmation": true,
        "showThumbs": true,
        "generateThumbnails": true,
        "searchBox": true,
        "listFiles": true,
        "fileSorting": "default",
        "chars_only_latin": true,
        "dateFormat": "d M Y H:i",
        "serverRoot": true,
        "fileRoot": "/",
        "baseUrl": false,
        "logger": false,
        "capabilities": ["select", "download", "rename", "delete", "replace"],
        "plugins": []
    },
    "security": {
        "allowFolderDownload": false,
        "allowChangeExtensions": false,
        "allowNoExtension": false,
        "uploadPolicy": "DISALLOW_ALL",
        "uploadRestrictions": [
            "jpg",
            "jpe",
            "jpeg",
            "gif",
            "png",
            "svg",
            "txt",
            "pdf",
            "odp",
            "ods",
            "odt",
            "rtf",
            "doc",
            "docx",
            "xls",
            "xlsx",
            "ppt",
            "pptx",
            "csv",
            "ogv",
            "mp4",
            "webm",
            "m4v",
            "ogg",
            "mp3",
            "wav",
            "zip",
            "rar"
        ]
    },
    "upload": {
        "multiple": true,
        "number": 5,
        "overwrite": false,
        "imagesOnly": false,
        "fileSizeLimit": 16
    },
    "exclude": {
        "unallowed_files": [
            ".htaccess",
            "web.config"
        ],
        "unallowed_dirs": [
            "_thumbs",
            ".CDN_ACCESS_LOGS",
            "cloudservers"
        ],
        "unallowed_files_REGEXP": "/^\\./",
        "unallowed_dirs_REGEXP": "/^\\./"
    },
    "images": {
        "imagesExt": [
            "jpg",
            "jpe",
            "jpeg",
            "gif",
            "png",
            "svg"
        ],
        "resize": {
        	"enabled":true,
        	"maxWidth": 1280,
            "maxHeight": 1024
        }
    },
    "videos": {
        "showVideoPlayer": true,
        "videosExt": [
            "ogv",
            "mp4",
            "webm",
            "m4v"
        ],
        "videosPlayerWidth": 400,
        "videosPlayerHeight": 222
    },
    "audios": {
        "showAudioPlayer": true,
        "audiosExt": [
            "ogg",
            "mp3",
            "wav"
        ]
    },
    "edit": {
        "enabled": true,
        "lineNumbers": true,
        "lineWrapping": true,
        "codeHighlight": false,
        "theme": "elegant",
        "editExt": [
            "txt",
            "csv"
        ]
    },
    "customScrollbar": {
    	"enabled": true,
    	"theme": "inset-2-dark",
    	"button": true
    },
    "extras": {
        "extra_js": [],
        "extra_js_async": true
    },
    "icons": {
        "path": "images/fileicons/",
        "directory": "_Open.png",
        "default": "default.png"
    },
    "url": "https://github.com/simogeo/Filemanager",
    "version": "2.0.0-dev"
}

**Comment by simogeo** [comment]
in index.html file, can you change : 

> <script type="text/javascript" src="scripts/filemanager.min.js"></script>

by 

> <script type="text/javascript" src="scripts/filemanager.js"></script>

and copy-paste error message again (it will display the correct line)

**Comment by sd-design** [comment]
Error: Uncaught TypeError: Cannot read property 'logger' of undefined in filemanager.min.js line:9

**Comment by simogeo** [comment]
** filemanager.min.js** it should be **filemanager.js**

Cache issue ?

**Comment by sd-design** [comment]
Sorry! I did'nt see

**Comment by sd-design** [comment]
BUt still it does'nt work

**Comment by sd-design** [comment]
I have changed  filemanager.min.js on filefilemanager.js

**Comment by sd-design** [comment]
In Firefox it's error: TypeError: config.options is undefined
In chrome it's error: Uncaught TypeError: Cannot read property 'logger' of undefined (in filemanage.js on 58 line)

**Comment by simogeo** [comment]
It seems the config file is not read as expected (you can see it in firebug (network tab). Do you have any url to provide ?

**Comment by sd-design** [comment]
Url are same:
http://localhost/filemanager/ - work 
http://localhost/file/ - does'nt work
May be I forgot to explain all files of filemanager located in http://localhost/filemanager/
My purpose is change location of index.html file

**Comment by simogeo** [comment]
If you want to change index.html location you need to change the full FM to the desired folder.

**Comment by sd-design** [comment]
I use RewriteEngine URL  - my location generated by framework

**Comment by simogeo** [comment]
That means, you should write an exception rule.

See : 
http://stackoverflow.com/questions/1848500/htaccess-mod-rewrite-how-to-exclude-directory-from-rewrite-rule
http://stackoverflow.com/questions/163302/how-do-i-ignore-a-directory-in-mod-rewrite

Please let me know. I would appreciate to get some feedback regarding that for other code-igniter users.

I created a wiki page for [Laravel](https://github.com/simogeo/Filemanager/wiki/Integrate-the-Filemanager-with-Laravel). I could do the same for CI.

**Comment by simogeo** [comment]
So ?

**Comment by sd-design** [comment]
Still I have same problem. I can't understand application logic. I know - it's my problem, but....

**Comment by simogeo** [comment]
see #494
