### ISSUE TITLE
CKeditor: Selected filename is nog complete given to the editor window

### ISSUE THREAD

**Issue by jicho** [simogeo/Filemanager#354]
Hi,

I've downloaded the latest version (2.1.0) of this nice Filemanager, but I have a little issue... I'm using the latest CKeditor as editor. I can upload and view files when I access the Filemanager using the "Browse server" option from CKEditor, so everything inside the Filemanager window works as expected :)

When I select, for example, an image (pdf.gif) and press the select button in the Filemanager I get the url to my image like this "undefinedpdf.gif" in CKEditor. I would expect something like this "/files/pdf.gif" in CKEditor.

Any idea what is going wrong? Or what I'm doing wrong...?

My settings:

    "serverRoot": false,
    "fileRoot": "C:/Websites/test/app/webroot/files/",
    "baseUrl": "/files/",

I'm using the filemanager in combination with CakePHP.

CKEditor config file contains only this:

    config.filebrowserBrowseUrl = '/filemanager/index.html';

Hmmm... When I use copy the url function in FM, I also get this image url:
undefinedpdf.gif

Thanks for the input!

**Comment by simogeo** [comment]
Ans what's happening if "baseUrl" is set to false ? I think you don't need to.

**Comment by simogeo** [comment]
but you're right, the application has a strange behavior ...

**Comment by jicho** [comment]
@simogeo I've tested it with the "baseUrl" set to false, result is the same :( I did not test is with other browser, so maybe... Who knows it is a Chrome (latest version) issue? I will do some more investigation when I have the change and update this issue when I find something.

At the end I need the "baseUrl" since the filemanager is used on a different location than the site, but that is for now a minor detail ;)

**Comment by simogeo** [comment]
Please see last commit, should be ok : a949bd85806e554db7ca77bc33a2180680fae1c7

thanks for reporting

**Comment by jicho** [comment]
Finally... Some time to test the update, the fix works, tnx!
