### ISSUE TITLE
Simogeo filemanager not returning image url to ckeditor

### ISSUE THREAD

**Issue by MebisJ** [simogeo/Filemanager#355]
I'm using ckeditor (version 4.4.7) and the Simogeo Filemanager (latest release) in the cakephp (2.6.3) framework.

CKeditor is showing the button for going to the filemanager. The filemanager is working fine but when I select a image nothing is happening. Normally the filemanager will close and the url to the image appears in the ckeditor image properties pop-up.

html:

    <script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
    <form>
     <textarea name="editor1" id="editor1" rows="10" cols="80">
         This is my textarea to be replaced with CKEditor.
    </textarea>
    <script>
     CKEDITOR.replace( 'editor1', {
        filebrowserBrowseUrl: 'http://mywebsite/js/Filemanager-master', 
    });
    </script>
    </form>

I noticed two other questions on this forum with the same problem but there was no answer.
I'm receiving this error in the IE console: 
SCRIPT70: access denied. File: Filemanager-master, line: 23, column: 200 –

**Comment by simogeo** [comment]
Just testes (again) and I have no problem.

Should be user specific ? Which browser are you using, which platform ? 

Could you try on a remote machine / other machine ?

> http://stackoverflow.com/questions/30370712/simogeo-filemanager-not-returning-image-url-to-ckeditor

**Comment by MebisJ** [comment]
Thank you for your time.
It's not user specific and happening in Chrome as IE. Maybe an interference problem with other javascripts. Because nobody else has this problem I try it again.

**Comment by MebisJ** [comment]
Ok, I installed xampp and tried it out local and that is working fine.
So now I can work further to the solution.

**Comment by simogeo** [comment]
According to me the problem came from a specific Apache settings (*httpd.con*f, or *.htaccess* file - maybe some rewrite rules).
