### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by shranet** [simogeo/Filemanager#356]
Hi. Sorry my english bad.
If you are using connector PHP, then you can get access to the parent folder as follows (on v0.8):

> *********************************

On current version:
If file manager files are in “fm” folder, then:

> *********************************

**Comment by simogeo** [comment]
I edited your message to *protect* FM users.
I'll fix it very soon. If any recommendation to do it the clean way, please send me an email. See my email in PHP connector code source.

Thanks for spotting this !

**Comment by simogeo** [comment]
Please see a204411497c3a2cdeee4fc5c02805fc1780faf58,  and test it ! Thanks to shranet & Joakim

**Comment by hammond13** [comment]
Just a note that I handled this in the mvc connection by passing all operations through an IsInRootPath function.
https://github.com/simogeo/Filemanager/blob/master/connectors/mvc/FilemanagerController.cs#L130

**Comment by simogeo** [comment]
@hammond13 : thanks for precision.
