### ISSUE TITLE
Different file extensions

### ISSUE THREAD

**Issue by supertazzik** [simogeo/Filemanager#357]
Hi,

First of all, thank you for this valuable project.

I am trying to use FileManager in a kind of Admin Panel application of a web site developed by ASP.NET. As I mentioned in the title, I must configure the file extensions to upload by a few situations. I have created ASP.NET Generic Handlers (.ashx files) to rewrite the config file, and 'allowed extensions' are changing for each situations successfully.

I have an issue in that point: When file type is not image (for example, only .swf files --- it directs to .../FlashFiles/ as fileroot, so "uploadRestrictions" is [ "swf" ] --- in QueryString type="files"), files can be added to uploader control but the 'upload button' doesn't work (nothing is happening when clicked). I've observed the ASP.NET connector file; the value of "mode" (in QueryString) is getting empty.

And another thing I need a solution on it, how to disallow to create a new folder? I have tried to delete the [button id="newFolder" .../] in the index.html (in my application it is FileManager.aspx) of an old version of FileManager and it had worked. But at the last version, if I delete the 'new folder' button, the 'upload button', which opens the uploader is also deleted.

(Sorry, if I have faults in language.)

**Comment by supertazzik** [comment]
Edit: In the issue mentioned above; files don't be uploaded altough it alerts 'Files are uploaded successfully' when clicked the 'upload button' after adding file(s) to the 'file upload' control.

**Comment by simogeo** [comment]
> And another thing I need a solution on it, how to disallow to create a new folder? I have tried to delete the [button id="newFolder" .../] in the index.html (in my application it is FileManager.aspx) of an old version of FileManager and it had worked. But at the last version, if I delete the 'new folder' button, the 'upload button', which opens the uploader is also deleted.

Regarding your second issue, just add extra jQuery call in index.html
```javascript

(function($) {
     $( "button#newfolder" ).remove();
});
```

I'll get back to you on the first one when I have more time

**Comment by simogeo** [comment]
By the way, if you did enhancement on ashx connector, please, consider [sharing with others](https://help.github.com/articles/using-pull-requests/) !

**Comment by supertazzik** [comment]
Thank you again, for your answer. I could remove the new folder button with this solution, and I am following up your answer for the other one.

P.S.
I will share (or just send to you) my "FileManager with ASP.NET" project after completing it.

**Comment by supertazzik** [comment]
I have been failing the spot like an amateur! Sometimes this happens, normally. :)
I set the maxRequestLength to 16MB in web.config, and problem solved.
