### ISSUE TITLE
miss scripts/jquery.tablesorter/jquery.tablesorter.min.js

### ISSUE THREAD

**Issue by ptitbibice** [simogeo/Filemanager#359]
hi, 
thanks for your support.

In your project, jquery.tablesorter.min.js is absent.
And they is one error with the list mode : 
TypeError: $(...).find(...).tablesorter is not a function

And when we add this : jquery.tablesorter.min.js => it's work

Thanks for you project, it's good !

**Comment by simogeo** [comment]
Are you sure ?? 
default `index.html` page points to `scripts/jquery.tablesorter-2.7.2.min.js` and as you can see, the file is there : https://github.com/simogeo/Filemanager/blob/master/scripts/jquery.tablesorter-2.7.2.min.js

Maybe your mistake ...

**Comment by ptitbibice** [comment]
Decidedly, it's my mistake ^^

Your file tree take a good work

Thank you
