### ISSUE TITLE
path.replace 

### ISSUE THREAD

**Issue by ptitbibice** [simogeo/Filemanager#360]
i think they is a bug with method replace on ie 11.

path = path.replace(fileRoot, "/"); on filemanager.min.js

it's hapend when you click on back floder button

Regards

**Comment by simogeo** [comment]
Please use `filemanager.js` version to debug.

But actually, I can't see the bug ! see yourself online : http://fm.linea21.com/
Which browser ? which version ?

**Comment by ptitbibice** [comment]
hi,
i use ie 11,

Just, 
=> go to http://fm.linea21.com/ with ie 11
=> press  F12
=> open my_folder on tree file and press button level-up (back folder)
=> And an error is detected.

**Comment by simogeo** [comment]
Indeed, tested with IE9 and having the same issue. Any idea of what could cause this ?

**Comment by potnoodles** [comment]
In my IE11 The level-up function is passing a window object "parent" to the replace function.

fixed this by changing global parent to local var which gets passed as string
$('#level-up').click(function() {

 //parent = cpath.substring(0, cpath.slice(0, -1).lastIndexOf("/")) + '/';
var parent = cpath.substring(0, cpath.slice(0, - 1).lastIndexOf("/")) + '/';

**Comment by simogeo** [comment]
thanks for feedback ! I'll PR your fix ! further test will be welcome @ptitbibice @potnoodles
