### ISSUE TITLE
Issue with uploading Video file

### ISSUE THREAD

**Issue by asaivishal** [simogeo/Filemanager#361]
Hi,

Thanks for this awesome Filemanager and I love using it.

I am able to successfully upload pdf and image files through this but I am having issue with uploading video file.

Getting below error while trying to upload video:
```Uncaught TypeError: Cannot read property 'Code' of null
f.upload.multiple.a.unbind.click.a.dropzone.success
require.register.Emitter.emit
require.register.Dropzone._finished
(anonymous function)```

**Comment by asaivishal** [comment]
![error](https://cloud.githubusercontent.com/assets/950650/8174999/548aa3e2-1427-11e5-9750-610895cd2d4a.PNG)

**Comment by simogeo** [comment]
This error is triggered by dropzone. Are you using Chrome ? Could you try with another browser ?

By the way, I tried to upload a video on the onlinde demo : http://fm.linea21.com/

And it works well. The file is name `chrome_japan`.  You can download it and try again on your FM version.

See also : 
* https://github.com/enyo/dropzone/issues/444
* https://github.com/enyo/dropzone/issues/285

**Comment by asaivishal** [comment]
Thanks for the reply and online demo.

I downloaded and uploaded chrome_japan video and it worked fine.  It uploads the .ogv file without any issue.  The file I am trying to upload is .mp4 file and when I tried to upload the same file on online demo, it threw the same error as I as getting on my FM implementation.

It throws the same error while uploading .wmv file as well.

Thanks in advance.

**Comment by simogeo** [comment]
What is the size of your mp4 file and what is the limit set in config file ? see [fileSizeLimit](https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file#the-upload-section)

**Comment by asaivishal** [comment]
Hi,

I am uploading 10MB file and fileSizeLimit is 50.

Thanks.

**Comment by simogeo** [comment]
> I am uploading 10MB file and fileSizeLimit is 50.

So, it should be ok. 
You have to know that `fileSizeLimit` value can be overwritten if `upload_max_filesize` and `post_max_size ` allow less than given values. So, you could have a look on that side.

For debugging, you can also try to set : 
```javascript
"upload": {
        "multiple": false,
```

It will remove dropzone - you may have another and explicit error message ...! ? Please let me know

If you did not find the cause, you can send / share the video for me to test directly.

*Note : Regarding `wmv` file, be sure it is allowed by your config file in `uploadRestrictions` [section](https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.config.js.default#L32). It is not by default.*

**Comment by simogeo** [comment]
So ?

**Comment by asaivishal** [comment]
Hey thank you so much for clarifying about upload_max_size and post_max_size.

my post_max_size was less than filesize I was using.  By increasing that limit it worked.

Thanks you so much again and sorry for delay in replying as I got carried away by other work.

Cheers.
