### ISSUE TITLE
Problem with Image Viewer

### ISSUE THREAD

**Issue by dangtathanh** [simogeo/Filemanager#363]
Hi,
I try to setup the lastest version of FileManager in my project. Everythings work fine except the Image Viewer. In the FileManger screen, the thumbnail of an image is a file type icon instead of the its thumbnail

![01](https://cloud.githubusercontent.com/assets/10228326/8175670/df20d144-1417-11e5-92c6-dbed9dd9657c.JPG)

This is my config options:
![02](https://cloud.githubusercontent.com/assets/10228326/8175685/1ab7e5e4-1418-11e5-942b-55222c7dc15e.JPG)

I want the image's thumbnail will be shown instead of file type icon. How to fix it? My project is a MVC 5 project.

**Comment by simogeo** [comment]
Hi,

It seems the preview mechanism is not implemented for the MVC connector. @hammond13 is the main MVC connector maintainer - I could probably confirm. 

Ayyway, any contributor is welcome and so it would be nice someone to add it ! maybe you ?  You can have a look on the [PHP connector](https://github.com/simogeo/Filemanager/blob/master/connectors/php/filemanager.class.php#L899) to see how it works and we may help you by giving you some advices.

**Comment by dangtathanh** [comment]
Hi @simogeo 
Thank you for your suggestion. I have a look at the ASHX connector and found out that the method IsImage does not work completely perfect. This method return value FALSE, althrough the input is a type of image. We can solve by below code:

![03](https://cloud.githubusercontent.com/assets/10228326/8178182/5788fdbe-1436-11e5-8bd0-5d260171c580.JPG)

**Comment by simogeo** [comment]
Ok, you are using ASHX connector .. You have to know that it is not up-to-date. I commited your proposed fix : c670b67c21ab50650373091cb6cf53138ca8b258

If you want to work on this connector, please let me know. Thanks

**Comment by dangtathanh** [comment]
I have tried to use MVC connector (replace "ashx" by "asp" or "mvc" in above config options) but it didn't work. The screen kept loading and nothing happend. Do I miss somethings?

![04](https://cloud.githubusercontent.com/assets/10228326/8179205/59aa7a56-143f-11e5-8204-903d618eac9a.JPG)

**Comment by simogeo** [comment]
I'ts a good choice to switch to MVC connector. It is not as complete as PHP but more advanced and more secure than ASHX.

Try to open Firebug to see what's happening there. Eventually you could post your config file here.

**Comment by simogeo** [comment]
If it does not work, you can also try this version : https://github.com/simogeo/Filemanager/releases/tag/v1.2

**Comment by dangtathanh** [comment]
Here is my config options for MVC connector

```JavaScript
{
    "_comment": "IMPORTANT : go to the wiki page to know about options configuration https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file",
    "options": {
        "culture": "en",
        "lang": "asp",
        "theme": "flat-dark",
        "defaultViewMode": "grid",
        "autoload": true,
        "showFullPath": false,
        "showTitleAttr": false,
        "browseOnly": false,
        "showConfirmation": true,
        "showThumbs": true,
        "generateThumbnails": true,
        "searchBox": true,
        "listFiles": true,
        "fileSorting": "default",
        "chars_only_latin": true,
        "dateFormat": "d M Y H:i",
        "serverRoot": false,
        "fileRoot": "/FilesStorage/",
        "baseUrl": false,
        "logger": false,
        "capabilities": ["select", "download", "rename", "delete", "replace"],
        "plugins": []
    },
    "security": {
        "allowFolderDownload": false,
        "allowChangeExtensions": false,
        "allowNoExtension": false,
        "uploadPolicy": "DISALLOW_ALL",
        "uploadRestrictions": [
            "jpg",
            "jpe",
            "jpeg",
            "gif",
            "png",
            "svg",
            "txt",
            "pdf",
            "odp",
            "ods",
            "odt",
            "rtf",
            "doc",
            "docx",
            "xls",
            "xlsx",
            "ppt",
            "pptx",
            "csv",
            "ogv",
            "mp4",
            "webm",
            "m4v",
            "ogg",
            "mp3",
            "wav",
            "zip",
            "rar"
        ]
    },
    "upload": {
        "multiple": true,
        "number": 5,
        "overwrite": false,
        "imagesOnly": false,
        "fileSizeLimit": 16
    },
    "exclude": {
        "unallowed_files": [
            ".htaccess",
            "web.config"
        ],
        "unallowed_dirs": [
            "_thumbs",
            ".CDN_ACCESS_LOGS",
            "cloudservers"
        ],
        "unallowed_files_REGEXP": "/^\\./",
        "unallowed_dirs_REGEXP": "/^\\./"
    },
    "images": {
        "imagesExt": [
            "jpg",
            "jpe",
            "jpeg",
            "gif",
            "png",
            "svg"
        ],
        "resize": {
        	"enabled":true,
        	"maxWidth": 1280,
            "maxHeight": 1024
        }
    },
    "videos": {
        "showVideoPlayer": true,
        "videosExt": [
            "ogv",
            "mp4",
            "webm",
            "m4v"
        ],
        "videosPlayerWidth": 400,
        "videosPlayerHeight": 222
    },
    "audios": {
        "showAudioPlayer": true,
        "audiosExt": [
            "ogg",
            "mp3",
            "wav"
        ]
    },
    "edit": {
        "enabled": true,
        "lineNumbers": true,
        "lineWrapping": true,
        "codeHighlight": false,
        "theme": "elegant",
        "editExt": [
            "txt",
            "csv"
        ]
    },
    "customScrollbar": {
    	"enabled": true,
    	"theme": "inset-2-dark",
    	"button": true
    },
    "extras": {
        "extra_js": [],
        "extra_js_async": true
    },
    "icons": {
        "path": "images/fileicons/",
        "directory": "_Open.png",
        "default": "default.png"
    },
    "url": "https://github.com/simogeo/Filemanager",
    "version": "2.0.0-dev"
}
```

**Comment by simogeo** [comment]
Try with `serverRoot` set to true or specify the full path to FilesStorage...

```javascript
"serverRoot": true,
"fileRoot": "/FilesStorage/",
```

**Comment by dangtathanh** [comment]
It's stil not working. Some errors appear

![01](https://cloud.githubusercontent.com/assets/10228326/8180437/e6cda7fc-1447-11e5-95d3-b138432943c5.JPG)

**Comment by simogeo** [comment]
It seems you are working with ASP conn.

**Comment by dangtathanh** [comment]
This quote is from the wiki. We have 3 options for ASP .NET, they are: asp, ashx and asp again. So, the value of lang option for MVC connector is ASP, isn't it?

```
lang Default value "php". Set this to the server side language you wish to use - options: php, jsp, lasso, asp, cfm, ashx, asp, pl.
```

**Comment by simogeo** [comment]
To use MVC, specify `mvc` value.

**Comment by dangtathanh** [comment]
I tried it but it's still not working

![02](https://cloud.githubusercontent.com/assets/10228326/8180879/a123aca2-144b-11e5-964d-287109e720e6.JPG)

**Comment by simogeo** [comment]
The message is clear enough ... even filemanger.config.js.default is not found

**Comment by dangtathanh** [comment]
When I use ASHX connector, that error appears too. But everythings works fine

![03](https://cloud.githubusercontent.com/assets/10228326/8181116/69c7f2ac-144d-11e5-87f6-431e9c01e512.JPG)

Can you post an example. We already have an example of MVC project here 
https://github.com/Rick-Anderson/MvcMovie5

**Comment by simogeo** [comment]
First, grab a copy of [filemanager.config.js.default](https://raw.githubusercontent.com/simogeo/Filemanager/master/scripts/filemanager.config.js.default) file into /Filemanager/scripts/ folder.

I can't really help you with MVC connector since I don't know it (I'm not the author) . Maybe @hammond13 can help you;

**Comment by hammond13** [comment]
Hi,

First of all, is your project an MVC project?  If not, the MVC connector won't work.

The MVC connector uses area registration in order to locate the connector.  This is needed in order to conform to the filemanager.{{lang}} format.  See the FilemanageAreaRegistration.cs file:
https://github.com/simogeo/Filemanager/blob/master/connectors/mvc/FilemanagerAreaRegistration.cs

It looks like your filemanager folder is in your root directory so change
"Scripts/filemanager/connectors/mvc/filemanager.mvc"
to
"filemanager/connectors/mvc/filemanager.mvc"

Then also look in FilemanagerConnector.cs. There are a few setting you will need to check, including two you will need to add to web.config (examples in the comments).

One caveat: it has been many months since I synced up my code, and it looks like there have been a lot of changes since then.  So the MVC connector has not been tested with the latest code.

I hope that helps.

**Comment by dangtathanh** [comment]
Hi 
@simogeo
Thanks! I have not removed filemanager.config.js.default from my project yet. This error happens because IIS cannot recognize extension of this file (.default). Just add MIME type for this extension and it will work fine.

@hammond13 ,
Yes, I'm sure that it's a MVC project. I tried everythings you said, but it didn't work. I followed these steps:
1> Download Filemanager from github
2> Unzip downloaded file
3> Copy unzipped folder to the project
4> Copy filemanager.config.js.default in /Filemanager/scripts/ folder and parse in the same folder. Then change the copied file from "filemanager.config.js - Copy.default" to "filemanager.config.js"
5> Change some options in file "filemanager.config.js" 
from
```Javascript
"lang": "php",
"serverRoot": true,
"fileRoot": false,
```
to
```Javascript
"lang": "mvc",
"serverRoot": false,
"fileRoot": "/FilesStorage/",
```
Additional steps as you said
6> Change FilemanageAreaRegistration.cs file
from
```C#
/// <summary>
/// Registers the area
/// </summary>
public override void RegisterArea(AreaRegistrationContext context)
{
    context.MapRoute(
	"Filemanager_default",
	"Scripts/filemanager/connectors/mvc/filemanager.mvc",
	new { controller = "Filemanager", action = "Index" },
	new string[] { "MyProject.Areas.FilemanagerArea.Controllers" }
	);
}
```
to
```C#
/// <summary>
/// Registers the area
/// </summary>
public override void RegisterArea(AreaRegistrationContext context)
{
    context.MapRoute(
	"Filemanager_default",
	"filemanager/connectors/mvc/filemanager.mvc",
	new { controller = "Filemanager", action = "Index" },
	new string[] { "MyProject.Areas.FilemanagerArea.Controllers" }
	);
}
```

7> Add 2 options to web.config
```XML
<appSettings>
    <add key="Filemanager_RootPath" value="/uploads/"/>
    <add key="Filemanager_IconDirectory" value="/filemanager/images/fileicons/"/>
</appSettings>
```

I tried open these 2 URLs in browser and got 404 Error (File or directory not found.)
```URL
/filemanager/connectors/mvc/filemanager
/filemanager/connectors/mvc/filemanager.mvc

```

**Comment by hammond13** [comment]
You may need to make sure that your area registrations are actually getting registered.  A new MVC project will generally have this set up by default, but you may not. In your Glabal.asax.cs file, in the Application_Start function make sure you have this:

AreaRegistration.RegisterAllAreas();

**Comment by dangtathanh** [comment]
Hi @hammond13,
Area registrations are already getting registered. I have setup Filemanager in a MVC 4 project and it worked perfectly. So, I think Area registrations not working correctly in MVC 5 project. Can you take a test for MVC 5 project?

**Comment by hammond13** [comment]
Oh, that's possible.  I'm never used it in an MVC 5 project.  Sorry, I won't have time to test this in the short term.  Your best bet may be to take the MapRoute code and move it into your Global.asax.cs file wherever your other routes are.  I was only using an area registration for convenience, and its only purpose is to map that route to the connector file.

**Comment by simogeo** [comment]
@dangtathanh : please post feedback or tell us if we can close the issue
