### ISSUE TITLE
Left tree - just showing the root

### ISSUE THREAD

**Issue by sebastiansouth** [simogeo/Filemanager#369]
Hello

1. The tree view on the left. It's showing me just root.Clicking don't work
2. Search below does not work
3. Undefined ?
![fm](https://cloud.githubusercontent.com/assets/13162515/8495078/f5733e4a-216a-11e5-9fc0-25ca789eb440.jpg)

Well, I am not a pro  :)   but for some hints i will be very thankful

bg
Sebastian

**Comment by simogeo** [comment]
I would give you the advice of starting again with a new application archive. Just copy-paste the default config file and rename it. It should work correctly
