### ISSUE TITLE
Get the root folder

### ISSUE THREAD

**Issue by wentiti** [simogeo/Filemanager#372]
Hi, i'm kevin, i just want help, i can't see anything on the root folder, i followed the steps, but nothing, i use wamp : easyphp.I copy and paste your directory folder in the www one and i change the filemanager.config.js.default in filemanager.config.js. please hepl me my email: tionokevin@live.fr thx

**Comment by simogeo** [comment]
Could be a setting issue or related to issue #306 (but it is supposed to be fixed)
