### ISSUE TITLE
Uploading files more than 8 MB produces errors in JSON

### ISSUE THREAD

**Issue by a-opazo** [simogeo/Filemanager#374]
Upload any file more than 8 Mb (even on the test page fm21...) will produce an error. Depending on the browser the error is reported in jquery:

firefox: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data (line 5 col 15994)

msie: 

if (callbacks) {
    callbacks = callbacks.slice(0);
    for (var i = 0, len = callbacks.length; i < len; ++i) {
      callbacks[i].apply(this, args);
SYNTAX ERROR

in the console, callbacks[0] returns
function(b,c){a("#uploadresponse").empty().html(c);var f=jQuery.parseJSON(a("#uploadresponse").find("textarea").text());0==f.Code?this.removeFile(b):(m(d),a("#filetree").find('a[data-path="'+d+'"]').click(),a.prompt(f.Error),error_flag=!0)}

No idea what's happening.

**Comment by simogeo** [comment]
I have no problem uploading a 13 MB file in online demo.

May be related to https://github.com/simogeo/Filemanager/issues/361
Could you please investigate since I don't have much time right now

**Comment by a-opazo** [comment]
I will try to investigate and see what's happening. No promises, though, since my knowledge of javascript is not that advanced, but at least i can deal with debuggers and code.

Thanks for the response.

**Comment by simogeo** [comment]
You can also try to change [fileSizeLimit](https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file#the-upload-section) to see if the bug is not happening when reaching the limit.
