### ISSUE TITLE
Autorefresh on update/delete action

### ISSUE THREAD

**Issue by dg-** [simogeo/Filemanager#375]
Hi everyone,

I noticed the following strange behavior:

When deleting or renaming a directory the changes are visible instantly, which includes the tree on the left side. Doing the same operation on files does not result in this instant "refreshes". That means deleted files are still visible on the side tree and in the main part of the window, until I refresh manually (F5). The same applies to changes to a file name.

Can somebody reproduce this?

**Comment by simogeo** [comment]
Probably a wrong configuration on your local install. Works well on http://fm.linea21.com/
Just try yourself

If you want further help, please specify your settings.
