### ISSUE TITLE
Filemanager ie 8 error

### ISSUE THREAD

**Issue by ptitbibice** [simogeo/Filemanager#376]
Hi,

When i go to demo with ie 8 => http://fm.linea21.com/ , the FileManager don't work.
I don't understand the error.

Regards

**Comment by simogeo** [comment]
It seems IE8 does not support jquery1.11.3. See : 
* http://stackoverflow.com/questions/22073479/what-is-the-latest-jquery-version-to-work-with-ie8
* http://blog.jquery.com/2014/12/18/jquery-1-11-2-and-2-1-3-released-safari-fail-safe-edition/

Should work correctly with release 2.1.0 : https://github.com/simogeo/Filemanager/releases/tag/v2.1.0

**Comment by CocacolaSh** [comment]
it does not work....if i remove the zeroclipboard,then not js error，but the css load incorrect.

**Comment by simogeo** [comment]
> but the css load incorrect.

what do you mean ?

**Comment by CocacolaSh** [comment]
Thanks for reply,  The style of the page display is wrong, for example, the button is arranged to the left,  the icon  of thebutton did not show, as if there is no style

**Comment by simogeo** [comment]
Is the style ok if you just comment `loadJS('./scripts/zeroclipboard/dist/ZeroClipboard.js');` line 1591 ?

**Comment by CocacolaSh** [comment]
if i comment loadJS('./scripts/zeroclipboard/dist/ZeroClipboard.js'); all the style show was incorrect 

![image](https://cloud.githubusercontent.com/assets/1592176/9488739/8c6c7776-4c0e-11e5-9d6d-afe55345aa48.png)

**Comment by simogeo** [comment]
any error message in console ?

**Comment by CocacolaSh** [comment]
i am so sorry,there have not any error,it is so Weird

**Comment by CocacolaSh** [comment]
i am so sorry,there have not any error,it is so Weird

**Comment by simogeo** [comment]
cache issue ?

**Comment by CocacolaSh** [comment]
I have cleaned up the cache,use F12 the ctrl+r. in chorme or firefox it run ok.but in IE8 so weird,
