### ISSUE TITLE
Custom Connector

### ISSUE THREAD

**Issue by Skelet0r67** [simogeo/Filemanager#384]
Hello,

I have created a custom connector and I am having trouble figuring out how to make the file manager application use that path for that connector. Is there a specific configuration property that I have to change?

**Comment by simogeo** [comment]
There is 2 ways to define connector.

By default the app use the `lang` var and recreate full path based on that rule : 

> var fileConnector =  'connectors/' + config.options.lang + '/filemanager.' + config.options.lang;

See code : https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.js#L112

Bu as you can see, you can also add `fileConnector` var into your js config file and specify the full path.

> var fileConnector = config.options.fileConnector || 'connectors/' + config.options.lang + '/filemanager.' + config.options.lang;

**Comment by Skelet0r67** [comment]
ahh okay, thank you that did the trick.. one more thing though.. now that i have the connector working with the file manager, I noticed that on the getJson call the object returned is just as string and the logic which iterates over the different properties expects a javascript object. I've started to put this line after the get json call to parse it into a javascript object. Is there a reason why jquery isn't parsing the json and I am having to put this in?

$.getJSON(url, function(data){
        data = JSON.parse(data);

**Comment by simogeo** [comment]
>  Is there a reason why jquery isn't parsing the json and I am having to put this in? 

Have no idea but your connector must retuen a json object, as it does in PHP for example using [json_encode() function](http://php.net/manual/fr/function.json-encode.php).
