### ISSUE TITLE
Error: "No Way." Files wont show. 

### ISSUE THREAD

**Issue by mattlr20** [simogeo/Filemanager#385]
I believe this particular "No Way" error is from line 230 in the php connector. Any ideas?

Here is the log.
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::enableLog - Log enabled (in Z:/filemanager_log.txt file)
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::__construct $this->root value Z:\path\Filemanager-master\
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::__construct $this->path_to_files Z:\path\Filemanager-master\userfiles/
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::__construct $this->doc_root value Z:\www
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::__construct $this->separator value userfiles
[08/09/2015 02:43:49]#1.0.0.1#substr path_to_files : \
[08/09/2015 02:43:49]#1.0.0.1#path_to_files : Z:\path\Filemanager-master\userfiles\
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::error - error message : No way.
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::enableLog - Log enabled (in Z:/filemanager_log.txt file)
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::__construct $this->root value Z:\path\Filemanager-master\
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::__construct $this->path_to_files Z:\path\Filemanager-master\userfiles/
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::__construct $this->doc_root value Z:\www
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::__construct $this->separator value userfiles
[08/09/2015 02:43:49]#1.0.0.1#substr path_to_files : \
[08/09/2015 02:43:49]#1.0.0.1#path_to_files : Z:\path\Filemanager-master\userfiles\
[08/09/2015 02:43:49]#1.0.0.1#Filemanager::error - error message : No way.

**Comment by simogeo** [comment]
FM is suspecting an attack .... could you post your config file ?

**Comment by mattlr20** [comment]
Thanks for replying, here's the config. 

<?xml version="1.0" encoding="UTF-8"?>

<configuration>
	<configSections>
		<sectionGroup name="system.web.extensions" type="System.Web.Configuration.SystemWebExtensionsSectionGroup, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35">
			<sectionGroup name="scripting" type="System.Web.Configuration.ScriptingSectionGroup, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35">
				<section name="scriptResourceHandler" type="System.Web.Configuration.ScriptingScriptResourceHandlerSection, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" requirePermission="false" allowDefinition="MachineToApplication" />
				<sectionGroup name="webServices" type="System.Web.Configuration.ScriptingWebServicesSectionGroup, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35">
					<section name="jsonSerialization" type="System.Web.Configuration.ScriptingJsonSerializationSection, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" requirePermission="false" allowDefinition="Everywhere" />
					<section name="profileService" type="System.Web.Configuration.ScriptingProfileServiceSection, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" requirePermission="false" allowDefinition="MachineToApplication" />
					<section name="authenticationService" type="System.Web.Configuration.ScriptingAuthenticationServiceSection, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" requirePermission="false" allowDefinition="MachineToApplication" />
				</sectionGroup>
			</sectionGroup>
		</sectionGroup>
	</configSections>
	<connectionStrings>
		<add name="ConnectionString" connectionString="Data Source=servername;Initial Catalog=database;Integrated Security=True" providerName="System.Data.SqlClient" />
		<add name="ConnectionString" connectionString="Data Source=servername;Initial Catalog=database;Integrated Security=True" providerName="System.Data.SqlClient" />
		<add name="ConnectionString" connectionString="Data Source=servername;Initial Catalog=database;Integrated Security=True" providerName="System.Data.SqlClient" />
	</connectionStrings>
	<appSettings>
		<add key="ErrorEmailAddresses" value="jamie.brown@company.com;jeff.myers@company.com;alex.ramsey@company.com" />
		<add key="EmailError" value="true" />
		 
		
	</appSettings>
	<system.web>
		<compilation debug="true" strict="true" explicit="true">
			<assemblies>
				<add assembly="System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
				<add assembly="System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
				<add assembly="System.Management, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
				<add assembly="System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
				<add assembly="CrystalDecisions.CrystalReports.Engine, Version=10.2.3600.0, Culture=neutral, PublicKeyToken=692FBEA5521E1304" />
				<add assembly="CrystalDecisions.ReportSource, Version=10.2.3600.0, Culture=neutral, PublicKeyToken=692FBEA5521E1304" />
				<add assembly="CrystalDecisions.Shared, Version=10.2.3600.0, Culture=neutral, PublicKeyToken=692FBEA5521E1304" />
				<add assembly="CrystalDecisions.Web, Version=10.2.3600.0, Culture=neutral, PublicKeyToken=692FBEA5521E1304" />
				<add assembly="CrystalDecisions.ReportAppServer.ClientDoc, Version=10.2.3600.0, Culture=neutral, PublicKeyToken=692fbea5521e1304" />
				<add assembly="CrystalDecisions.Enterprise.Framework, Version=10.2.3600.0, Culture=neutral, PublicKeyToken=692fbea5521e1304" />
				<add assembly="CrystalDecisions.Enterprise.InfoStore, Version=10.2.3600.0, Culture=neutral, PublicKeyToken=692fbea5521e1304" />
				<add assembly="System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
				<add assembly="System.Web.Extensions.Design, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
				<add assembly="System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
				<add assembly="System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
				<add assembly="System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
				<add assembly="System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
				<add assembly="System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
				<add assembly="System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
				<add assembly="System.Web.Services, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
				<add assembly="System.DirectoryServices.Protocols, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
				<add assembly="System.EnterpriseServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
				<add assembly="System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
				<add assembly="System.Web.RegularExpressions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" /></assemblies>
		</compilation>
		<pages theme="Intranet" validateRequest="false" enableEventValidation="false" viewStateEncryptionMode="Never">
			<controls>
				<add tagPrefix="ABC" assembly="ABC.Web" namespace="ABC.Web.UI.WebControls" />
				<add tagPrefix="asp" namespace="System.Web.UI" assembly="System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
				<add namespace="AjaxControlToolkit" assembly="AjaxControlToolkit" tagPrefix="ajaxToolkit" />
			</controls>
			<namespaces>
				<clear />
				<add namespace="System" />
				<add namespace="System.Collections" />
				<add namespace="System.Collections.Specialized" />
				<add namespace="System.Configuration" />
				<add namespace="System.Text" />
				<add namespace="System.Text.RegularExpressions" />
				<add namespace="System.Web" />
				<add namespace="System.Web.Caching" />
				<add namespace="System.Web.SessionState" />
				<add namespace="System.Web.Security" />
				<add namespace="System.Web.Profile" />
				<add namespace="System.Web.UI" />
				<add namespace="System.Web.UI.WebControls" />
				<add namespace="System.Web.UI.WebControls.WebParts" />
				<add namespace="System.Web.UI.HtmlControls" />
				<add namespace="System.Data" />
				<add namespace="System.Data.SqlClient" />
				<add namespace="ABC.Data" />
			</namespaces>
		</pages>
		
		<authentication mode="Windows" />
		<identity impersonate="true" />
		<authorization>
			<allow users="*" />
			<deny users="?" />
		</authorization>
		
		<customErrors mode="Off" />
		<httpHandlers>
			<remove verb="*" path="*.asmx" />
			<add verb="*" path="*.asmx" validate="false" type="System.Web.Script.Services.ScriptHandlerFactory, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
			<add verb="*" path="*_AppService.axd" validate="false" type="System.Web.Script.Services.ScriptHandlerFactory, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
			<add verb="GET,HEAD" path="ScriptResource.axd" type="System.Web.Handlers.ScriptResourceHandler, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" validate="false" />
		</httpHandlers>
		<httpModules>
			<add name="ScriptModule" type="System.Web.Handlers.ScriptModule, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
		</httpModules>
		
		<httpRuntime executionTimeout="1200" maxRequestLength="102400" />
	</system.web>
	<location path="path/Contacts.aspx">
		<system.web>
			<authorization>
				<allow users="*" />
			</authorization>
		</system.web>
	</location>
	<location path="path/Timesheet.aspx">
		<system.web>
			<authorization>
				<allow users="*" />
			</authorization>
		</system.web>
	</location>
	<location path="path/SQLExcel.aspx">
		<system.web>
			<authorization>
				<allow users="COMPANY\Jason, COMPANY\Angela" />
			</authorization>
		</system.web>
	</location>
	<location path="path/Utilities/FileWatcher.aspx">
		<system.web>
			<authorization>
				<allow users="COMPANY\Jennifer, COMPANY\Kate" />
			</authorization>
		</system.web>
	</location>
	<location path="path/IS">
		<system.web>
			<authorization>
				<allow roles="COMPANY\IS_Dept" />
				<deny users="*" />
			</authorization>
		</system.web>
	</location>
	<location path="path/Processemails">
		<system.web>
			<authorization>
				<allow users="COMPANY\Angela" />
			</authorization>
		</system.web>
	</location>
	<system.webServer>
		<validation validateIntegratedModeConfiguration="false" />
		<modules>
			<add name="ScriptModule" preCondition="integratedMode" type="System.Web.Handlers.ScriptModule, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
		</modules>
		<handlers>
			<remove name="WebServiceHandlerFactory-Integrated" />
		    <remove name="PHP via FastCGI" />		
		    <add name="PHP via FastCGI" path="*.php" verb="*" modules="FastCgiModule" scriptProcessor="C:\Program Files (x86)\PHP\php-cgi.exe" resourceType="File" requireAccess="Script" />
			<add name="ScriptHandlerFactory" verb="*" path="*.asmx" preCondition="integratedMode" type="System.Web.Script.Services.ScriptHandlerFactory, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
			<add name="ScriptHandlerFactoryAppServices" verb="*" path="*_AppService.axd" preCondition="integratedMode" type="System.Web.Script.Services.ScriptHandlerFactory, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
			<add name="ScriptResource" preCondition="integratedMode" verb="GET,HEAD" path="ScriptResource.axd" type="System.Web.Handlers.ScriptResourceHandler, System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
		</handlers>
	</system.webServer>

</configuration>

**Comment by simogeo** [comment]
I'm talking about this file : 
https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.config.js.default

**Comment by mattlr20** [comment]
{
		"_comment": "IMPORTANT : go to the wiki page to know about options configuration https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file",
    "options": {
        "culture": "en",
        "lang": "php",
        "theme": "flat-dark",
        "defaultViewMode": "grid",
        "autoload": true,
        "showFullPath": false,
        "showTitleAttr": false,
        "browseOnly": false,
        "showConfirmation": true,
        "showThumbs": true,
        "generateThumbnails": true,
        "searchBox": true,
        "listFiles": true,
        "fileSorting": "default",
        "chars_only_latin": true,
        "dateFormat": "d M Y H:i",
        "serverRoot": true,
        "fileRoot": false,
        "baseUrl": false,
        "logger": true,
		"logfile": "C:/filemanager_log.txt",
        "capabilities": ["select", "download", "rename", "delete", "replace"],
        "plugins": []
    },
    "security": {
        "allowFolderDownload": false,
        "allowChangeExtensions": false,
        "allowNoExtension": false,
        "uploadPolicy": "DISALLOW_ALL",
        "uploadRestrictions": [
            "jpg",
            "jpe",
            "jpeg",
            "gif",
            "png",
            "svg",
            "txt",
            "pdf",
            "odp",
            "ods",
            "odt",
            "rtf",
            "doc",
            "docx",
            "xls",
            "xlsx",
            "ppt",
            "pptx",
            "csv",
            "ogv",
            "mp4",
            "webm",
            "m4v",
            "ogg",
            "mp3",
            "wav",
            "zip",
            "rar"
        ]
    },
    "upload": {
        "multiple": true,
        "number": 5,
        "overwrite": false,
        "imagesOnly": false,
        "fileSizeLimit": 16
    },
    "exclude": {
        "unallowed_files": [
            ".htaccess",
            "web.config"
        ],
        "unallowed_dirs": [
            "_thumbs",
            ".CDN_ACCESS_LOGS",
            "cloudservers"
        ],
        "unallowed_files_REGEXP": "/^\\./",
        "unallowed_dirs_REGEXP": "/^\\./"
    },
    "images": {
        "imagesExt": [
            "jpg",
            "jpe",
            "jpeg",
            "gif",
            "png",
            "svg"
        ],
        "resize": {
        	"enabled":true,
        	"maxWidth": 1280,
            "maxHeight": 1024
        }
    },
    "videos": {
        "showVideoPlayer": true,
        "videosExt": [
            "ogv",
            "mp4",
            "webm",
            "m4v"
        ],
        "videosPlayerWidth": 400,
        "videosPlayerHeight": 222
    },
    "audios": {
        "showAudioPlayer": true,
        "audiosExt": [
            "ogg",
            "mp3",
            "wav"
        ]
    },
    "pdfs": {
        "showPdfReader": true,
        "pdfsExt": [
            "pdf",
            "odp"
        ],
	    "pdfsReaderWidth": "640",
        "pdfsReaderHeight": "480"	
    },
    "edit": {
        "enabled": true,
        "lineNumbers": true,
        "lineWrapping": true,
        "codeHighlight": false,
        "theme": "elegant",
        "editExt": [
            "txt",
            "csv"
        ]
    },
    "customScrollbar": {
    	"enabled": true,
    	"theme": "inset-2-dark",
    	"button": true
    },
    "extras": {
        "extra_js": [],
        "extra_js_async": true
    },
    "icons": {
        "path": "images/fileicons/",
        "directory": "_Open.png",
        "default": "default.png"
    },
    "url": "https://github.com/simogeo/Filemanager",
    "version": "2.0.0-dev"
}

**Comment by simogeo** [comment]
OS version ? are you using a AMP package ?

**Comment by mattlr20** [comment]
I am using Windows OS. I am not using a AMP package.

**Comment by simogeo** [comment]
what is the path to your web server ? what is the path to your Filemanger folder ?

**Comment by mattlr20** [comment]
The path to the filemanager folder is C:/dev/webprojects/Intranet/wwwroot/filemanager

Sorry, I'm having trouble finding out the path to the web server.

**Comment by simogeo** [comment]
```php
echo $_SERVER['DOCUMENT_ROOT']
```

**Comment by mattlr20** [comment]
Thanks, here its: 
C:\dev\www

**Comment by simogeo** [comment]
1. So, put FM folder into `C:\dev\www`

2. Be sure to copy/paste `/scripts/filemanager.config.js.default` and rename it to `/scripts/filemanager.config.js`

3. open your browser to http://localhost/filemanager/

4. it will works

**Comment by mattlr20** [comment]
It works! Thanks for helping so quickly!
