### ISSUE TITLE
Can the upload folder be in a network drive?

### ISSUE THREAD

**Issue by mattlr20** [simogeo/Filemanager#386]
If so, do you have any examples?

Thanks,
Matthew

**Comment by simogeo** [comment]
It may be possible with `symlink`. See : 

* http://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/
* https://social.technet.microsoft.com/Forums/windowsserver/en-US/f55698fd-028c-44e2-b3c4-9d05d7371ce0/creating-a-symlink-directory-on-a-network-share-to-a-path-below-a-mapped-drive-letter-local-path?forum=winserverfiles

**Comment by mattlr20** [comment]
Thanks for the help, I'll check it out.
