### ISSUE TITLE
Cannot get MVC connector to work.

### ISSUE THREAD

**Issue by LaravelNick** [simogeo/Filemanager#389]
Does anyone have any sample code or sample project to demonstrate how to use this connector please ?

For instance, how do we get IIS / ASP.Net to recognise and process ".mvc" extensions ?

public override void RegisterArea(AreaRegistrationContext context)
        {
            context.MapRoute(
                "Filemanager_default",
                "Scripts/filemanager/connectors/mvc/filemanager.mvc",
                new { controller = "Filemanager", action = "Index" },
                new string[] { "MyProject.Areas.FilemanagerArea.Controllers" }
            );
        }

**Comment by hammond13** [comment]
Hi, 

The code has an example of using an area registration to map the route to the connector.  So you can either use that code and call AreaRegistration.RegisterAllAreas() in your Global.asax file, or you can map the route directly in your Global.asax file the same way that you would map any other route.  Make sure the route you map matches the location of you filemanager directory.

There are some settings in FilemanagerConnector.cs that you will have to set in addition to filemanager.config.js.

Note that I have not synced up my code with the latest FileManager code, so I have not verified that the latest version works with the MVC connector, but I know of no reason it should have stopped working.

**Comment by LaravelNick** [comment]
Hi David,

Many thanks indeed for your reply. I'm using ASP.Net MVC 5 and with a bit of trial and error, I've finally managed to get it working well.

Thanks again.

**Comment by jlaustill** [comment]
LavavelNick, would you care to share what you did to get this working?  I'm struggling at the same place you did :)
