### ISSUE TITLE
How to get image path with domain ?

### ISSUE THREAD

**Issue by lonerunner** [simogeo/Filemanager#390]
I can't get a full path to the image with domain name in response. 
I thought that `"showFullPath": true,` is to retrieve full path of the image like `http://domain.name/userfiles/user/image.jpg` but it's the same weather i set it to true or false.

I have integrated filemanager with ckeditor and laravel 5 and everything seems to work fine except the images i upload and try to get the path of images only retrieve path without domain name like `/userfiles/user/image.jpg` Trying to use that with ckeditor i get a problem where images selected are not displayed in ckeditor textarea field.

Is there a way to get a full path of the image with domain name.
I have also tried to use filemanager alone without ckeditor and when i select image and `Copy to clipboard` i also get just imagepath without domain name.

**Comment by simogeo** [comment]
Use `baseUrl` parameter in config file : 

see the doc : https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file#the-options-section

**Comment by lonerunner** [comment]
It still doesn't work with baseUrl, i mean it sorta works but i have to set baseUrl like http://domain.name but in this case when i change domain name(or switch from local to server) i would have to change settings too, anyway i kinda found a solution i added the `url` variable in connector config.php file.
