### ISSUE TITLE
Filemanager from a simple textfield open in modal possible?

### ISSUE THREAD

**Issue by lonerunner** [simogeo/Filemanager#391]
I have found instructions on opening filemanager in textfield here https://github.com/simogeo/Filemanager/wiki/How-to-use-the-filemanager-from-a-simple-textfield-%3F

And i have also found instructions on opening filemanager in modal window when using it with ckeditor https://github.com/simogeo/Filemanager/wiki/How-to-open-the-Filemanager-from-CKEditor-in-a-modal-window-%3F

But is it possible to open filemanager in modal window when using it standalone with input field and button ? I am not so good at javascripts and few solutions i tried to combine from those 2 instructions above, results in opening some kind of iframe but empty frame without filemanager.

**Comment by simogeo** [comment]
The simplest (and nice) way to do is to use colorbox. See the following [how to](https://github.com/simogeo/Filemanager/wiki/How-to-use-the-filemanager-with-colorbox-%3F).

See also colorbox page and samples at http://www.jacklmoore.com/colorbox/
