### ISSUE TITLE
Help i can't upload image

### ISSUE THREAD

**Issue by baophong09** [simogeo/Filemanager#392]
Please help me fix this
http://imgur.com/R4AgSd3

**Comment by simogeo** [comment]
I guess 'undefined' is not the desired path ......

Please read installation instructions : 
https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file
https://github.com/simogeo/Filemanager/wiki/Specify-user-folder%2C-configuration-cases

and Laravel howto : https://github.com/simogeo/Filemanager/wiki/Integrate-the-Filemanager-with-Laravel

**Comment by simogeo** [comment]
I guess it is ok right now. Please re-open if needed
