### ISSUE TITLE
Feature request: Have a readonly access depending on user

### ISSUE THREAD

**Issue by koocotte** [simogeo/Filemanager#394]
Hello, we use Filemanager to share some files and pictures in a nursery.

I would like to be able to use Filemanager in two different ways : 
 * uploading and managing files (full featured filemanager as it work today) by nursery workers
 * and to browse and download them without write access for parents.

I already have both type of user, but can't fine a way in user.config.php to switch between thoses two mode.

**Comment by simogeo** [comment]
From now, you can use config parameter in URL.
See https://github.com/simogeo/Filemanager/wiki/Passing-parameters-to-the-FM#passing-a-config-file

So, just prepare a config file with "browseOnly" parameter set to true ... and you will get this done !
