### ISSUE TITLE
HTTPS/SSL issues due HTTP font import

### ISSUE THREAD

**Issue by HHGAG** [simogeo/Filemanager#395]
Could you change all external http import calls to https due SSL connection issues, please.
E.g.
https://github.com/simogeo/Filemanager/blob/5586177fe13a44aef29d990482e9675b85c66a0d/themes/flat-dark/styles/filemanager.css#L6

**Comment by simogeo** [comment]
WHere are they ?

**Comment by simogeo** [comment]
should be ok
