### ISSUE TITLE
php 5.2 (and maybe less) compatibility

### ISSUE THREAD

**Issue by Fro99666** [simogeo/Filemanager#396]
hi,

to increase php compatibility you just need to add this php function who add array_replace_recursive if it doesnot exist (tester on php 5.2 on windows 2000):

if (!function_exists('array_replace_recursive'))
{
  function array_replace_recursive($array, $array1)
  {
    function recurse($array, $array1)
    {
      foreach ($array1 as $key => $value)
      {
        // create new key in $array, if it is empty or not an array
        if (!isset($array[$key]) || (isset($array[$key]) && !is_array($array[$key])))
        {
          $array[$key] = array();
        }
  
        // overwrite the value in the base array
        if (is_array($value))
        {
          $value = recurse($array[$key], $value);
        }
        $array[$key] = $value;
      }
      return $array;
    }
  
    // handle the arguments, merge one by one
    $args = func_get_args();
    $array = $args[0];
    if (!is_array($array))
    {
      return $array;
    }
    for ($i = 1; $i < count($args); $i++)
    {
      if (is_array($args[$i]))
      {
        $array = recurse($array, $args[$i]);
      }
    }
    return $array;
  }
}

**Comment by simogeo** [comment]
Thanks. I may add this

**Comment by simogeo** [comment]
done, see 386f6cbb72609a1f692ba36d15fe8357a815ac81
