### ISSUE TITLE
Wrong path when selecting an image

### ISSUE THREAD

**Issue by ionesculiviucristian** [simogeo/Filemanager#397]
Hello. I have a problem with my current setup:
- Laravel 5

- filemanager.config.js
```javascript
"serverRoot": false,
"fileRoot": "/",
```
- user.config.php
```php
$fm = new Filemanager();
$fm->setFileRoot(public_path('uploads/userfiles/'));
```
The problem is that after i upload an image and try to insert it, it puts the full path to the image's url and thus showing me the red icon for missing files. I resolved this by adding at line 197 in filemanager.class.php the following:

```php
$url = str_replace("\\","/",$this->path_to_files);
$path = '/'.str_replace($_SERVER['DOCUMENT_ROOT'], '', $url) . $this->get['path'];
```
Is there any way to avoid modifying the above ? Maybe my setup is wrong. Thanks.

**Comment by simogeo** [comment]
Could you copy-paste the returned path by the FM ? 
and the expected path - the one you get after hacking the FM

**Comment by ionesculiviucristian** [comment]
From 
````php
$path = $this->dynamic_fileroot. $this->get['path'];
````
 i get

> C:\wamp\www\eoncms/public_html\uploads/userfiles//cool_picture.jpg

and from my modified code i get

> /eoncms/public_html/uploads/userfiles/cool_picture.jpg

**Comment by simogeo** [comment]
yep, I guess `public_path()` is not the way to go since it returns a full path
http://laravel.io/forum/04-07-2014-public-path-vs-url?page=1

Try : 

```javascript
"serverRoot": true,
"fileRoot": "/",
```

```php
$fm = new Filemanager();
$fm->setFileRoot(public_path('/eoncms/public_html/uploads/userfiles/'));
```

By the way, you may be interested by using the FM laravel package : https://github.com/bestmomo/filemanager

**Comment by ionesculiviucristian** [comment]
With that configuration
````php
public_path('/eoncms/uploads/userfiles/')
````
i get this path
> C:\wamp\www\eoncms/public_html\/eoncms/public_html/uploads/userfiles/

and this error

> The directory / does not exist.

**Comment by ionesculiviucristian** [comment]
I've tested the method used in the bestmomo/filemanager with

````php
$folderPath = $app->basePath() . '/public_html/uploads/userfiles/';
$fm->setFileRoot($folderPath);
````
````javascript
"serverRoot": false,
"fileRoot": "/",
"baseUrl": "/uploads/"
````
and now
````php
$path = $this->dynamic_fileroot. $this->get['path'];
````
is
> C:\wamp\www\eoncms/public_html/uploads/userfiles//cool_picture.jpg

This is the same problem I was having from the start. I haven't installed the linked library to see if that works because I only want to fix this issue. Everything else seems fine.

**Comment by tok3** [comment]
Same issue with laravel package. For me things are running on macos but when  deployed to debian linux the bug occurs. Temporarily I fixed it be adding this snippet at line 282 in filemanager.class.php in the published connectors/php. 

```php

        $in_path = '/public';
        if (stristr($path, $in_path))
        {
            $pos = strpos($path, $in_path);
            $path = substr($path, $pos + strlen($in_path));
        }
```

**Comment by vijaysebastian** [comment]
@tok3 can you please provide your connectors/php/filemanager.class.php.

I have still problem in image select,

**Comment by tok3** [comment]
Hi, 

sorry for the delay I’ve totally overseen the mail. 
attached you’ll find my filemanager.class.php,

regards 





-- 
eQUIPE3W

Tel:   +49(0) 611 166 608 94
Fax:   +49(0) 611 360 049 24
Mobil: +49(0) 172 915 380 2

Email: tobias@eq3w.de <mailto:tobias@mmsetc.de>
Web:   www.eq3w.de <http://www.mmsetc.de/>

----------------------------------------------------

VERTRAULICHE INFORMATIONEN!

Diese eMail enthält vertrauliche Informationen und ist nur für den berechtigten Empfänger bestimmt. Wenn diese eMail nicht für Sie bestimmt ist, bitten wir Sie, diese eMail an uns zurückzusenden und anschließend auf Ihrem Computer und Mail-Server zu löschen. Solche eMails und Anlagen dürfen Sie weder nutzen, noch verarbeiten oder Dritten zugänglich machen, gleich in welcher Form.

Wir danken für Ihre Kooperation!



CONFIDENTIAL!

This email contains confidential information and is intended for the authorised recipient only. If you are not an authorised recipient, please return the email to us and then delete it from your computer and mail-server. You may neither use nor edit any such emails including attachments, nor make them accessible to third parties in any manner whatsoever.

Thank you for your cooperation.

**Comment by ianfebriyanto** [comment]
I have this issue, in windows its working fine. but in linux (ubuntu), this is happened. hello @tok3 , can you share me the fix that you make ? thanks in advance.

**Comment by ianfebriyanto** [comment]
@vijaysebastian hey bro, can you share the temporary fix ? thanks in advance.

**Comment by tok3** [comment]
Hi, 

here is a link to my „quickfixed“ filmanager class https://www.dropbox.com/s/vmc74j98u48khhd/filemanager.class.php?dl=0&preview=filemanager.class.php <https://www.dropbox.com/s/vmc74j98u48khhd/filemanager.class.php?dl=0&preview=filemanager.class.php> 

hope it will help !

regrards
