### ISSUE TITLE
wrong uploadRestrictions when uploadPolicy=ALLOW_ALL

### ISSUE THREAD

**Issue by koocotte** [simogeo/Filemanager#398]
Using uploadPolicy=ALLOW_ALL with the php connector, 

filemanager.class.php `__construct()` load `filemanager.config.js.default` then `filemanager.config.js`.

I think `$this->config = array_replace_recursive ($config_default, $config)` is wrong. I have in uploadRestrictions the content of both files; and this result in all extensions in `filemanager.config.js.default` being denied.

**Comment by simogeo** [comment]
Well spotted @koocotte : actually I just tested array_merge native functions and I'm not able to get the wanted result ....

I also tried this : http://danielsmedegaardbuus.dk/2009-03-19/phps-array_merge_recursive-as-it-should-be/
and even this https://github.com/ckressibucher/array_merger with no success ....

One option, would be to [get all (non-numeric) keys recursively](http://php.net/manual/en/function.array-keys.php#114584) and then populate the table with config files.

Not sure to have time for that, right now

Another option, would simply be to remove default config file !

**Comment by koocotte** [comment]
You can use different keys:
uploadExtentionDenied: exe php vbs...
uploadExtentionAllowed: gif jpg jpeg png...
uploadExtentionDefault: ALLOW | DISALLOW

This would require less work.

**Comment by simogeo** [comment]
yes, but it is less elegant

**Comment by simogeo** [comment]
@koocotte : should be (simply) fixed ! 3d8c55923fe77956957aa39476bb01edff9171a7

Let me know !

**Comment by simogeo** [comment]
maybe, I should also delete restrictionUpload in js part !?

**Comment by simogeo** [comment]
Closing it. Please re-open if needed !
