### ISSUE TITLE
Default Configuration Warning prevention

### ISSUE THREAD

**Issue by Fro99666** [simogeo/Filemanager#400]
hi,

if you change in filemanager.class.php:
- date by @date
- getimagesize by @getimagesize
- filemtime by @filemtime
- filesize by @filesize

it will prevent json malfomation due to warning sent from default php config (who occur mainly on Windows)

**Comment by simogeo** [comment]
But Warnings should not be there !???

**Comment by Fro99666** [comment]
I know, but not all the people know how to set a server, so i am making an advice not an order, by the way the change i wrote don't really make any change to the code.
People who are not good with server configuration (or using a dev environement) will think your Filemanager don't work instead of thinking it come from thier configuration...this change prevent this case, if you don't want to bother with that, you can close my request ! don't worry i wont blame you for that.

**Comment by jlaustill** [comment]
I'm using this with.Net MVC and am getting an error 

> GET http://localhost:60687/Scripts/filemanager/scripts/filemanager.config.js.default?_=1456326921250 404 (Not Found)

Is this related?  I'm not sure where this is coming from?  The plugin seems to be working fine, I can upload and download images and insert them into TinyMCE fine, so I'm not even sure what this error even means, but I would like it to go away very much :)

**Comment by hammond13** [comment]
@jlaustill You shouldn't be trying to access filemanager.config.js.default at all. That's just an example file, and the file you use should have the default extension removed.  You're getting a 404 because IIS is not configured to serve .default files.

**Comment by simogeo** [comment]
You must call `filemanager.config.js.default` file. Just be sure you did not remove it.

**Comment by jlaustill** [comment]
Hammond13, I have the filemanager.config.js file in this location, and it's obviously using it or it wouldn't work at all.  If I rename it then it complains it's not there and errors out.  SO why is it still trying to grab the .default file as well is what I don't get?  I'm not referencing it anywhere at all, so it has to be something in the filemanager code.  I'll have to step through the code and see what's going on and report back.

**Comment by simogeo** [comment]
the FM calls **both** user config file **AND** default config file.

That way, updates are easier to handle for FM users.

**Comment by hammond13** [comment]
@jlaustill @simogeo Sorry, I didn't realize that. I has been a while since I synched up my code and the version I have doesn't call the .default file. I'm not sure about apache, but IIS won't server a .default file unless you add that extension to its list of MIME types.  Seems like if you want to reference that file in the code it should be called filemanager.config.default.js instead.

**Comment by jlaustill** [comment]
@simogeo @hammond13 Exactly my case I guess.  I would think filemanager.config.default.js would be a much better name myself.  I'm extremely reluctant to edit my MIME types just to adhere to something that works in apache.  For now I guess I will just step through the code and find the line loading the default and just comment it out and see if that works for me.

**Comment by simogeo** [comment]
Ok, I'll adapt the code. I let you know when it's done.

**Comment by jlaustill** [comment]
That would be awesome @simogeo, and I will be more than happy to test for you :)

**Comment by jlaustill** [comment]
I'd like to confirm that I renamed this file, and changed line 41 to 

`
	} else {
		var url = './scripts/filemanager.config.default.js';
	}
`

And I am no longer getting this error and everything seems to be working fine.  I'm not sure if this is the only place it needs changed or not, but stepping through the code it at least seems to be loading everything as expected now.

**Comment by jlaustill** [comment]
Also, after playing with this today and continually blowing up my jshint tests, I realized that the filemanager.config.js file isn't javascript at all, it's JSON.  How would you feel about changing the extension to match?  It will still work in .net, I've already tested it.  Plus, it keeps my ReSharper happy by matching what's in the file and it's about 300 fewer errors in my display.  The change is really simple, just rename filemanager.config.js to filemanager.config.json and filemanager.config.default.js to filemanager.config.default.json and then update lines 37, 38, and 41 to match and everything loads as expected.  

`
			var url = './scripts/filemanager.config.json';
			userconfig = 'filemanager.config.json';
		}
	} else {
		var url = './scripts/filemanager.config.default.json';
`

I will be more than happy to do the pull request if this is ok with everyone.

**Comment by simogeo** [comment]
It is, indeed, json. 
Thanks for your PR proposal but I'd rather do it since it will require few changes on the PHP connector side.

**Comment by jlaustill** [comment]
Sounds good!  I don't think it requires any changes to the mvc connector at all from what I can tell, but I will report back if it causes any issues for sure.

**Comment by simogeo** [comment]
Supposed to be online now : see b877dc3a41fe97c4db6361584c45b1aa12d28e3d 

poke : @servocoder

**Comment by servocoder** [comment]
Hey! Looks fine.
I was watching the discussion.
Thank you for keeping me up to date
