### ISSUE TITLE
API for Connectors up to date?

### ISSUE THREAD

**Issue by justingit** [simogeo/Filemanager#404]
Hello! I'm interested in perhaps giving the Perl connector some love. I'm just double-checking that the Connector API that's listed in ReadMe.md is up to date, so that I can work off of it. We're currently using a past version of Filemanager, and it works great, but I sort of fear that upgrading to a shiny new version will prove troublesome, as the current Perl connector may be out of date.

**Comment by simogeo** [comment]
> Hello! I'm interested in perhaps giving the Perl connector some love.

Very interesting 
The API doc (in *readme* file) is up-to-date ! Just go on and let me know !
(If you want I can add you as Filemanager contributor)

**Comment by justingit** [comment]
Giving this a quick run, the current implementation of the pl connector seems to be working just fine. Perhaps though there's some advanced features I'm not aware of, that haven't been implemented, or serious (or not so serious) security issues that need to be addressed? I was hoping to use the php connector as somewhat of a guide, but I'm also guessing that they've now drifted quite a bit aways from each other. 

There's certainly things that are wanting in the Perl connector - no way to test the API features finely documented is a big one. Having a test suite in the Perl connector would be super nice ;)

**Comment by simogeo** [comment]
Yes, it has changed a little ;-))

Some more methods are there ... like move, replace, edit files, and more .... There is also security fixes I guess.  
Starting from the PHP implementation to update pl connector would be fine ! And for any support I will be there to answer your questions.
