### ISSUE TITLE
Wrong version listed in scripts/filemanager.config.js.default

### ISSUE THREAD

**Issue by justingit** [simogeo/Filemanager#406]
Shouldn't, 

    "url": "https://github.com/simogeo/Filemanager",
    "version": "2.0.0-dev"

Listed as, 

    "url": "https://github.com/simogeo/Filemanager",
    "version": "2.2.0"

in, 

*scripts/filemanager.config.js.default*

in the latest release?

**Comment by simogeo** [comment]
should be ! (i know that ;-)) ....)

**Comment by simogeo** [comment]
ok ! c1e0ecaa1ac3591c0592f68bcb374cc2accb8b2a
