### ISSUE TITLE
Trying to add few additions, wondering if possible.

### ISSUE THREAD

**Issue by GonzaloCh** [simogeo/Filemanager#412]
Hey guys, so I've been working on this project for a while and have it set up. While working on this project I have came up with the idea of adding a few additional features to this wonderful program.

I have the following code and would like to implement it.
-I have developed a compiler feature that will compile C, C++ and Java on the click of a button.
-I would like to implement this on to the file manager. 

-Can I use ace editor instead of code mirror?

I also want to create a bootstrap theme in order to have mobile compatibility would this be possible as well?

**Comment by simogeo** [comment]
Hi and thanks for your interest,
For now, there is no strong plugins mechanism. You will, so, be able to implement all this by modifying files directly or by adding extra js code.

> -Can I use ace editor instead of code mirror?

There is no ability to do this by setting up options parameter

You will be able to answer all your questions by looking at the source code itself : 
https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.js

**Comment by simogeo** [comment]
> -I have developed a compiler feature that will compile C, C++ and Java on the click of a button.
> -I would like to implement this on to the file manager. 

Since, this is very specific need, this should not join the core version. If' you'd like to work on as plugin. I would be pleased to integrate it.

**Comment by GonzaloCh** [comment]
Trying to implement it with extra js code. Quick question though, when transferring to a Ubuntu Server compared to my localhost. I keep getting No Way error. This is due to it not being in Server Root i'm assuming. Would DocumentRoot be the correct place or does it have to be in Apache2 server actual server root?

**Comment by simogeo** [comment]
I always run it on Ubuntu server / Apache2 with no particular issue.
You may have a look at : https://github.com/simogeo/Filemanager/issues/414

And also : 
* https://github.com/simogeo/Filemanager/wiki/Specify-user-folder%2C-configuration-cases
* https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file

FYI, extra JS code can be passed in js configuration file : see https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.config.js.default#L143

**Comment by GonzaloCh** [comment]
Thank you so much for this wonderful project. Almost done with what I want to add. Just want to move it around. And implement some sort of terminal view.

**Comment by simogeo** [comment]
Glad you reached your goal. 
If you like the project and want to contribute, you can [share the way you did to implement extra feature](https://github.com/simogeo/Filemanager/wiki/_new) or do a [small donation](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=2M5GWH9NLNEZL).

Thanks for feedback.
