### ISSUE TITLE
How can I move the buttons around in editor view.

### ISSUE THREAD

**Issue by GonzaloCh** [simogeo/Filemanager#415]
Is it possible to move the buttons to the top of editor or to the side or anywhere and have a set length placed on the editor so there's no need for it to just increment by itself. My goal is to have something like this at the end.

Current view
![current](https://cloud.githubusercontent.com/assets/15659024/11017422/b3665302-855b-11e5-80fe-c64c5f1a4835.png)

After buttons have been moved around.

<img width="1221" alt="screen shot 2015-11-07 at 2 25 01 pm" src="https://cloud.githubusercontent.com/assets/15659024/11017413/7378905c-855b-11e5-9984-0acffbf9a1fa.png">

**Comment by simogeo** [comment]
Well, you can try to change css properties of `#toolbar` element.

If needed, just [create a new theme](https://github.com/simogeo/Filemanager/wiki/Create-your-own-theme)  based on default theme.
