### ISSUE TITLE
Feature Request: Don't cache image thumbnails

### ISSUE THREAD

**Issue by xanderdunn** [simogeo/Filemanager#417]
I have images that are generated over time, so each time I open them up in Filemanager, they'll be different.  

However, Filemanager creates a thumbnail and keeps it, so every time the image changes the thumbnail will be a stale old version.

**Comment by simogeo** [comment]
For performance reason, thumbnails are generated when file is replaced only.
An option could be to remove thumbnails. Please see the doc : 
https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file#the-options-section

set `showThumbs` to `false` or /and  `generateThumbnails` to `false` 

Another option would be to generate your thumbnails by your 3rd party app (when images are generated)

**Comment by xanderdunn** [comment]
Thanks, but I definitely want thumbnails.  I'm not interested in turning them off.  

I definitely don't want the programs that are generating these images to have to worry about also generating smaller versions and putting them into place for Filebrowser.  

A setting to disable thumbnail caching (and take on the responsibility of any performance problem) would be great.  
Also, updating the cached thumbnail when the modified date on the image changes would be an option, but that would be more difficult to implement.

**Comment by simogeo** [comment]
> A setting to disable thumbnail caching (and take on the responsibility of any performance problem) would be great.

Want to work on it ?

**Comment by xanderdunn** [comment]
It's not high enough priority for me, but perhaps it will become so later.

**Comment by simogeo** [comment]
Can you test it ? 5838ab76a1c31a0acfdbaae6dfbefc69a3457f6f

**Comment by simogeo** [comment]
Don't forget to set "cacheThumbnails": to false in your config file

**Comment by xanderdunn** [comment]
@simogeo This is awesome!  Thanks very much!  I'll try it out.
