### ISSUE TITLE
Feature Request: Follow Symlinks

### ISSUE THREAD

**Issue by xanderdunn** [simogeo/Filemanager#418]
Whenever I attempt to follow a symlink directory in Filemanager, I receive the "No way." error.  Following any regular directory in the same folder works as expected.

**Comment by simogeo** [comment]
Can you have a look on : 

* https://github.com/simogeo/Filemanager/issues/332
* https://github.com/simogeo/Filemanager/issues/386

And let us know

**Comment by simogeo** [comment]
you can enable log to see what's happening : https://github.com/simogeo/Filemanager/wiki/Enable-log-debug-in-PHP-connector

**Comment by simogeo** [comment]
any feedback ?

**Comment by xanderdunn** [comment]
@simogeo Sorry, I've moved on from this for now.  You can close this if you like and if I come back to this I can take another look at it.

**Comment by simogeo** [comment]
ok, thanks for letting me know
