### ISSUE TITLE
Doesn't support Chinese folder name

### ISSUE THREAD

**Issue by ryanlin1986** [simogeo/Filemanager#420]
In ajax call, we need use encodeURIComponent for the folder name.

**Comment by simogeo** [comment]
could you precise where exactly ?

**Comment by ryanlin1986** [comment]
$.getJSON(fileConnector + '?mode=addfolder&path=' + $('#currentpath').val() + '&name=' + foldername + '&time=' + d.getMilliseconds(), function (result)

Should be:

$.getJSON(fileConnector + '?mode=addfolder&path=' + $('#currentpath').val() + '&name=' + encodeURIComponent(foldername) + '&time=' + d.getMilliseconds(), function (result)

**Comment by simogeo** [comment]
It is done. Thanks ... check next version coming soon
