### ISSUE TITLE
How can I make text editor take whole screen?

### ISSUE THREAD

**Issue by FPC101** [simogeo/Filemanager#422]
Hello simogeo, so the page that holds the filemanager has dividers. How can I remove the dividers? or where are the dividers at in the theme file?

**Comment by simogeo** [comment]
Hi, 

Actually, you can all this in css file. I would give you the advice of creating a [new theme](https://github.com/simogeo/Filemanager/wiki/Create-your-own-theme).
Search for : `#filetree` and `#splitter .vsplitbar`.

Not sure it will work out of the box ... because widths are also set directly in js file.

See code : https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.js
([end of file](https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.js#L1990) and setDimensions() declaration.

Actually, this is also hardcoded here : https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.js#L1965  .... so it should be adapted in js file itself. 

Want to propose a fix ?

**Comment by simogeo** [comment]
At the end of the FM : 

Replace instructions by : 

```javascript
$('#splitter').splitter({
		sizeLeft: 0,
		minLeft: 0,
		minRight: 0
	});
```

and in css, to #filetree selector, add : 

```css
min-width: 0px;
width: 0px;
```

I'll make this more flexible soon !

**Comment by FPC101** [comment]
Thank you so much! Will try it right now and report back.

**Comment by FPC101** [comment]
The dividers became smaller, but it's didn't set it up to my limits.

**Comment by simogeo** [comment]
I'm not sur of your request. Do you want to be able to see a unique window, as follow ?

![size-panels-fm](https://cloud.githubusercontent.com/assets/154323/11319252/d7bc7554-9070-11e5-9cd3-2772857cc663.png)

see also : https://github.com/simogeo/Filemanager/issues/423

or do you want [this feature](https://codemirror.net/demo/fullscreen.html) ?
In that case, please wait - it is not implemented yet

**Comment by FPC101** [comment]
No what i'm trying to do is this.

I'm trying to remove the dividers on the side of this page
![screen shot 2015-11-21 at 3 38 45 pm](https://cloud.githubusercontent.com/assets/15932550/11320870/062f403e-9066-11e5-894e-e7f6581efc1f.png)

**Comment by simogeo** [comment]
Download latest from trunk, edit file, click on editor, and press F11

**Comment by FPC101** [comment]
Thank you so just to make sure. The dividers on that page are now completely customizable?

**Comment by FPC101** [comment]
Awesome addition of the f11 button action! I do have a question though, where exactly is the listener for that button located? I would love to implement some more stuff, when that button is pressed.

**Comment by FPC101** [comment]
And would still love to be able to edit dividers to my needs.

**Comment by simogeo** [comment]
> Awesome addition of the f11 button action! I do have a question though, where exactly is the listener for that button located? I would love to implement some more stuff, when that button is pressed. 

https://github.com/simogeo/Filemanager/blob/master/scripts/CodeMirror/dynamic-mode.js#L53

> And would still love to be able to edit dividers to my needs.

But there is no dividers in edit mode !?

**Comment by FPC101** [comment]
OH! Well is there a way to just move the editor around? That's really my goal. I want to move it more to the left.

**Comment by FPC101** [comment]
This is my goal. 
From
<img width="1194" alt="screen shot 2015-11-25 at 9 13 12 pm" src="https://cloud.githubusercontent.com/assets/15932550/11414962/7056a7bc-93b9-11e5-86b2-13cb62966ea8.png">

To

<img width="1223" alt="screen shot 2015-11-25 at 9 11 47 pm" src="https://cloud.githubusercontent.com/assets/15932550/11414967/7ec736cc-93b9-11e5-8720-ac351091d675.png">

**Comment by simogeo** [comment]
No worries, in your theme main css file, add :  


```css

.CodeMirror-fullscreen {
  position: fixed;
  top: 2em; left: 0; right: 0; bottom: 0 ! important;
  height: auto;

}

div.CodeMirror.CodeMirror-fullscreen {
width:60% ! important;
margin:0;
z-index: 9;
 }
```

Just play with css and do not forget `important`

**Comment by FPC101** [comment]
Thank you! Would the same be possible without fullscreen?

**Comment by simogeo** [comment]
Use css : 

```css
div.CodeMirror {
// your properties 
}
```
