### ISSUE TITLE
should use url encode for path of getinfo ajax request

### ISSUE THREAD

**Issue by ryanlin1986** [simogeo/Filemanager#429]
It's in setMenus function, please look at the following code:

$.getJSON(fileConnector + '?mode=getinfo&path=' + path + '&config=' + userconfig + '&time=' + d.getMilliseconds(), function (data) {

should be changed to:
$.getJSON(fileConnector + '?mode=getinfo&path=' + encodeURIComponent(path) + '&config=' + userconfig + '&time=' + d.getMilliseconds(), function (data) {

**Comment by ryanlin1986** [comment]
Also, the parameters of rename ajax call should do this too.

**Comment by simogeo** [comment]
thanks. See latest commit
