### ISSUE TITLE
Right click has no effect on Firefox 

### ISSUE THREAD

**Issue by kursusHC** [simogeo/Filemanager#430]
Hi and thanks for your nice software. 

Right click on files and folders has no effect on Firefox 42. 

Works fine with Chrome. 

Thank you

**Comment by simogeo** [comment]
Tested with success on http://fm.linea21.com/ with FF42 under Ubuntu.

Check your local settings

**Comment by kursusHC** [comment]
Ok it appears that the extension All-in-One gestures prevents right click on this particular case. Will try to investigate as it doesn't happen with others sites with JS rick click menus.

**Comment by simogeo** [comment]
Ok, Thanks for letting me know !
