### ISSUE TITLE
Json error 500 on Godaddy

### ISSUE THREAD

**Issue by tenq** [simogeo/Filemanager#431]
Hi, I use classic version of filemanager, but, when migrate a site to Godaddy windows (with plesk), connector/asp/filemanager.asp not work.

It´s possible to solve this?

I´m tried to solve with web.config, but no success:

````
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
	<validation validateIntegratedModeConfiguration="false" />
    	<modules runAllManagedModulesForAllRequests="true" />
	<staticContent>
            <remove fileExtension=".json" />
            <mimeMap fileExtension=".json" mimeType="application/json" />
        </staticContent>
    </system.webServer>
</configuration>
```
thanks for help!!!

**Comment by simogeo** [comment]
No idea on my part .... asp connector has no maintainer

**Comment by tenq** [comment]
Ok, @simogeo , thanks... I'll try another way ;-(

**Comment by simogeo** [comment]
You can use mvc connector ...

**Comment by tenq** [comment]
thanks @simogeo, I will try...
