### ISSUE TITLE
Backdrop opening is not animated

### ISSUE THREAD

**Issue by kursusHC** [simogeo/Filemanager#432]
Hello and thanks for this nice gallery. 

I noticed that the fade animation on the backdrop opening is not applied whatever the delay set with 'backdropDuration'. 

According to this [SO answer](http://stackoverflow.com/a/20938849) some (most) bowsers skip the animation for efficiency purpose. The solution linked solves the problem. 

Thanks

**Comment by simogeo** [comment]
Can you precise which backdrop opening  ? even point out the code 

(And if you like to provide a PR, you will be very welcome)

**Comment by kursusHC** [comment]
Sorry I posted this in the wrong repo, my mistake !
