### ISSUE TITLE
Show only folder in left tree panel

### ISSUE THREAD

**Issue by wabsa** [simogeo/Filemanager#433]
Is there an option to filter the left tree panel that only folders will show in the list?
Thanks

**Comment by simogeo** [comment]
Set listFiles to `false`

https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.config.js.default#L17

See the [doc](https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file) : 

> listFiles Default value true. Display files in right column (filetree). If set to false, will display only folders. Can take value true or false.
