### ISSUE TITLE
hi !   How to move files using java connector？？

### ISSUE THREAD

**Issue by ExtremeYu** [simogeo/Filemanager#439]
i can't find move button can you help me??

**Comment by ExtremeYu** [comment]
![qq 20160109150553](https://cloud.githubusercontent.com/assets/16620268/12214948/81ca1f8c-b6e2-11e5-88ac-4de323a273e9.jpg)
![qq 20160109150622](https://cloud.githubusercontent.com/assets/16620268/12214950/9280a044-b6e2-11e5-864d-cf976a60ec65.jpg)

**Comment by ExtremeYu** [comment]
in fact there is no move selection in right  menu ,can not move files amon drag also

**Comment by simogeo** [comment]
To use `move` capability, add it into [config file](https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.config.js.default#L27). But i'm not sure it is implemented in java connector - you probably use [that one]Hi guess you uses this connector : https://github.com/th-schwarz/C5Connector.Java) ?
( drag'n drop is not implemented)

**Comment by ExtremeYu** [comment]
i user this https://github.com/th-schwarz/C5Connector.Java/releases/tag/c5connector-java-0.10 connector

**Comment by simogeo** [comment]
And have try adding `move` to capabilities  array in config file ?

**Comment by ExtremeYu** [comment]
yes i tried ， but not very convenient
![qq 20160110001128](https://cloud.githubusercontent.com/assets/16620268/12217016/bcec2e9c-b72e-11e5-87b3-8d5c2181ca5e.jpg)

**Comment by simogeo** [comment]
well, that the way it works right now
