### ISSUE TITLE
try upload video with more than 100mb

### ISSUE THREAD

**Issue by MRCardoso** [simogeo/Filemanager#443]
i am tried use your library Filemanager, but when i try an upload video with  more than 100mb, the request to 'connectors/php/filemanager.php' return status http failed

i am using PHP language

already adjusted the upload_max_filesize and post_max_size to 200MB but without success

**Comment by simogeo** [comment]
Did you set `fileSizeLimit` in [config file](https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file#the-upload-section) ?

And what is the exact status error code ? https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

Any explicit error message  from Firebug or developer console ?

You can also enable and have a look on Filemanager log file : https://github.com/simogeo/Filemanager/wiki/Enable-log-debug-in-PHP-connector

Also, see Server errors log !

And let us know. It could interest other users !

**Comment by simogeo** [comment]
By the way, upload rely on dropzone which FAQ says : 

> There is a maxFilesize option in Dropzone which defaults to 256 (MB). Increase this to upload files bigger than that. If your files upload fine but aren't stored on the server, then it's due to your server configuration. Most servers limit the file upload size as well. Please check with the appropriate documentation.

source : https://github.com/enyo/dropzone/wiki/FAQ#why-are-large-files-not-uploading

**Comment by MRCardoso** [comment]
already change de fileSizeLimit, he config file is this 'scripts/filemanager.config.js' correct?
the status http is "(failed)", no has number

**Comment by simogeo** [comment]
check or copy / paste phpinfo() output

**Comment by MRCardoso** [comment]
what i need search?

this informations, is like this in phpinfo():

upload_max_filesize	200MB
post_max_size       200MB

**Comment by MRCardoso** [comment]
the request already return with status 'failed', before read the file 'connectors/php/filemanager.php'

**Comment by jagernicolas** [comment]
I have similar problem, I tried to send a pdf of 3MB and I got a msg that I can only upload 2MB per file, I have change the fileSizeLimit to 16Mb same problem, the upload pannel shows that I can upload 16Mb though, but still get the message about 2MB max

**Comment by MRCardoso** [comment]
Hi, 
a colleague of my team solved the problem, was limiting in the nginx "client_max_body_size"

thanks.

**Comment by Krishnachaitanya4167** [comment]
@jagernicolas  @simogeo  hey i am also also having the same problem of upload size limited to 2mb ,how to solve this?

**Comment by simogeo** [comment]
hi @Krishnachaitanya4167 : see my message above : https://github.com/simogeo/Filemanager/issues/443#issuecomment-172888353

**Comment by psolom** [comment]
@Krishnachaitanya4167 you do use Windows OS isn't you?
