### ISSUE TITLE
filemanager.min.js isn't identical with filemanager.js?

### ISSUE THREAD

**Issue by WulleBulle** [simogeo/Filemanager#447]
Hello,

I just figured that the filemanager.min.js is completely different to the filemanager.js in the zip package I've downloaded. Why is that?
Is there any uncompressed version of filemanager.min.js?

Thanks in advance.

**Comment by simogeo** [comment]
The uncompressed version of `filemanager.min.js` is `filemanager.js` !

**Comment by WulleBulle** [comment]
Right, thank you very much and my apologize for bothering.
I love this gem of a software.
