### ISSUE TITLE
Symlinks (Windows Server 2012 IIS)

### ISSUE THREAD

**Issue by mcmlxxix** [simogeo/Filemanager#448]
I'm looking to base users in a per-user directory on a mapped network drive (a file server, specifically). 

I've found that virtual directories in IIS are ignored (which is fine, really), but also symlinked directories appear as locked and produce the message "No way", and if I specify the symlink directory as the fileRoot, I received the message "System permissions do not allow you to perform this action"

Is it possible to support and use symlinks with this? I'd like to use this as an alternative to my FTP site to allow people who are not comfortable with FTP to work with their files easily. 

It's entirely possible I've overlooked something simple, but I don't really know where to begin troubleshooting this problem.

**Comment by mcmlxxix** [comment]
I have referenced the closed issues #332 and #306, and haven't seen anything about it being tested under Windows. Here is the output from my logfile:

[05/02/2016 04:20:04]#173.166.77.109#Filemanager::enableLog - Log enabled (in c:/inetpub/davroot/log.txt file)
[05/02/2016 04:20:04]#173.166.77.109#Filemanager::__construct $this->root value C:\inetpub\davroot\
[05/02/2016 04:20:04]#173.166.77.109#Filemanager::__construct $this->path_to_files C:\inetpub\davroot\userfiles/
[05/02/2016 04:20:04]#173.166.77.109#Filemanager::__construct $this->doc_root value C:\inetpub\davroot
[05/02/2016 04:20:04]#173.166.77.109#Filemanager::__construct $this->separator value userfiles
[05/02/2016 04:20:04]#173.166.77.109#substr path_to_files : z:\users\Lucy\
[05/02/2016 04:20:04]#173.166.77.109#path_to_files : C:\inetpub\davroot\userfiles\
[05/02/2016 04:20:04]#173.166.77.109#Filemanager::error - error message : No way.

**Comment by simogeo** [comment]
in php file you can replace [line ](https://github.com/simogeo/Filemanager/blob/master/connectors/php/filemanager.class.php#L1202) by : 

```php
	$this->__log('substr path_to_files : ' . substr(realpath($path) . DIRECTORY_SEPARATOR, 0, strlen(realpath($this->path_to_files))));
```

and post the log again

**Comment by mcmlxxix** [comment]
Appears to be the same result - for both symlink mappings.

"z:\users\lucy\"

[07/02/2016 02:43:11]#192.168.1.65#Filemanager::enableLog - Log enabled (in c:/inetpub/davroot/log.txt file)
[07/02/2016 02:43:11]#192.168.1.65#Filemanager::__construct $this->root value C:\inetpub\davroot\
[07/02/2016 02:43:11]#192.168.1.65#Filemanager::__construct $this->path_to_files C:\inetpub\davroot\userfiles/
[07/02/2016 02:43:11]#192.168.1.65#Filemanager::__construct $this->doc_root value C:\inetpub\davroot
Filemanager::__construct $this->separator value userfiles
substr path_to_files : z:\users\lucy\
path_to_files : C:\inetpub\davroot\userfiles\
Filemanager::error - error message : No way.

"\\server1\fileserver\users\lucy\"

Filemanager::enableLog - Log enabled (in c:/inetpub/davroot/log.txt file)
Filemanager::__construct $this->root value C:\inetpub\davroot\
Filemanager::__construct $this->path_to_files C:\inetpub\davroot\userfiles/
Filemanager::__construct $this->doc_root value C:\inetpub\davroot
Filemanager::__construct $this->separator value userfiles
substr path_to_files : C:\inetpub\davroot\userfiles
path_to_files : C:\inetpub\davroot\userfiles\
Filemanager::error - error message : Unable to open the directory /userfiles/Lucy/.
Filemanager::error - error message : Unable to open the directory /userfiles/Lucy/.

**Comment by simogeo** [comment]
I will provide a patch for "\\server1\fileserver\users\lucy\" syntax !

**Comment by mcmlxxix** [comment]
Thank you!

**Comment by simogeo** [comment]
Try with the last version. See commit 67417e84e54084f6532e52d160bd80dc18e48109

**Comment by mcmlxxix** [comment]
The changes seem to have made it so I can't list even the rootPath, which was not a problem before. 
**
Current folder: /
No way.
**
It's probably worth noting that before you made this change, I had modified filemanager.class.php to just return true from is_valid_path() without bothering to validate anything, which eliminated the "No way." errors, but opened the door for a few more issues. 

1. even without validating path, it seems PHP still has a problem accessing UNC paths in windows. It spits out a system permissions error, but the permissions are fine.

2. UNC paths that are mapped to a drive letter in Windows are usable, but you have to set the permissions for your website (from IIS: website -> basic settings -> connect as) to a user account that has access to the network share. I have created a user specifically for this purpose and given it access, and it works, if I bypass is_valid_path()

**Comment by simogeo** [comment]
@mcmlxxix : I'm sorry. I'll revert back the commit. Unfortunately, I can't help you anymore. Don't have much time and have no IIS server.
You should probably investigate the web regarding PHP  and UNC paths in windows.

And if you find something, pleas propose a fix.

**Comment by mcmlxxix** [comment]
I edited my previous comment to correct a mistake. I had it backwards. The UNC symlink paths work, as long as the permissions are correct, but mapped letter drives do not (regardless of permissions). I will see if I can find a patch that works to make is_valid_dir() work with IIS and PHP.

**Comment by mcmlxxix** [comment]
Found a solution that has worked for me:
```
  $patt = array('/\\\\+/','/\/+/');
  $repl = array('\\\\','/');

  $substrpath = substr(realpath($path) . DIRECTORY_SEPARATOR, 0, strlen($this->path_to_files)) . DIRECTORY_SEPARATOR;
  $substrpath = preg_replace($patt,$repl,$substrpath); // removing double slash

  $rpath = realpath($this->path_to_files)  . DIRECTORY_SEPARATOR;
  $rpath = preg_replace($patt,$repl,$rpath); // removing double slash
	
  $this->__log('substr path : ' . $substrpath);
  $this->__log('real path : ' . $rpath);
	
  return ($substrpath == $rpath);
```
Because I am on windows, I cannot test the functionality under other environments, but I'm fairly certain that it will work.

**Comment by mcmlxxix** [comment]
Poke @simogeo  - above is my proposed fix..  if it works, I'd consider this case closed..

Thanks for taking the time to look into this with me..

**Comment by simogeo** [comment]
I'll have a look on that ! Thanks to you for investigating.

**Comment by simogeo** [comment]
I pushed your fix to the main repo ! thanks again.
