### ISSUE TITLE
pdf reader and audio player not working om my server

### ISSUE THREAD

**Issue by jagernicolas** [simogeo/Filemanager#449]
Hi,
the pdf reader doesn't works 
the audio player doesn't works
I haven't video on the server, the video player wasn't tested

I dont know if I missed something at the installation/configuration. When I go at http://fm.linea21.com/, the music player and the pdf reader work.

**Comment by simogeo** [comment]
You probably missed something indeed ...

Use firebug or developer pane to see what's happening there

**Comment by jagernicolas** [comment]
ok, I never debugged anything on internet, firefox returns :

HEAD 
XHR 
http://192.168.2.18/userfiles/My_folder/img001.pdf [HTTP/1.1 500 Internal Server Error 13ms]
GET 
XHR 
http://192.168.2.18/userfiles/My_folder/img001.pdf [HTTP/1.1 500 Internal Server Error 4ms]
GET 
http://192.168.2.18/userfiles/My_folder/Yamaha-TG100-Whistle-C5.wav [HTTP/1.1 500 Internal Server Error 15ms]
HTTP load failed with status 500. Load of media resource http://192.168.2.18/userfiles/My_folder/Yamaha-TG100-Whistle-C5.wav failed. 192.168.2.18
HEAD 
XHR 
http://192.168.2.18/userfiles/My_folder/img001.pdf [HTTP/1.1 500 Internal Server Error 4ms]
Found plugin by file extension from path: pdf index.html:73:76
GET 
XHR 
http://192.168.2.18/userfiles/My_folder/img001.pdf [HTTP/1.1 500 Internal Server Error 5ms]
UnexpectedResponseException: Unexpected server response (500) while retrieving PDF "http://192.168.2.18/userfiles/My_folder/img001.pdf".

**Comment by simogeo** [comment]
and what's happing if you directly load http://192.168.2.18/userfiles/My_folder/img001.pdf  in your browser ?

where is your file located ?

**Comment by jagernicolas** [comment]
I got :
Server error!

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a CGI script.

If you think this is a server error, please contact the webmaster.
Error 500
192.168.2.18
Apache/2.4.17 (Unix) PHP/5.6.16 

my file is located in : /srv/http/userfiles/My_Folder

**Comment by jagernicolas** [comment]
I remove .htaccess from /srv/http/userfiles/

I use in /etc/httpd/conf/httpd.conf : 
 <Directory />
 AllowOverride none
 Require all denied
 </Directory>

everything works!
