### ISSUE TITLE
Files are uploaded but not showing in filemanger

### ISSUE THREAD

**Issue by amirhj** [simogeo/Filemanager#452]
My config is the default one and I have integrated it with ckeditor.
There is no problem in uploading. I checked the files in userfile directory, but Its not able to show files in file manager, it shows folder but not files

**Comment by simogeo** [comment]
are you sure `listFiles` is set to `true` in your config file ?
https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.config.js.default#L17
