### ISSUE TITLE
Possible to select file without getting info?

### ISSUE THREAD

**Issue by kabeda** [simogeo/Filemanager#455]
Hi,
Like in the title, I need to select the file directly from the list without entering in the preview mode then click on select. Is it possible.
Thanks,

**Comment by simogeo** [comment]
Pleas, be more precise

**Comment by kabeda** [comment]
Hi,
When I access to filemanager, I got the grid or the list. If I click on a file, I had a preview of the file and the buttons of select, replace... If fact, I don't want to have this preview, just after a click on the list or the grid the file will be selected and the file name (path) returned to from where I called filemanager.

Thanks,

**Comment by simogeo** [comment]
Not possible yet but it will come soon. I let you know when I push the feature.

**Comment by simogeo** [comment]
Done. Download the latest archive and don't forget to set `quickSelect` option in config file to true.
