### ISSUE TITLE
New Folder Name does not  support Chinese charset

### ISSUE THREAD

**Issue by GitOffice** [simogeo/Filemanager#458]
please fix it ,3Q

**Comment by servocoder** [comment]
New folder name supposed to be transliterated.
But I am aware that there is a problem with transliteration of non ASCII languages in the current version. You could faced the same problem for cyrillic chars as well. Now I am working on the new version of FM at my fork and I partially have fixed this bug, but it is not stable enough yet. I am going to release stable code on the next week. But be aware that my fork has many changes in the core and some of them are backward incompatible. I'll let you know when it's ready. You could also watch #456 issue to stay informed of new features in my fork.

**Comment by simogeo** [comment]
@GitOffice : indeed,there was a discussion on that issue some time ago. See : #244

but have you tried with `"chars_only_latin": false` option. See https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.config.default.json#L20
