### ISSUE TITLE
Problem displaying files in Filemanager

### ISSUE THREAD

**Issue by mpparent** [simogeo/Filemanager#460]
I had a problem with Filemanager, it stopped working properly this week. Hasn't changed nothing prior to that. I tried to repair by reinstalling the new version. Same problem.
The problem is that the Filemanager is not displaying files. I can upload though! But the wheel is still spinning and no files are showed. 

Is there a solution?

**Comment by simogeo** [comment]
check with developer console or Firebug ..... 

Also, maybe have a look to your folder permissions !?

**Comment by mpparent** [comment]
Hi,
What are suppose to be the permissions? I tried to found those and didn't find theme in documentation. But I can upload. That the strange part. So I know the folder is the right one. 



In the console there is no error. Only a css warning for a unexpected token in the filemanager token. 



Merci,

 

WDI ce n'est pas que des sites web, des noms de domaine et de l'hébergement! C'est aussi un service informatique pour le dépannage, l'installation de réseaux, d'ordinateurs et autres équipements électroniques et de logiciels. Nous nous occupons aussi de l'acquisition de vos produits informatiques. N'hésitez pas à nous contacter!

 




Marc Philippe Parent ing. jr, M.Sc
WebDev Intégration Ltée
http://www.wdi.qc.ca
(418)655-5607

================================
Avis relatif à la confidentialité :
Ce message contient des renseignements qui peuvent être confidentiels ou protégés. Il s'adresse au destinataire prévu ou à une personne autorisée à le recevoir en son nom. Si vous l'avez reçu par erreur, nous vous prions d'en informer l'auteur dans les meilleurs délais, de ne pas divulguer son contenu et de le supprimer de votre système.
========================= 
Notice of Confidentiality :
This message contains information that may be confidential or privileged.  It is intended for the exclusive use of the addressee or any person entitled to receive it.  If you received this message in error,  please inform the author as soon as possible, do not disclose its contents and delete it from your system.

**Comment by simogeo** [comment]
> I had a problem with Filemanager, it stopped working properly this week.
If you did not make any changes to the FM, it can be a server or php configuration changes, no !?

**Comment by mpparent** [comment]
Hi,
Maybe. Will i ask you, i ask them too. They did not tell me that they changed something. 

I tought it was a upgrade problem. So I installes the new version of filemanager, but i have the same problem. 

What are supposes to be the permissions?





Merci,

 

WDI ce n'est pas que des sites web, des noms de domaine et de l'hébergement! C'est aussi un service informatique pour le dépannage, l'installation de réseaux, d'ordinateurs et autres équipements électroniques et de logiciels. Nous nous occupons aussi de l'acquisition de vos produits informatiques. N'hésitez pas à nous contacter!

 




Marc Philippe Parent ing. jr, M.Sc
WebDev Intégration Ltée
http://www.wdi.qc.ca
(418)655-5607

================================
Avis relatif à la confidentialité :
Ce message contient des renseignements qui peuvent être confidentiels ou protégés. Il s'adresse au destinataire prévu ou à une personne autorisée à le recevoir en son nom. Si vous l'avez reçu par erreur, nous vous prions d'en informer l'auteur dans les meilleurs délais, de ne pas divulguer son contenu et de le supprimer de votre système.
========================= 
Notice of Confidentiality :
This message contains information that may be confidential or privileged.  It is intended for the exclusive use of the addressee or any person entitled to receive it.  If you received this message in error,  please inform the author as soon as possible, do not disclose its contents and delete it from your system.

**Comment by simogeo** [comment]
I'm talking about folder permissions (setting them to 0777) will ensure the application could use it but may cause some security issue. By the way, if you're able to upload file, so I guess it is ok. Have you checked your uploaded file is physically located in the desired folder ?

> In the console there is no error. Only a css warning for a unexpected token in the filemanager token.
Have a look on the newtork panel to see what is returned by the application (response)

**Comment by mpparent** [comment]
Hi,
Folder are 755, files 644. 

Yes, the uploaded file is in the right place. It's why it is strange

I remove the auth security for tests. You can see what's happening on http://www.terratours.ca/gestion/liberary/Filemanager/




Merci,

 

WDI ce n'est pas que des sites web, des noms de domaine et de l'hébergement! C'est aussi un service informatique pour le dépannage, l'installation de réseaux, d'ordinateurs et autres équipements électroniques et de logiciels. Nous nous occupons aussi de l'acquisition de vos produits informatiques. N'hésitez pas à nous contacter!

 




Marc Philippe Parent ing. jr, M.Sc
WebDev Intégration Ltée
http://www.wdi.qc.ca
(418)655-5607

================================
Avis relatif à la confidentialité :
Ce message contient des renseignements qui peuvent être confidentiels ou protégés. Il s'adresse au destinataire prévu ou à une personne autorisée à le recevoir en son nom. Si vous l'avez reçu par erreur, nous vous prions d'en informer l'auteur dans les meilleurs délais, de ne pas divulguer son contenu et de le supprimer de votre système.
========================= 
Notice of Confidentiality :
This message contains information that may be confidential or privileged.  It is intended for the exclusive use of the addressee or any person entitled to receive it.  If you received this message in error,  please inform the author as soon as possible, do not disclose its contents and delete it from your system.

**Comment by simogeo** [comment]
Not able to access www.terratours.ca

**Comment by mpparent** [comment]
Mmmm
I do. 



So you don't have access to this neather?

http://www.terratours.ca/gestion/liberary/Filemanager/


Merci,

 

WDI ce n'est pas que des sites web, des noms de domaine et de l'hébergement! C'est aussi un service informatique pour le dépannage, l'installation de réseaux, d'ordinateurs et autres équipements électroniques et de logiciels. Nous nous occupons aussi de l'acquisition de vos produits informatiques. N'hésitez pas à nous contacter!

 




Marc Philippe Parent ing. jr, M.Sc
WebDev Intégration Ltée
http://www.wdi.qc.ca
(418)655-5607

================================
Avis relatif à la confidentialité :
Ce message contient des renseignements qui peuvent être confidentiels ou protégés. Il s'adresse au destinataire prévu ou à une personne autorisée à le recevoir en son nom. Si vous l'avez reçu par erreur, nous vous prions d'en informer l'auteur dans les meilleurs délais, de ne pas divulguer son contenu et de le supprimer de votre système.
========================= 
Notice of Confidentiality :
This message contains information that may be confidential or privileged.  It is intended for the exclusive use of the addressee or any person entitled to receive it.  If you received this message in error,  please inform the author as soon as possible, do not disclose its contents and delete it from your system.

**Comment by simogeo** [comment]
not at all ....

**Comment by mpparent** [comment]
Ok

Where are you? Just to know why you can't see it but we can. 

But as you can see in the image, the filemanager is only not showing anything. Could it be a problem creating thumbails?







Merci,

 

WDI ce n'est pas que des sites web, des noms de domaine et de l'hébergement! C'est aussi un service informatique pour le dépannage, l'installation de réseaux, d'ordinateurs et autres équipements électroniques et de logiciels. Nous nous occupons aussi de l'acquisition de vos produits informatiques. N'hésitez pas à nous contacter!

 




Marc Philippe Parent ing. jr, M.Sc
WebDev Intégration Ltée
http://www.wdi.qc.ca
(418)655-5607

================================
Avis relatif à la confidentialité :
Ce message contient des renseignements qui peuvent être confidentiels ou protégés. Il s'adresse au destinataire prévu ou à une personne autorisée à le recevoir en son nom. Si vous l'avez reçu par erreur, nous vous prions d'en informer l'auteur dans les meilleurs délais, de ne pas divulguer son contenu et de le supprimer de votre système.
========================= 
Notice of Confidentiality :
This message contains information that may be confidential or privileged.  It is intended for the exclusive use of the addressee or any person entitled to receive it.  If you received this message in error,  please inform the author as soon as possible, do not disclose its contents and delete it from your system.

**Comment by simogeo** [comment]
France
don't see images neither. If you want to share images, do it from github website itself.

**Comment by mpparent** [comment]
Donc vous parlez français?





Merci,

 

WDI ce n'est pas que des sites web, des noms de domaine et de l'hébergement! C'est aussi un service informatique pour le dépannage, l'installation de réseaux, d'ordinateurs et autres équipements électroniques et de logiciels. Nous nous occupons aussi de l'acquisition de vos produits informatiques. N'hésitez pas à nous contacter!

 




Marc Philippe Parent ing. jr, M.Sc
WebDev Intégration Ltée
http://www.wdi.qc.ca
(418)655-5607

================================
Avis relatif à la confidentialité :
Ce message contient des renseignements qui peuvent être confidentiels ou protégés. Il s'adresse au destinataire prévu ou à une personne autorisée à le recevoir en son nom. Si vous l'avez reçu par erreur, nous vous prions d'en informer l'auteur dans les meilleurs délais, de ne pas divulguer son contenu et de le supprimer de votre système.
========================= 
Notice of Confidentiality :
This message contains information that may be confidential or privileged.  It is intended for the exclusive use of the addressee or any person entitled to receive it.  If you received this message in error,  please inform the author as soon as possible, do not disclose its contents and delete it from your system.

**Comment by mpparent** [comment]
![image](https://cloud.githubusercontent.com/assets/12661703/13463072/8a93ec8e-e058-11e5-9b9d-672e5a1daf86.png)

**Comment by servocoder** [comment]
Hi there, I am from Ukraine but unable to open your domain too. I firmly believe that you have problem with your server and the issue doesn't related to filemanager. You should find some qualified specialist to solve problem with your server.

**Comment by simogeo** [comment]
> I firmly believe that you have problem with your server and the issue doesn't related to filemanager. 

+1

**Comment by mpparent** [comment]
Ooook
I found here https://asm.ca.com/en/ping.php that the site is not accessible everywhere. But it seems to be another problem. But both seems to be server related. I'll be back if not.  

Thanks.

**Comment by mpparent** [comment]
The reason why you didn't have the access to our server is that you ip sub net is/was blocked by security. It wasn't a trouble.

**Comment by simogeo** [comment]
`
Warning: date() [function.date]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/New_York' for 'EST/-5.0/no DST' instead in /home/terratou/terratours.ca/html/gestion/liberary/Filemanager/connectors/php/filemanager.class.php on line 1502`

http://www.terratours.ca/gestion/liberary/Filemanager/connectors/php/filemanager.php?path=%2Ffiles_perso%2Fimages%2F&config=filemanager.config.json&mode=getfolder&showThumbs=true&time=247

PHP configuration issue. To fix it : 
* http://stackoverflow.com/questions/16765158/date-it-is-not-safe-to-rely-on-the-systems-timezone-settings
* http://stackoverflow.com/questions/5535514/how-to-fix-warning-from-date-in-php
* disable warnigs
