### ISSUE TITLE
.net mvc can't get folder list

### ISSUE THREAD

**Issue by kkman021** [simogeo/Filemanager#461]
I have try to install on a .net mvc project.

And Step by Step:

- Changed filemanager.config.json 
  lang changed to "mvc".

- Setting FilemanagerController.cs 

- register area in Global.asax

When i view this url in browser:
/Scripts/Filemanager/index.html?CKEditor=InfoContent&CKEditorFuncNum=2&langCode=zh

I can't see the folder info.
Using fiddler i find 404 error return by IIS .

Scripts/Filemanager/connectors/mvc/filemanager.mvc?path=%2FAdmin%2FScripts%2FFilemanager%2Fuserfiles%2F&config=filemanager.config.json&mode=getfolder&showThumbs=true&time=297

Is there any tips?

**Comment by simogeo** [comment]
poke @hammond13

**Comment by spill50** [comment]
I had a few issues getting it to work with mvc. I'm running IIS Express while debugging in Visual Studio.

I found it had a problem with the filemanager.mvc in the url and thinks it's looking for a file with the .mvc extension.

I changed line **123** in **filemanager.js** to 

`var fileConnector = config.options.fileConnector || 'connectors/' + config.options.lang + '/filemanager';`

Then in **FileManagerAreaRegistration.cs** I changed the route to the following:

```
context.MapRoute(
    "FileManager_default",
    "FileManager/connectors/mvc/filemanager",
    new { controller = "FileManager", action = "Index" },
    new string[] { "intouch.Areas.FileManager.Controllers" }
);
```

After that all seemed to work.

**Comment by Lienfa** [comment]
otherwise, you can add the option in `filemanager.config.json`:
```
{
  "options": {
    "fileConnector": "/Scripts/Filemanager/connectors/mvc/filemanager"
  }
}
```

then same as @spill50 change the route in `FileManagerAreaRegistration.cs`

**Comment by kkman021** [comment]
the two way all find solve my problem.
finally i choses @Lienfa solution,because if ond day filemanage.js update. i don't need to change again.

thanks for all apply.
I post a example on github,and try to step by step in chinese traditional.
Hope if there has the same issue, can solve problem.
[FileManagerMvcDemo](https://github.com/kkman021/FileManagerMvcDemo)

Tanks again @simogeo  @spill50  @Lienfa
