### ISSUE TITLE
Context Menu not working as expected in Chrome

### ISSUE THREAD

**Issue by spill50** [simogeo/Filemanager#462]
Google Chrome Version: 48.0.2564.116 m

When right clicking on a file, no context menu is displayed.

When right clicking on a folder, no context menu is displayed. If you then immediately left click on the folder, the details view is displayed and the context menu shows.

I do not see this issue in Firefox, Edge, IE11 only Chrome.

Any thoughts?

**Comment by servocoder** [comment]
I use the same version of Chrome and don't have the issue you have described. Are you able to reproduce it on the demo page http://fm.linea21.com/ ? Also check your browser's console for errors.

**Comment by spill50** [comment]
Strange, yes it has the same behavior on the demo page as well. Only thing I see in the console is

```
jquery-1.11.3.min.js:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
filemanager.min.js:74 Total execution time : 3 ms
```

**Comment by servocoder** [comment]
Ok, inform of the result, please.
Some thoughts about your problem:
1) Check if you have another jquery plugin script loaded on the page.
2) Also try to switch off some Chrome extensions, some can cause conflicts.

**Comment by spill50** [comment]
Ok thanks for your suggestions. I went ahead and disabled all Chrome extensions and this resolved the problem. When I have a bit more time I will enable one by one to see what the conflicting extension is and report back.

**Comment by servocoder** [comment]
Great! Your report could help others.
