### ISSUE TITLE
I can upload files but I can't see files and folder

### ISSUE THREAD

**Issue by SlitYahoo** [simogeo/Filemanager#464]
Hi. I installed and connected your file manager with Ckeditor. That works well; when I what to browse images, file manager opens on a click of a button Browse, but the problem is that file manager never stops loading when opened. I can't see files or folders. I can however upload images, but when I upload images, your file manager doesn't show them.

**Comment by simogeo** [comment]
Have a look on following issue : https://github.com/simogeo/Filemanager/issues/460

**Comment by SlitYahoo** [comment]
I have localhost web site that uses Xampp server on Windows. My root folder is on Dropbox. Maybe that is an issue.

**Comment by simogeo** [comment]
> My root folder is on Dropbox. Maybe that is an issue. 

Should be ! ;-)) Start deploying FM on server root folder which is easy ... then do your own tests - maybe using virtualhost !?

**Comment by SlitYahoo** [comment]
I put my project in htdocs in Xampp folder in c:\xampp. And I still have the same problem...

**Comment by simogeo** [comment]
Use the developer console to see what's happening :

https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

 https://www.google.fr/search?q=developer+console+network+pane&client=ubuntu&hs=kDa&channel=fs&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjauIvc4qnLAhUEShQKHWYbBQIQ_AUIBygB&biw=1865&bih=897

**Comment by SlitYahoo** [comment]
I have error [that is red/purple square] and 404 for this file http://localhost/knjiznica_php/CMS%20SYSTEM/Filemanager/scripts/filemanager.config.default.json?_=1457208006318

**Comment by SlitYahoo** [comment]
This confused me: "Make a copy of the default configuration file ("filemanager.config.default.json" located in the scripts directory), removing the '.default' from the end of the filename, and edit the options according to the following wiki page". I removed default in .json not on the end. Now I put it back and now it WORKS :-)
