### ISSUE TITLE
Enable/disable Upload and Add

### ISSUE THREAD

**Issue by JosHuybrighs** [simogeo/Filemanager#466]
Great software, but I don't seem to find any possibility to disable/hide the Upload and Add button (on the top bar) when the user isn't entitled to modify something.
So what I am missing is something like a 'upload' and 'add' capability in the 'Capabilities' object for 'getfolder' and 'getinfo'. And of course software support for this.

Best regards,
Jos

**Comment by simogeo** [comment]
you can set `browseOnly` to `true` in config file.

(not sure mvc conn is really up-to-date by the way)
