### ISSUE TITLE
Loading filemanager into a div using ajax

### ISSUE THREAD

**Issue by WulleBulle** [simogeo/Filemanager#469]
Hello,

this is an user issue or help request. 
I try to load the filemanager into a div using jquery ajax(). The url is ok and the file

i.e.: /dir/somesub/filemanager/index.html?field_name=inputname&type=image

gets pulled by jquery but I'm getting lots of 404s because the css and script paths in index.html are relative to the template I am running the ajax script.

How can I load the filemanager into the div correctly?
Hope this was clear.

thank you in advance.

Regards

**Comment by WulleBulle** [comment]
Solved it creating an iframe with jQuery and using the filemanagers URl as src. Although I would be very interested into how it could work in the ajax way.
I think I have to change the path of the config file in filemanager.min.js to force it to use a complete custom config file path.
Maybe you could efford some time to explain. Otherwise please close this post. Thank you.

**Comment by simogeo** [comment]
https://github.com/simogeo/Filemanager/wiki/How-to-use-the-filemanager-with-colorbox
