### ISSUE TITLE
Adding buttons to filemanager

### ISSUE THREAD

**Issue by SlitYahoo** [simogeo/Filemanager#470]
I don't know if this is or could be an issue, but when I add my custom button to index.html it disappears when I open filemanager that is set to exclusiveFolder.

**Comment by simogeo** [comment]
Could happen ... depend when and where you add it.

Adding it using jQuery (and after FM instantiation) is probably the right way to go

**Comment by SlitYahoo** [comment]
I just open index.html and create add button using button tag. It is there when I open file manager without exclusive folder parametar.

**Comment by simogeo** [comment]
Not sure `exclusiveFolder` param explains that ... any url to provide ?

**Comment by SlitYahoo** [comment]
The project is on local computer... I am using xampp on win10. This is how I conected ckeditor with FM filebrowserImageBrowseUrl: 'Filemanager/index.html?exclusiveFolder=DATABASE/MEDIA'. In this case I dont get button. filebrowserImageBrowseUrl: 'Filemanager/index.html. In this case I get button.

**Comment by SlitYahoo** [comment]
All I need it was to clear the browser cache. Button is there :-) Unfortunately I have problems with letters š, č, đ. File manager doesn't stop loading if some files has those letters.

**Comment by servocoder** [comment]
Check issue #458 to get more info regarding non-ASCII chars
