### ISSUE TITLE
Cannot rename folders / files

### ISSUE THREAD

**Issue by AEK-BKF** [simogeo/Filemanager#471]
Hi,
Thanks for this nice package,
I've installed it successfully and it works fine except renaming folders / files !
When I try to rename something I get this error : No Way ,
Please could you help me ? thanks

**Comment by servocoder** [comment]
That is true.
I have fixed it on my branch, let me fix it here, I will let you know.

**Comment by AEK-BKF** [comment]
Thanks a lot :)
I'm waiting ^^

**Comment by servocoder** [comment]
Fixed, check now, please

**Comment by servocoder** [comment]
Fixing in haste I have made syntax error, try again

**Comment by AEK-BKF** [comment]
I've downloaded your new file " connectors/php/filemanager.class.php " but it doesn't work :/
