### ISSUE TITLE
No return URL

### ISSUE THREAD

**Issue by emadrashdanroya** [simogeo/Filemanager#472]
I'm using TinyMCE v3
I set Filemanager and display and can upload and remove and rename everything work fine 
but I can't return url for uploaded image 

`tinyMCE.init({
            mode: "textareas",
            theme: "advanced",
            plugins: "safari,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,
            directionality: "rtl",
            fontsize: "18",

            file_browser_callback: myFileBrowser
        });
        function myFileBrowser (field_name, url, type, win) {

            var cmsURL = '/pathtofilemanager/Filemanager/index.html';    // script URL - use an absolute path!
           
            tinyMCE.activeEditor.windowManager.open({
                file : cmsURL,
                title : 'My File Browser',
                width : 800,  // Your dimensions may differ - toy around with them!
                height : 600,
                resizable : "yes",
                inline : "yes",  // This parameter only has an effect if you use the inlinepopups plugin!
                close_previous : "no"
            }, {
                window : win,
                input : field_name
            });
            return false;
        }
`

**Comment by simogeo** [comment]
I guess the [wiki page](https://github.com/simogeo/Filemanager/wiki/How-to-use-the-Filemanager-with-tinyMCE-3-or-4) could be updated indeed...

Here is some updated documentation for tinyMCE4 : https://www.tinymce.com/docs/configure/file-image-upload/#file_browser_callback
See also : http://community.tinymce.com/forum/viewtopic.php?pid=108477#p108477

If you feel like updating the wiki page it could be great

**Comment by emadrashdanroya** [comment]
Now I can see (select) button but after click it, it's not returning url to tinymce v3

Thanks.

**Comment by simogeo** [comment]
What's the developer console saying ?

**Comment by emadrashdanroya** [comment]
> Uncaught TypeError: top.tinymce.activeEditor.windowManager.getParams is not a function
> 
> Uncaught TypeError: window.opener.SetUrl is not a function

**Comment by emadrashdanroya** [comment]
Console point to 
			win.document.getElementById(tinyMCEPopup.getWindowArg("input")).value = url;

**Comment by emadrashdanroya** [comment]
I fix it by adding 
```
        window : win,
        input : field_name

```
Many thanks :)

**Comment by simogeo** [comment]
thanks for following this up. Could you please post the whole code ? Thanks in advance

**Comment by emadrashdanroya** [comment]
add.php

```
    <script>

        tinyMCE.init({
            mode: "textareas",
            theme: "advanced",
            plugins: "safari,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template, table,contextmenu,paste,-externalplugin",
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,
            directionality: "rtl",
            fontsize: "18",


            relative_urls: false,
            file_browser_callback: function (field_name, url, type, win) {
                tinymce.activeEditor.windowManager.open({
                    title: "My file browser",
                    url: "/js/Filemanager2/index.html",
                    width: 800,
                    height: 600,
                    inline: "yes"
                }, {
                    window: win,
                    input: field_name

                });
            }
        });

```

/js/Filemanager2/index.html
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>File Manager</title>
    <link rel="stylesheet" type="text/css" href="styles/reset.css"/>
    <link rel="stylesheet" type="text/css" href="scripts/jquery.filetree/jqueryFileTree.css"/>
    <link rel="stylesheet" type="text/css" href="scripts/jquery.contextmenu/jquery.contextMenu-1.01.css"/>
    <link rel="stylesheet" type="text/css" href="styles/filemanager.css"/>
    <!--[if IE]>
    <link rel="stylesheet" type="text/css" href="styles/ie.css"/>

    <![endif]-->
</head>
<body onload="tinyMCEPopup.executeOnLoad('init();')">
<div>
    <form id="uploader" method="post">
        <button id="home" name="home" type="button" value="Home">&nbsp;</button>
        <h1></h1>

        <div id="uploadresponse"></div>
        <input id="mode" name="mode" type="hidden" value="add"/>
        <input id="currentpath" name="currentpath" type="hidden"/>
<span id="file-input-container">
	<div id="alt-fileinput">
        <input id="filepath" name="filepath" type="text"/>
        <button id="browse" name="browse" type="button" value="Browse"></button>
    </div>
	<input id="newfile" name="newfile" type="file"/>
</span>
        <button id="upload" name="upload" type="submit" value="Upload"></button>
        <button id="newfolder" name="newfolder" type="button" value="New Folder"></button>
        <button id="grid" class="ON" type="button">&nbsp;</button>
        <button id="list" type="button">&nbsp;</button>
    </form>
    <div id="splitter">
        <div id="filetree"></div>
        <div id="fileinfo">
            <h1></h1>
        </div>
    </div>

    <ul id="itemOptions" class="contextMenu">
        <li class="select"><a href="#select"></a></li>
        <li class="download"><a href="#download"></a></li>
        <li class="rename"><a href="#rename"></a></li>
        <li class="delete separator"><a href="#delete"></a></li>
    </ul>



    <script type="text/javascript" src="scripts/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="scripts/jquery.form-3.24.js"></script>
    <script type="text/javascript" src="scripts/jquery.splitter/jquery.splitter-1.5.1.js"></script>
    <script type="text/javascript" src="scripts/jquery.filetree/jqueryFileTree.js"></script>
    <script type="text/javascript" src="scripts/jquery.contextmenu/jquery.contextMenu-1.01.js"></script>
    <script type="text/javascript" src="scripts/jquery.impromptu-3.2.min.js"></script>
    <script type="text/javascript" src="scripts/jquery.tablesorter-2.7.2.min.js"></script>
    <script type="text/javascript" src="scripts/filemanager.config.js"></script>
    <script type="text/javascript" src="scripts/filemanager.js"></script>
    <script type="text/javascript" src="/js/tiny_mce2/tiny_mce_popup.js"></script>
</div>
</body>
</html>

```

**Comment by emadrashdanroya** [comment]
Thanks :+1:
