### ISSUE TITLE
Any way to use ACL to control Filemanager

### ISSUE THREAD

**Issue by billzt** [simogeo/Filemanager#473]
In https://github.com/simogeo/Filemanager/wiki/Security-concern we could control someone to **use** Filemanager. Is there any way to use more detailed ACL? For example:

user A could upload/download, but can't delete files
user B could only download, can't do other things
user C could do all things

**Comment by simogeo** [comment]
A way would be to have dedicated or dynamic config files : https://github.com/simogeo/Filemanager/wiki/Passing-parameters-to-the-FM#passing-a-config-file

**Comment by billzt** [comment]
Yes, it is a possible way. However I think it is too dangerous to show the config file in URL. For example, If I log in as user A, I am still able to use priviledge of user C by visit:` http://fm.linea21.com/index.html?config=user.C.json`

What I prefer is to define them in `user.config.php` just like https://github.com/simogeo/Filemanager/wiki/How-to-allow-users-to-have-their-own-folder 

```php
// If user A log in,
$content = file_get_contents("../../scripts/user.A.json");
$fm = new Filemanager();
$fm->setup(json_decode($content, true));
```

However, it seems doesn't work. Am I wrong?

**Comment by simogeo** [comment]
> I think something could be done with the $extraConfig
Only on the connector side ....

I really think the best way is to generate the file dynamically (based on PHP session) and return the wanted json file. Do you get my point or do you need a sample ?

**Comment by billzt** [comment]
Well, I will try it.
