### ISSUE TITLE
Change upload path

### ISSUE THREAD

**Issue by emadrashdanroya** [simogeo/Filemanager#475]
Hello simogeo,
First nice work
But I'm trying to change upload path
I changed in filemanager.config.js 
from
`var fileRoot = '/' + am + 'userfiles/';`
to
`var fileRoot = '/home/user/web/public/domain.com/public/img/uploadimgs/';`

Now when I open filemanager 

> The directory /home/user/web/public/domain.com/public/img/uploadimgs/ does not exist

Please help

**Comment by simogeo** [comment]
well, this syntax does not exists anymore ! I guess you are using an old version.

Why don't you switch to a new one ?

See : 
* https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file
* https://github.com/simogeo/Filemanager/wiki/Specify-user-folder%2C-configuration-cases

**Comment by emadrashdanroya** [comment]
Is there any way to change old version upload. I can't update right now.

Thanks

**Comment by simogeo** [comment]
sorry, too old, I don't remember ... it may be work on the js side but not on the PHP side .... :-/

**Comment by emadrashdanroya** [comment]
Can I migrate new filemanager with TinyMCE v3 ?

**Comment by simogeo** [comment]
yes see #472

**Comment by emadrashdanroya** [comment]
Thanks, That's worked :+1: :smile:
