### ISSUE TITLE
Can not loading korean charset used file & directory name.

### ISSUE THREAD

**Issue by son7872** [simogeo/Filemanager#477]
Can not loading file & directory,it's used korean charset name. 

So,  loading progress circle does not finish.

I can not see directory & file list.

And If i create a new folder name korean, created folder name is 'unsupportedCharsReplacement'.

I'm not normally available?

Please additional Korean language support.

Thanks.

**Comment by simogeo** [comment]
FM is not supposed to handle this .... see also #458 and #244 

Would be great but not easy ...
