### ISSUE TITLE
Configuration Issue

### ISSUE THREAD

**Issue by abhishekdoshi** [simogeo/Filemanager#478]
Hello,
When i Put all files in Web Server (localhost) Root Directory, when i trying to access Root file, no file shows me , but when i create new folder top-right side, it creates directory and Uploaded all files in "userfiles" but can't be able to view that all files and access that files in root directory. 
Note : I am using Windows OS with Apache WAMP Server

**Comment by simogeo** [comment]
Start again from the beginning or use Console development (network panel to wee what's happening )

**Comment by abhishekdoshi** [comment]
Hii, 
In-fact i already do more than 5 times on my server. If you don't mind please can you give me suggestion? your help if very useful to me. 
Thanks

**Comment by simogeo** [comment]
please, tell me where precisely is your FM folder and copy-paste your config file.

**Comment by abhishekdoshi** [comment]
I get it @simogeo , solution is to enable IIS Server. Thanks , beautiful software
