### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by emadrashdanroya** [simogeo/Filemanager#480]
Hello simogeo
I uploaded fresh download copy filemanager 
when I opened index.html stuck on loading icon.
Please help

**Comment by simogeo** [comment]
check development console (network panel) to see what's happening ........

Which server are you using ?

**Comment by emadrashdanroya** [comment]
Maybe you didn't understand my problem,
My problem that when I opened index.html I see loading icon and stuck with it. (keep loading)

**Comment by simogeo** [comment]
Maybe you didn't understand my **answer** ...
Filemanager runs under a web server ....

**Comment by emadrashdanroya** [comment]
Centos 6.7 x64
Apache/2.4.18 (Unix)

**Comment by simogeo** [comment]
And have you checked  development console (network panel) to see what's happening ........

**Comment by emadrashdanroya** [comment]
404 -> filemanager.config.default.json
I copied filemanager.config.json to filemanager.config.default.json
and it's working now
Thanks man =)

**Comment by emadrashdanroya** [comment]
Hey simogeo
I'm facing another problem..
Browsing works fine 
everything seems ok unless I select image 
console print(
`a.split is not a function`
)
Please help thanks

**Comment by simogeo** [comment]
?? are you sure it comes from the Filemanager ? 

if you want to identify precisely the problem, in you index.html file, replace link to filemanager.min.js by link to filemanager.js file

**Comment by emadrashdanroya** [comment]
Changed 
Console print
`filemanager.js:107 Uncaught TypeError: url.split is not a function`

**Comment by simogeo** [comment]
set config.options.baseUrl to `false`

**Comment by emadrashdanroya** [comment]
Now I can select photo but URL not correct for example it should be

`www.domain.com/img/name.jpg ` 
But output 
`img/name.jpg`

**Comment by simogeo** [comment]
And what's happening if baseUrl is set to `www.domain.com/img/` ?

**Comment by emadrashdanroya** [comment]
That's works :+1: 
so keep settings with url ?

**Comment by simogeo** [comment]
What was the value before ? only `http://www.domain.com`.. I'll have a look on that

**Comment by emadrashdanroya** [comment]
no I'm using subdomain now
`http://dev.domain.com`
Really thanks simogeo u r great :D
