### ISSUE TITLE
Two trailing slashes in path display

### ISSUE THREAD

**Issue by WulleBulle** [simogeo/Filemanager#481]
Hello,

I can't figure out why my path info is showing two trailing slashes.

`Current folder: //`

The options in the filemanager.config.js are:

`"serverRoot": true,
        "fileRoot": "content/images",
        "baseUrl": false,`

Is there anything wrong with it? The folder info doesn't change if I change the fileRoot or else.

I am using cfm as script language.
When I load the tree I see two getFolder requests in the browsers console. In the first one the path parameter has a trailing / (path /content/images/).
The second one has none so the path is shown as content/images.

I think this is the reason why I can't delete, upload or replace files. If I try to delete a file the given path doesn't contain the filename.

**Comment by simogeo** [comment]
CFM connector is very outdated .... with no maintainer. Want to contribute ?

**Comment by WulleBulle** [comment]
Ah, ok. I will take a look in it and report here. Thank you for answering.
