### ISSUE TITLE
Show in Bootstrap Modal?

### ISSUE THREAD

**Issue by mehmetalidumlu** [simogeo/Filemanager#483]
Hi all,
How can i show file manager page in bootstrap modal? I shown it in a new window correctly, but when i want to show it in a bootstrap modal then some things gone awry. There is a [**screenshot**](http://prntscr.com/atpyy8)
Thanks...

**Comment by simogeo** [comment]
For information works well with jquery.colorbox. see : https://github.com/simogeo/Filemanager/wiki/How-to-open-the-Filemanager-from-CKEditor-in-a-modal-window

Could you enquire regarding bootstrap modal and let us know ? thanks
