### ISSUE TITLE
Chunk Size?

### ISSUE THREAD

**Issue by mehmetalidumlu** [simogeo/Filemanager#484]
Hi again,
I can't upload large data file. I set maxRequestLength to "2147483647". I must upload bigger then 10 GiB in one file but i cant. Can you tell me anything of upload large data file?
Thanks...

**Comment by servocoder** [comment]
The file uploader in the current version doesn't support chunked uploading. I am working on a new version in my fork. Currently I have completely changed file uploader plugin to Blueimp file uploader which supports chunked upload. But don't rush to test my fork, I have all these stuff on my localhost, and I am performing some tests and bugfix. I plan to push the changes at the end of this week or on the next week.

**Comment by simogeo** [comment]
@servocoder : Looking forward to see this !

**Comment by servocoder** [comment]
@mehmetalidumlu, @simogeo
Released:
https://github.com/simogeo/Filemanager/issues/456#issuecomment-217649069
