### ISSUE TITLE
Can't Set Virtual Path

### ISSUE THREAD

**Issue by mehmetalidumlu** [simogeo/Filemanager#486]
Hi,
I cant set fileroot to virtual path. "http://localhost/uploads" address directed "E:/uploads" on server. 
I checked out https://github.com/simogeo/Filemanager/wiki/Specify-user-folder%2C-configuration-cases but i cant do this. Can you help me?

**Comment by mehmetalidumlu** [comment]
Config File Settings:
```
"serverRoot": false,
"fileRoot": "/localhost/uploads/",
"baseUrl": "E:/root/",
```
**ASHX** DirectoryInfo(HttpContext.Current.Server.MapPath(path))
`E:\projects\mayProject\test\localhost\uploads\`	

Config File Settings:
```
"serverRoot": true,
"fileRoot": false,						
"baseUrl": false,
```
**ASHX** DirectoryInfo(HttpContext.Current.Server.MapPath(path))
`E:\projects\mayProject\test\Contents\scripts\Filemanager-master\userfiles\`

**My Virtual Path:** `http://localhost/uploads`

I tried different way for use virtual path but I failed.

**Comment by mehmetalidumlu** [comment]
Will not help anyone? 
You can at least make a suggestion...

**Comment by simogeo** [comment]
Not sur ashx connector handle this .... (there is no maintainer)
