### ISSUE TITLE
Yii and Filemanager

### ISSUE THREAD

**Issue by woody1990** [simogeo/Filemanager#487]
I have file manager loaded as a component in Yii and got it to work! Problem is that I have an issue on initial loading of the page. The file tree takes up the majority of the screen. The slider still works but it does't get positioned correctly. Anyone one tackled this or know what's going on?

![file tree issue](https://cloud.githubusercontent.com/assets/8379533/14730347/f8e44776-0888-11e6-863f-d64de81497ff.PNG)

**Comment by simogeo** [comment]
Try to change `splitterWidth` and `splitterMinWidth` in [config.json](https://github.com/simogeo/Filemanager/blob/master/scripts/filemanager.config.js.default#L21) file

**Comment by woody1990** [comment]
@simogeo Yeah I tried that and it didn't change it. Still fires the filetree to the right

**Comment by simogeo** [comment]
any news from this ?
