### ISSUE TITLE
Help fix

### ISSUE THREAD

**Issue by it9xpro** [simogeo/Filemanager#489]
Hello . i am using filemanager create folder and error like images
help me fix 
thank 
![bug](https://cloud.githubusercontent.com/assets/6617916/15236158/31f7ae9a-18ec-11e6-953c-7e7b70038d26.png)

**Comment by Bartosz86** [comment]
Open folder "6" and check the existence of folder "7".
On images you show only first depth in root folder.

**Comment by it9xpro** [comment]
:(
![screenshot_1](https://cloud.githubusercontent.com/assets/6617916/15243870/7e283140-1928-11e6-9da5-d45036c377ea.png)

**Comment by simogeo** [comment]
post your config file
