### ISSUE TITLE
A small error with function setFileRoot()

### ISSUE THREAD

**Issue by Bartosz86** [simogeo/Filemanager#490]
Hi,
I spent a lot of time trying to change settings with fileRoot and prepared for each user their own folders on data. 

If I set fileRoot on localization user's files all is ok, but when I try set it in user.config.php with function setFileRoot, I get error "No way. (Or loading page without any actions - only loader.gif)". 

Could you help me resolve this problem?

Regards,
Bartosz

User.config.php
`<?php 
function auth() {
	return true;
}
$fPathfolderPath = 'public/filemanager/userfiles/user1/';
$fm = new Filemanager();
$fm->setFileRoot($folderPath);
?>`

filemanager.config.js:
`{
		"_comment": "IMPORTANT : go to the wiki page to know about options configuration https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file",
    "options": {
        "culture": "pl",
        "lang": "php",
        "defaultViewMode": "grid",
        "autoload": true,
        "showFullPath": false,
        "showTitleAttr": false,
        "browseOnly": false,
        "showConfirmation": true,
        "showThumbs": true,
        "generateThumbnails": true,
        "searchBox": true,
        "listFiles": true,
        "fileSorting": "default",
        "chars_only_latin": true,
        "dateFormat": "d.m.Y H:i",
        "serverRoot": true,
        "fileRoot": "/", 
        "relPath": false,
        "logger": true,
        "logfile": "/home/bartosz_g/Pulpit/filemanager_log.txt",
        "capabilities": ["select", "download", "rename", "delete", "replace"],
        "plugins": []
    },
    "security": {
        "allowChangeExtensions": false,
        "allowNoExtension": false,
        "uploadPolicy": "DISALLOW_ALL",
        "uploadRestrictions": [
            "jpg",
            "jpeg",
            "gif",
            "png",
            "svg",
            "txt",
            "pdf",
            "odp",
            "ods",
            "odt",
            "rtf",
            "doc",
            "docx",
            "xls",
            "xlsx",
            "ppt",
            "pptx",
            "csv",
            "ogv",
            "mp4",
            "webm",
            "m4v",
            "ogg",
            "mp3",
            "wav"
        ]
    },
    "upload": {
        "overwrite": false,
        "imagesOnly": false,
        "fileSizeLimit": 16
    },
    "exclude": {
        "unallowed_files": [
            ".htaccess",
            "web.config"
        ],
        "unallowed_dirs": [
            "_thumbs",
            ".CDN_ACCESS_LOGS",
            "cloudservers"
        ],
        "unallowed_files_REGEXP": "/^\\./",
        "unallowed_dirs_REGEXP": "/^\\./"
    },
    "images": {
        "imagesExt": [
            "jpg",
            "jpeg",
            "gif",
            "png",
            "svg"
        ],
        "resize": {
        	"enabled":true,
        	"maxWidth": 1280,
            "maxHeight": 1024
        }
    },
    "videos": {
        "showVideoPlayer": true,
        "videosExt": [
            "ogv",
            "mp4",
            "webm",
            "m4v"
        ],
        "videosPlayerWidth": 400,
        "videosPlayerHeight": 222
    },
    "audios": {
        "showAudioPlayer": true,
        "audiosExt": [
            "ogg",
            "mp3",
            "wav"
        ]
    },
    "edit": {
        "enabled": false,
        "lineNumbers": true,
        "lineWrapping": true,
        "codeHighlight": false,
        "theme": "elegant",
        "editExt": [
            "txt",
            "csv"
        ]
    },
    "extras": {
        "extra_js": [],
        "extra_js_async": true
    },
    "icons": {
        "path": "images/fileicons/",
        "directory": "_Open.png",
        "default": "default.png"
    }
}`

logs file:
`[13/05/2016 05:36:21]#127.0.0.1#Pqb\FilemanagerLaravel\Filemanager::enableLog - Log enabled (in /home/bartosz_g/Pulpit/filemanager_log.txt file)
[13/05/2016 05:36:21]#127.0.0.1#Pqb\FilemanagerLaravel\Filemanager::__construct $this->doc_root value /home/bartosz_g/Pulpit/public_html/public
[13/05/2016 05:36:21]#127.0.0.1#Pqb\FilemanagerLaravel\Filemanager::__construct $this->separator value 
[13/05/2016 05:36:21]#127.0.0.1# returned path : /home/bartosz_g/Pulpit/public_html/public/
[13/05/2016 05:36:21]#127.0.0.1#Pqb\FilemanagerLaravel\Filemanager::isValidPath path1 value : /home/bartosz_g/Pulpit/public_html/public
[13/05/2016 05:36:21]#127.0.0.1#Pqb\FilemanagerLaravel\Filemanager::isValidPath path2 value : /home/bartosz_g/Pulpit/public_html/public/filemanager
[13/05/2016 05:36:21]#127.0.0.1#Pqb\FilemanagerLaravel\Filemanager::isValidPath path1 value : /home/bartosz_g/Pulpit/public_html/public
[13/05/2016 05:36:21]#127.0.0.1#Pqb\FilemanagerLaravel\Filemanager::error - error message : No way.`

**Comment by simogeo** [comment]
you can try to specify  : 

`"serverRoot": false,`


and 

```php
<?php 
function auth() { return true; } 
$fPathfolderPath = 'PATHTOWEBSERVER/public/filemanager/userfiles/user1/'; 
$fm = new Filemanager(); $fm->setFileRoot($folderPath); 
?>
```

or ask to the FilemanagerLaravel packager:
