### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by oneleft** [simogeo/Filemanager#491]
Are you still looking for a new maintainer?  If so, there is no clear direction on submitting an application for the position.  If not, please remove the notice from the top of the repo homepage.

**Comment by simogeo** [comment]
Sorry for the delay ... my computer crashed few days ago (hdd is dead) and it is not resolved yet ...
Actually @servocoder is already in, workin in a new fork (#456) and doing a wonderful job.

But if you want to involve, I will encourage you to do so - the more we are in, the more the app gets better. Il let @servocoder the last word.

**Comment by ferenczAndras** [comment]
I would be interested too :)

**Comment by servocoder** [comment]
Are you, guys, able to maintain and develop non-PHP connectors, to make and keep them up-to-date? I've released [new version](https://github.com/servocoder/RichFilemanager), with new features listed in #456, and I plan to continue develop filemanager. Client-side and PHP connector at least. Any of your contribution is a great help. Testing of the new release is would be fine too.

**Comment by simogeo** [comment]
Thanks you all, for your interest in maintaining FM. 
I'd like the idea of having a main maintainer (servocoder) responsible of the all project.But I really think it's worth value for the project having a common roadmap and regular contributors. ... (my two cents) what do you think ?

**Comment by servocoder** [comment]
Sure, I meant that guys can take FULL responsibility for any of non-PHP connector and become its main maintainer. But any other help and contribution will be greatly appreciated, including PHP connector and cliend-side.
