### ISSUE TITLE
codeigniter userfiles images have files but cant load

### ISSUE THREAD

**Issue by chiukoo** [simogeo/Filemanager#494]
![screenshot](https://cloud.githubusercontent.com/assets/11659606/15675445/ab092ba6-2774-11e6-8583-1a0f75f388bc.png)

this url is work             : assets/filemanager/images/fmlogo_bbg.png

but this 404 not found : assets/filemanager/userfiles/slider.jpg

all setting 755

and php version is 5.2

why~~please help!!

**Comment by simogeo** [comment]
any url to provide ?

**Comment by chiukoo** [comment]
@simogeo I remove userfile/web.config, and its work. but why !?

**Comment by simogeo** [comment]
Excellent ! ... No idea... Check your Apache logs ! or whatever server you use.

Please let us know

**Comment by chiukoo** [comment]
@simogeo ok i will try ~~thx ^^
