### ISSUE TITLE
error when i try to open pdf

### ISSUE THREAD

**Issue by PanChenhao** [simogeo/Filemanager#495]
I intergrate filemanager into a MVC frame,  but i still use ashx to operate file.  and when i try to open pdf, i got the error message,  

>  UnexpectedResponseException: Unexpected server response (500) while retrieving PDF "http://localhost:51146/Upload/Training Plan 2016.pdf".1 pdf.js:426:42

what's the problem

**Comment by simogeo** [comment]
I would say it is because of 'space' characters in string

Try with another file named with no blank characters.

**Comment by PanChenhao** [comment]
I tried with aed.pdf, and got the same error message again. I use IE11, and check network in develop tool, guess the problem maybe caused by wrong Type. URL:/Upload/aed.pdf, protocol: HTTP, Method: GET, Result: 500, **Type: text/html**, Received: 6.00KB, Taken: 31 ms, Initator: XMLHttpRequest.
Should Type be application/pdf? how to change it?

**Comment by simogeo** [comment]
try to upload your file on the online demo and see what's happening : http://fm.linea21.com/
