### ISSUE TITLE
The directory /filemanager/userfiles/ does not exist. using laravel 5.1

### ISSUE THREAD

**Issue by wabsa** [simogeo/Filemanager#496]
default.config.php:
`// Folder path
$folderPath = $app->basePath() . '/filemanager/userfiles/';    `

filemanager.config.js:
`"serverRoot": true,
 "fileRoot": "filemanager/userfiles/",`

my server folder structure (laravel)
core/app
core/bootstrap
core/etc...

public_html/filemanager
public_html/assets

any suggestions? thanks

**Comment by simogeo** [comment]
Why don't you work with the dedicated package ? https://github.com/bestmomo/filemanager
