### ISSUE TITLE
jquery-1.11.3.min.js Failed to load resource: the server responded with a status of 404

### ISSUE THREAD

**Issue by lifeact** [simogeo/Filemanager#497]
Hi, i integrate Filemanager  in CKEDITOR

`
    // Turn off automatic editor creation first.
    CKEDITOR.disableAutoInline = false;
    CKEDITOR.inline( 'editor1', {
    filebrowserBrowseUrl: 'http://demo.times.mk.ua/Content/Filemanager-master/index.html'    
});
	
`

when i open http://demo.times.mk.ua/Content/Filemanager-master/index.html i have error: 
![80411dd28c](https://cloud.githubusercontent.com/assets/8957733/16244669/dad70fa0-3805-11e6-89f1-f6c99c960081.jpg)

file is available http://demo.times.mk.ua/Content/Filemanager-master/scripts/jquery-1.11.3.min.js

please help me fix this error...

**Comment by simogeo** [comment]
You have a 404 error on http://demo.times.mk.ua/Content/Filemanager-master/scripts/filemanager.config.default.json

and 

http://demo.times.mk.ua/Content/Filemanager-master/scripts/filemanager.config.json
