### ISSUE TITLE
How to use simogeo Filemanager in Asp MVC ?

### ISSUE THREAD

**Issue by AnastasiV** [simogeo/Filemanager#501]
I have ASP.NET MVC Framework .../connectors/mvc/FilemanagerController.cs
but it does not match to this rule [path to FileManager]/connectors/[language extension]/filemanager.[language extension]
`"lang": "mvc", ` in filemanager.config.json doesn't work!
`"lang": "ashx",` - this work
Only I want use mvc connector. How include it? How should to choice the mvc connector?

**Comment by dangtathanh** [comment]
Check this issue: https://github.com/simogeo/Filemanager/issues/461

It worked for my MVC5 project.

**Comment by AnastasiV** [comment]
@dangtathanh thank you!
