### ISSUE TITLE
File size limit during downloading a folder  - download button 

### ISSUE THREAD

**Issue by Antintn** [simogeo/Filemanager#502]
Hello.

I would like to ask if is there also a possibility to limit the size of the downloaded folders?
I would like to use something like:
If we have folder larger than 2GB the button "download" will not show up when we click right button of the mouse on the folder  
If we have folder smaller than 2GB the button "download" will show up when we click right button of the mouse on the folder and the file download will be available

Was something similar implemented in filemanager?
If not, could you please guide me how can it be implemented in the easiest way, please?

Kind Regards

**Comment by servocoder** [comment]
There is no such option for Download action.
I have implemented `fileRootSizeLimit` option in [RichFilemanager](https://github.com/servocoder/RichFilemanager) (forked repo), so you are able to limit the size of destination root folder, but still nothing for downloading limitation.
