### ISSUE TITLE
Bug thumbnail of user

### ISSUE THREAD

**Issue by salim-dev** [simogeo/Filemanager#503]
Bonsoir,
j'ai un soucie avec le générateur de vignette coté utilisateur et non coté adminisateur qui fonctionne tres bien.
le générateur crée un dossier au nom de l'image (pour chaque image) et dans ce dossier il crée le dossier _thumbs et enfin dans ce dossier il génère la vignette. mais dans le dossier _thumbs principal il n'y a rien.

filemanagers.config.js

{
"_comment": "IMPORTANT : go to the wiki page to know about options configuration https://github.com/simogeo/Filemanager/wiki/Filemanager-configuration-file",
"options": {
"culture": "en",
"lang": "php",
"theme": "default",
"defaultViewMode": "grid",
"autoload": true,
"showFullPath": false,
"showTitleAttr": false,
"browseOnly": false,
"showConfirmation": true,
"showThumbs": true,
"generateThumbnails": true,
"cacheThumbnails": false,
"searchBox": true,
"listFiles": true,
"fileSorting": "default",
"chars_only_latin": true,
"dateFormat": "d M Y H:i",
"serverRoot": false,
"fileRoot": "/",
"baseUrl": "/uploads/sources/",
"logger": false,
"capabilities": ["select", "download", "delete"],
"plugins": []
},
"security": {
"allowFolderDownload": false,
"allowChangeExtensions": false,
"allowNoExtension": false,
"uploadPolicy": "DISALLOW_ALL",
"uploadRestrictions": [
"jpg",
"jpeg",
"gif",
"png",
"svg",
"txt",
"pdf",
"odp",
"ods",
"odt",
"rtf",
"doc",
"docx",
"xls",
"xlsx",
"ppt",
"pptx",
"csv",
"ogv",
"mp4",
"webm",
"m4v",
"ogg",
"mp3",
"wav",
"zip",
"rar"
]
},
"upload": {
"multiple": true,
"number": 14,
"overwrite": false,
"imagesOnly": false,
"fileSizeLimit": 20
},
"exclude": {
"unallowed_files": [
".htaccess",
"web.config"
],
"unallowed_dirs": [
"_thumbs",
"sources-thumb",
".CDN_ACCESS_LOGS",
"cloudservers"
],
"unallowed_files_REGEXP": "/^\./",
"unallowed_dirs_REGEXP": "/^\./"
},
"images": {
"imagesExt": [
"jpg",
"jpeg",
"gif",
"png",
"svg"
],
"resize": {
"enabled":true,
"maxWidth": 2050,
"maxHeight": 2050
}
},
"videos": {
"showVideoPlayer": true,
"videosExt": [
"ogv",
"mp4",
"webm",
"m4v"
],
"videosPlayerWidth": 400,
"videosPlayerHeight": 222
},
"audios": {
"showAudioPlayer": true,
"audiosExt": [
"ogg",
"mp3",
"wav"
]
},
"edit": {
"enabled": true,
"lineNumbers": true,
"lineWrapping": true,
"codeHighlight": false,
"theme": "elegant",
"editExt": [
"txt",
"csv"
]
},
"customScrollbar": {
"enabled": true,
"theme": "inset-2-dark",
"button": true
},
"extras": {
"extra_js": [],
"extra_js_async": true
},
"icons": {
"path": "images/fileicons/",
"directory": "_Open.png",
"default": "default.png"
},
"url": "",
"version": ""
}

filemanager.class.php

protected $config = array();
protected $language = array();
protected $get = array();
protected $post = array();
protected $properties = array();
protected $item = array();
protected $languages = array();
protected $allowed_actions = array();
protected $root = '';                // Filemanager root folder
protected $doc_root = '';        // root folder known by JS : $this->config['options']['fileRoot'] (filepath or '/') or $_SERVER['DOCUMENT_ROOT'] - overwritten by setFileRoot() method
protected $dynamic_fileroot = ''; // Only set if setFileRoot() is called. Second part of the path : '/Filemanager/assets/' ( doc_root - $_SERVER['DOCUMENT_ROOT'])
protected $path_to_files = ''; // path to FM userfiles folder - automatically computed by the PHP class, something like '/var/www/Filemanager/userfiles'
protected $logger = false;
protected $logfile = '';
protected $cachefolder = '_thumbs/';
protected $thumbnail_width = 260;
protected $thumbnail_height = 260;
protected $separator = 'imgs'; // @todo fix keep it or not?

**Comment by salim-dev** [comment]
merci d avance

**Comment by simogeo** [comment]
> protected $separator = 'imgs'; 

this is not normal at all ... $separator should take value 'userfiles'.
Please re-install the FM

**Comment by salim-dev** [comment]
ok, but is it possible to change the separator , because on my project , it is necessary that the separator should have the name " imgs " not " userfile "

**Comment by simogeo** [comment]
Please, read : https://github.com/simogeo/Filemanager/wiki/Specify-user-folder%2C-configuration-cases. Your settings could be : 

```javascript
        "serverRoot": false,
        "fileRoot": "/home/www/your-app/filemanager/imgs/",
```

**And no need to do any change in the php class ! **
