### ISSUE TITLE
Is there an API or something to add unzip functionality to FileManager

### ISSUE THREAD

**Issue by SlitYahoo** [simogeo/Filemanager#506]
Hi, 
I would like to add unzip functionality to Filemanager. Is there some easy way to do so?
I translated Filemanager to Croatian language... if you need it...

**Comment by servocoder** [comment]
Not so easy but possible.
It depends on the connector and storage type of course. It may be implemented for PHP connector definetely, but unzip functionality brings security threat. Customer may put any files to archive, potentially malicious, and you will not be able to check them (by file type, e.g.).

**Comment by SlitYahoo** [comment]
Then what is the best way for uploading folder using Filemanager?

**Comment by servocoder** [comment]
No way, indeed. The only way currently is to create new empty folder and use multiple files upload then. BTW unzip feature has a right to exist. If you are going to use FM yourself or share to permitted users solely. In some "admin panel" or another secured area. It may be optional feature in config file to use it to your own risk. I will add it to my todo list, but I have others things to do first.

**Comment by servocoder** [comment]
In any case this repo is weakly supported. I can suggest you to migrate to [Rich Filemanager](https://github.com/servocoder/RichFilemanager). All new features are implementing there. And use it for any further issues and suggestions, please.

**Comment by SlitYahoo** [comment]
Ok. Thank you.
