### ISSUE TITLE
Is there any way to make insertfile button on TinyMce?

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [simogeo/Filemanager#516]
I did this way - https://github.com/simogeo/Filemanager/wiki/How-to-use-the-Filemanager-with-tinyMCE-3-or-4

and now Filemanager is integrated on InsertImage dialog and some others dialog. Awesome.
But is there any way also to make InsterFile button on toolbar like this - https://yadi.sk/i/LDxbp6mIweeTS (image)

**Comment by simogeo** [comment]
Sorry, I'm not a tinymce user ... and I have no time to have a look on that.
Would you investigate and give us feedback ?... I don't think it is complicated
