### ISSUE TITLE
Unable to upload files:

### ISSUE THREAD

**Issue by jcink** [simogeo/Filemanager#520]
My policy is as follows:
 
       "policy": "ALLOW_ALL",
        "restrictions": [
            "false"
        ]

Server configuration is a cPanel server with PHP 7.0.x

This is in filemanager.config.json; I don't knnow what I'm doing wrong. Please advise. The file type I'm trying to upload is .php

**Comment by simogeo** [comment]
And what about ? :  

       "policy": "ALLOW_ALL",
        "restrictions": []
