### ISSUE TITLE
Some help for config.php (Unable to perform initial request to server)

### ISSUE THREAD

**Issue by tenq** [simogeo/Filemanager#521]
I tried to use this file manager with ckeditor in modal, but I receive this message:

**Unable to perform initial request to server.**

```
PHP Parse error:  syntax error, unexpected '[' in \admin\editor\filemanager\connectors\php\config.php on line 10
```
FileManger folder is in: /admin/editor/filemanager

My userfiles is in: /arquivos/userfiles (folder with write permission)

The Server is Windows 2008 running PHP.
thanks

**Comment by simogeo** [comment]
It seems you are using the RichFilemanager, please use the right project issues reporting tools : https://github.com/servocoder/RichFilemanager/issues

cc @servocoder
