### ISSUE TITLE
Filemanager with CKEditor in CI 3

### ISSUE THREAD

**Issue by jamboljack** [simogeo/Filemanager#522]
Good Night Everyone,

I have recently tried FileManager with CKEditor in CI 3, if the session OFF result is correct. But if the session ON, the results are only loading. any suggestion ?

Source : https://github.com/moemoe89/codeigniter-ckeditor-filemanager

Session OFF : 
![not auth](https://cloud.githubusercontent.com/assets/6668588/20713846/6e258030-b67c-11e6-8027-74d911123fe5.jpg)

Session ON : 
![session on](https://cloud.githubusercontent.com/assets/6668588/20713857/771f5256-b67c-11e6-92a3-e5327ebeac3a.jpg)

I create session : http://pastebin.com/HJDkAH7R
default.config : http://pastebin.com/cZaZfYsC

**Comment by simogeo** [comment]
Use the developer console to see what reponse is sent be the ajax request.

Do you have an url to share ?

**Comment by jamboljack** [comment]
It's strange,, my application still offline.
But i want check again and answering your question, it's running well @simogeo 

![file done](https://cloud.githubusercontent.com/assets/6668588/20748426/afede63e-b720-11e6-83a2-19138c314ba1.jpg)

**Comment by simogeo** [comment]
perfect !
