### ISSUE TITLE
raspberry pi media server

### ISSUE THREAD

**Issue by mkeyno** [simogeo/Filemanager#523]
sorry guys to open ticket for my question , but I'm trying  to let my raspberry pi  connected client, share media files from storage connected to raspberry pi , I've already install NAS server but its not beautiful as your file manger lib , can you advise me how to use your lib for such media server

**Comment by servocoder** [comment]
Your question is very particular, I don't have any experience with media servers. Furthermore this repo is deprecated and haven't been supported anymore. We can keep this issue open for some time in case somebody experienced in this matter and would share it with you.
