### ISSUE TITLE
Keeps loading

### ISSUE THREAD

**Issue by Luuk1979** [simogeo/Filemanager#524]
Hi guys

REad many topics bout this issue.
Got same problem. Trying to run it under Linux, Apache, PHP.
Using default config. Also downloaded the Filemanager-master which is a working package. Same problem.

Dont see any errors in apache log.

Tips please

![loading](https://cloud.githubusercontent.com/assets/25485127/22514342/53de968a-e89f-11e6-9dd7-dc3f4f18aa41.PNG)

**Comment by servocoder** [comment]
This repo is deprecated and haven't been supported anymore. Please, try https://github.com/servocoder/RichFilemanager. Read the wiki thoroughly before create an issue: https://github.com/servocoder/RichFilemanager/wiki
