### ISSUE TITLE
Include FM in other PHP file

### ISSUE THREAD

**Issue by phlyte7** [simogeo/Filemanager#526]
I have a PHP project which requires a file manager among other features. I've put Filemanager in a sub folder called docmgt, renamed index.html to index.php. 
I have another php file outside the docmgt folder where I prefer to use include("docmgt/index.php") to make Filemanager part of the project instead of an Iframe. I've transferred all the links to Filemanager's scripts and css to the outer php file and stripped off the `<html>` and `<head>` tags from docmgt/index.php. I had to update the links to resources in filemanager.min.js and filemanager.class.php to correspond to the new file path. At this point I see all the controls but there is a "No Way" displayed in the content area and Filemanager cannot access the userfiles folder. 
Firebug shows the response for connectors/php/filemanager.php is  {"Error":"No way.","Code":"-1","Properties":{"Date Created":null,"Date Modified":null,"Height":null,"Width"
:null,"Size":null}}

What have I missed?

**Comment by simogeo** [comment]
did you fix the issue ? Please share the tip. Thanks
