### ISSUE TITLE
Help me! plase

### ISSUE THREAD

**Issue by thanhtai9606** [simogeo/Filemanager#527]
I'm using Visualt Studio 2015 and ASP.NET MVC but I don'n know, How to add this File Manger into my project. It doesn't work, Help me!

**Comment by thanhtai9606** [comment]
Thank you, I have just change lang by ashx ok. But MVC in this project for what???

**Comment by servocoder** [comment]
You don't have to duplicate you question in both repositories: https://github.com/servocoder/RichFilemanager/issues/114.  RichFilemanager is derived from this particular repo, and this repo is deprecated and weakly supported. MVC connector at this repo is outdated as well as at RichFilemanager repo.
