### ISSUE TITLE
How to define upload size

### ISSUE THREAD

**Issue by samphors** [simogeo/Filemanager#528]
I've read through of your document and checked for the existing issues of yours, but anyway I couldn't see. So could you tell me how to do?

* I used PHP connection

**Comment by servocoder** [comment]
What do you mean behind "upload size"? Be more precise, please.

**Comment by samphors** [comment]
My php.ini upload size is smaller than default configuration of json file. I've to update the max upload size on my server, than it's ok.

Thank you
