### ISSUE TITLE
Issue with expandedFolder

### ISSUE THREAD

**Issue by thincmedia** [simogeo/Filemanager#533]
Hi, thank a mil to the compilers for such a great and comprehensive file management solution.

I have a slight issue with the trying to work with expandedFolder as guided on [this thread ](https://github.com/simogeo/Filemanager/wiki/How-to-allow-users-to-have-their-own-folder)

Here are code snippets from my setup:

filemanager.config.json

`"serverRoot":true,
        "fileRoot":"/",`

filemanager.php

`$folderPath = '/' . $_SESSION['myfolder'] . '/';
$fm->setFileRoot($folderPath, true);`

My installation is structured this way:

http://localhost/fm2/filemanager/?index.html?expandedFolder=1234/

The above works perfectly for all default functionalities:

however when I bring in the expandedFolder dynamic as shown below the code fails:

http://localhost/fm2/filemanager/?index.html?expandedFolder=1234/

Also, I note in some example config files there is code which is not included in the latest master zip or composer installation. e.g. the fileroot and serveroor attributes are not included by default in the composer installation I did just  a day ago. (latest package)

Any kind of help would be appreciated.

Kind Regards
Gugu

**Comment by simogeo** [comment]
Are you ising this FM or [RichFileManager](https://github.com/servocoder/RichFilemanager) ?

**Comment by thincmedia** [comment]
I'm using RichFileManager and using the PHP connector

**Comment by servocoder** [comment]
In this case this is the wrong repo to ask.
If you use [RichFileManager](https://github.com/servocoder/RichFilemanager) it was completely reworked, and doen't provide `serverRoot` and `fileRoot` options in the JSON file. These options has been moved to PHP configuration file. Check the Wiki of the RichFilemanager repository for details.

I close this issue. If you will continue to experience difficulties feel free to ask in the RichFilemanager repo.

**Comment by thincmedia** [comment]
Thank you.
