### ISSUE TITLE
Laravel routes

### ISSUE THREAD

**Issue by eqxDev** [simogeo/Filemanager#536]
Hi,

I am using simogeo/Filemanager found on github using composer. It never loads any files I think it may be caused by an error I am seeing in network that follows: URL/filemanager/connectors/php/filemanager.php?path=%2F&config=filemanager.config.js&mode=getfolder&showThumbs=true&time=940

I have checked the filemanager folder is in the public folder yet it still is going though the route controller?

(1/1) NotFoundHttpException in RouteCollection.php (line 179)

Please any help will be amazing!

Kind Regards.

**Comment by servocoder** [comment]
This repo hasn't been supported anymore.

You can try out [RichFileManager](https://github.com/servocoder/RichFilemanager)

I'm going to add Laravel support out of the box soon. Meanwhile it's possible to run RFM with Laravel with some adjustments: https://github.com/servocoder/RichFilemanager-PHP/issues/10
