### ISSUE TITLE
Does "expandedFolder" option works?

### ISSUE THREAD

**Issue by dsu** [simogeo/Filemanager#539]
I would like to set the current directory of a file manager. Preferably by JS API.
I have tried _expandedFolder_ parameter. I can see a second Ajax request that fetches a content of that directory, but file manager shows root directory. 
It doesn't work in demo application either:
[http://fm.devale.pro/index.html?expandedFolder=My](http://fm.devale.pro/index.html?expandedFolder=My)

**Comment by psolom** [comment]
You are at the wrong repository.
This one is deprecated, and the demo that you mentioned is refered to the https://github.com/servocoder/RichFilemanager repository

Duplicate this issue in the right repo and I will check the issue and provide reply.
