### ISSUE TITLE
Why no double underscores in file names?

### ISSUE THREAD

**Issue by robsch** [simogeo/Filemanager#540]
I have found that cleanString() removes multiple underscores. Is there a special reason for this? Can I just drop this line (and in PHP the corresponding line in filemanager.class.php) if I want to allow muliple underscores? Or does that cause any problems?

**Comment by simogeo** [comment]
It should not cause any trouble. You're free to remove pattern in cleanstrint() methods - both php and js files

**Comment by simogeo** [comment]
BY the way, see also : https://github.com/servocoder/RichFilemanager

**Comment by robsch** [comment]
Thanks! 

Of course I know already the RichFilemanager. Will switch to it asap.
