### ISSUE TITLE
unable to play Audio and video files, view pdf's

### ISSUE THREAD

**Issue by Krishnachaitanya4167** [simogeo/Filemanager#541]
#![screenshot from 2017-11-20 17-08-20](https://user-images.githubusercontent.com/25736001/33016762-c421ec42-ce15-11e7-9def-d87d609048bd.png)

If i try to specify user defined folder iam unable to access media fies because of unable to load media 404 error

**Comment by simogeo** [comment]
Please switch to https://github.com/servocoder/RichFilemanager project.
