### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by robertnicjoo** [simogeo/Filemanager#545]
hi,

I would like to know how can I give ability to certain users to manage my files?

currently whom ever try to visit my url such as:

```php
http://domain/ckeditor/filemanager/dialog.php
```

can have access to all my uploaded files.

PS: I'm using laravel, basically i'm looking for some sort of route middleware  like that, but any other way can provide me what i'm looking for is ok by me :)

thanks.

**Comment by simogeo** [comment]
1. This version is not maintained anymore. Please use RichFilemanager instead
2. There is no `dialog.php` file as you refer in FM standard realease !?

**Comment by psolom** [comment]
I have written a new article about integration of RichFilemanager with Laravel framework: https://github.com/servocoder/RichFilemanager-PHP/wiki/Laravel-framework

However if you are new to RichFilemanager I advice you to start from reading wiki of the packages:
https://github.com/servocoder/RichFilemanager/wiki
https://github.com/servocoder/RichFilemanager-PHP/wiki
