### ISSUE TITLE
Directory recursion with ColdFusion connector

### ISSUE THREAD

**Issue by doncx** [simogeo/Filemanager#92]
I am successfully using an old version of the C5 filemanager, from last winter.

I am trying to upgrade both my CKEditor and Simogeo Filemanager to current versions, and am having a simple problem with 853c1fb:

When I open a directory in filemanager (images, for instance), either by double-clicking in the main area, or by clicking in the file tree sidebar, a new set of the top level folders (file, flash, image, media) open below the previous level.  This goes on and on, nesting deeper and deeper.  But the directories aren't actually created, they are just displayed as nested.

A second, likely related problem, is that when I attempt to upload, I get the error: "Invalid var ."

I suppose this could be a setup problem, but I have followed directions.

I should note that I am using a non-standard directory for upload storage, "/content/editor".

Any ideas?

Thanks,

- Don

**Comment by simogeo** [comment]
Will be reopened in case a CFM maintainer let him know
